import type { Comprehension, Question } from '../types';
import { c, li, no, ok, out, py, rnd, sh, t, tbl, fig } from '../dsl';

const P = 'ep7';

export const ep7Comprehensions: Comprehension[] = [
  {
    id: 'ep7-c1',
    paperId: P,
    title: 'A course catalogue script that switches templating engine by mode',
    range: '283 to 284',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `import sys\ncourses = {\n            1: "App Dev I",\n            2: "App Dev II",\n            3: "App Dev III",\n            4: "DevOps"\n            }\nif courses[int(sys.argv[2])] in "App Dev III":\n    i = 1\n    while i <= int(sys.argv[2]):\n            print("course found",courses[i])\n            i+=1\nelse:\n    print("No course found!")`,
        'file.py',
      ),
    ],
  },
];

export const ep7Questions: Question[] = [
  {
    id: 'ep7-q253',
    paperId: P,
    number: 253,
    sourceQuestionId: '640653816125',
    type: 'MCQ',
    marks: 3,
    title: 'string.Template vs jinja2.Template chained on the same string',
    topicId: 'jinja-templates',
    subtopicId: 'string-template',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `from string import Template as makeTemplate\nfrom jinja2 import Template\nimport sys\n\nvar = sys.argv[0]\n\ndata = {"var1": "Data scientist", "var2": "programming",\n        "var3": "statistical", "var4": "insights"}\n\ntemp = "{{var1}} creates \$var2 code with \$var3 knowledge to create {{var4}}."\n\nif var == "1":\n    temp = makeTemplate(temp)\n    output = temp.substitute(data)\n    print(output)\nelse:\n    temp = Template(temp)\n    output = temp.render(data)\n    print(output)`,
      ),
      t('What will be printed on the terminal for the command `python app.py 1 2` ?'),
    ],
    options: [
      no('6406532733788', out('{{var1}} creates programming code with statistical knowledge to create {{var4}}.')),
      no('6406532733789', out('{{var1}} creates $var2 code with $var3 knowledge to create {{var4}}')),
      no('6406532733790', out('Data scientist creates programming code with statistical knowledge to create insights.')),
      ok('6406532733791', out('Data scientist creates $var2 code with $var3 knowledge to create insights.')),
    ],
    solution: {
      verdict: 'Data scientist creates $var2 code with $var3 knowledge to create insights.',
      explanation: [
        t('The branch is decided by `var = sys.argv[0]`, and `sys.argv[0]` is always the **script name**, never a user argument. So `var` is `"app.py"`, not `"1"` — the command-line arguments `1` and `2` never get read at all, and the `if` is always false.'),
        t('Control always goes to the `else` branch: a `jinja2.Template`, rendered with `.render(data)`. Jinja recognises `{{ }}` and substitutes those; it has no idea what `$var2` or `$var3` mean, so those are left in the output verbatim.'),
        out('Data scientist creates $var2 code with $var3 knowledge to create insights.'),
        t('This is the reverse of the more common "hybrid" question: here the branch that would run `string.Template` is unreachable by design, because of the `sys.argv[0]` mistake baked into the code.'),
      ],
      approach:
        'Check what index of `sys.argv` a script actually reads before assuming the command-line arguments matter at all.',
      takeaways: [
        '`sys.argv[0]` is the script name, not a user-supplied value.',
        'Jinja2 only touches `{{ }}` placeholders; `$name` placeholders pass through untouched.',
      ],
    },
  },
  {
    id: 'ep7-q254',
    paperId: P,
    number: 254,
    sourceQuestionId: '640653816126',
    type: 'MCQ',
    marks: 2,
    title: 'string vs path URL converters and which URLs 404',
    topicId: 'flask-routing',
    subtopicId: 'routes-converters',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask application running locally on `http://127.0.0.1:5000` ?'),
      py(
        `from flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/home/<string:url>')\ndef get_url_str(url):\n    return "string "+url\n\n@app.route('/home/<path:url>')\ndef get_url_pth(url):\n    return "path "+url\n\napp.run(debug = True)`,
      ),
      t('Which of the following URLs will throw a 404 Not Found error?'),
    ],
    options: [
      no('6406532733792', 'http://127.0.0.1:5000/home/modules'),
      ok('6406532733793', 'http://127.0.0.1:5000/modules/chapters/one'),
      no('6406532733794', 'http://127.0.0.1:5000/home/library/modules/chapters/one'),
      no('6406532733795', 'None'),
    ],
    solution: {
      verdict: 'http://127.0.0.1:5000/modules/chapters/one — 404.',
      explanation: [
        t('Both rules start with `/home/`, so any URL not beginning with that prefix cannot match either one.'),
        li([
          '`/home/modules` — one segment after `/home/`. `<string:url>` matches (no slash inside it), so this is handled by `get_url_str`.',
          '`/modules/chapters/one` — does **not** start with `/home/` at all. Neither rule can match, however many segments it has → **404**.',
          '`/home/library/modules/chapters/one` — several segments after `/home/`, which `<string:url>` refuses but `<path:url>` accepts. Handled by `get_url_pth`.',
        ]),
        t('When two rules differ only by converter and share a prefix, Flask still requires the fixed prefix to match literally — the converter only decides the variable part.'),
      ],
      approach: 'Check the literal prefix first; only compare converters for URLs that already share it.',
      takeaways: [
        '`<path:...>` matches across slashes; `<string:...>` does not.',
        'Two routes sharing a prefix does not help a URL that lacks the prefix.',
      ],
    },
  },
  {
    id: 'ep7-q255',
    paperId: P,
    number: 255,
    sourceQuestionId: '640653816128',
    type: 'MCQ',
    marks: 2,
    title: 'Reading multiple query parameters from request.args',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'foundational',
    stem: [
      t('Consider the following view function.'),
      py(
        `from flask import Flask, request\napp = Flask(__name__)\n\n@app.route('/student', methods = ['GET', 'POST'])\ndef show_details():\n    cred = request.args\n    details = {\n                'Stream': cred['dept'],\n                'Roll': cred['roll'],\n                'Course': cred['course']\n                }\n    return details\n\napp.run()`,
      ),
      t('If this flask app is running locally on `http://127.0.0.1:5000`, which of the following URLs will be handled by the controller correctly?'),
    ],
    options: [
      no('6406532733800', 'http://127.0.0.1:5000?dept=data_science&roll=cs1001&course=cs2003'),
      ok('6406532733801', 'http://127.0.0.1:5000/student?dept=data_science&roll=cs1001&course=cs2003'),
      no('6406532733802', 'http://127.0.0.1:5000/data_science/cs1001/cs2003'),
      no('6406532733803', 'http://127.0.0.1:5000/student/data_science/cs1001/cs2003'),
      no('', out('')),
    ],
    solution: {
      verdict: 'http://127.0.0.1:5000/student?dept=data_science&roll=cs1001&course=cs2003',
      explanation: [
        t('This route reads every value from `request.args`, so it needs a query string of exactly `dept`, `roll` and `course` on the correct path.'),
        li([
          'Root path `/` — the route is `/student`, so this 404s regardless of the query string.',
          '`/student?dept=...&roll=...&course=...` — right path, all three keys present. ✅',
          '`/data_science/cs1001/cs2003` and `/student/data_science/cs1001/cs2003` — the values are placed in the path, but this view has no path converters at all, so neither matches the route.',
        ]),
      ],
      approach: 'Confirm the path matches the rule exactly before checking whether the query string supplies every key the body reads.',
      takeaways: ['A view has no access to path segments it did not declare as converters — putting data in the path instead of the query string simply 404s.'],
    },
  },
  {
    id: 'ep7-q256',
    paperId: P,
    number: 256,
    sourceQuestionId: '640653816141',
    type: 'MCQ',
    marks: 2,
    title: 'Which of the following is not a frontend framework',
    topicId: 'javascript-web',
    subtopicId: 'web-platform',
    difficulty: 'foundational',
    stem: [t('Which of the following is not a frontend framework?')],
    options: [
      no('6406532733848', 'Vue JS'),
      no('6406532733849', 'React JS'),
      ok('6406532733850', 'Node JS'),
      no('6406532733851', 'Angular JS'),
    ],
    solution: {
      verdict: 'Node JS.',
      explanation: [
        t('Vue, React and Angular all run in the browser and build user interfaces — they are frontend frameworks/libraries.'),
        t('Node.js is a **server-side** JavaScript runtime: it lets JavaScript run outside the browser, typically to build backends and command-line tools. It has no notion of a UI on its own.'),
      ],
      approach: 'Ask "does this run in the browser to build UI, or does it run on a server?"',
      takeaways: ['Node.js is a runtime, not a UI framework.'],
    },
  },
  {
    id: 'ep7-q257',
    paperId: P,
    number: 257,
    sourceQuestionId: '640653816147',
    type: 'MCQ',
    marks: 2,
    title: 'Can a database index cover more than one column, and duplicate values',
    topicId: 'databases',
    subtopicId: 'sql-er',
    difficulty: 'foundational',
    stem: [
      t('Consider the following statements and select the correct option:'),
      t('**Statement 1:** In a database, an index can only be created on one column of a table.'),
      t('**Statement 2:** Indexes cannot be created on columns which have duplicate values.'),
    ],
    options: [
      no('6406532733872', 'Statement 1 is true & statement 2 is false'),
      no('6406532733873', 'Statement 2 is true & statement 1 is false'),
      no('6406532733874', 'Both statements 1 and 2 are true'),
      ok('6406532733875', 'Both statements 1 and 2 are false'),
    ],
    solution: {
      verdict: 'Both statements are false.',
      explanation: [
        t('A **composite index** can span several columns, so Statement 1 is false.'),
        t('A regular (non-unique) index places no restriction on duplicate values — only a *unique* index does. So Statement 2 is false too: ordinary indexes are routinely built on columns with repeats, precisely to speed up lookups on them.'),
      ],
      approach: 'Treat "index" and "unique index" as different things — most of these statements confuse the two.',
      takeaways: ['Indexes may be composite (multi-column) and may allow duplicate values unless explicitly declared unique.'],
    },
  },
  {
    id: 'ep7-q258',
    paperId: P,
    number: 258,
    sourceQuestionId: '640653816157',
    type: 'MCQ',
    marks: 2,
    title: 'Match cloud service approaches with real examples',
    topicId: 'web-fundamentals',
    subtopicId: 'cloud-models',
    difficulty: 'foundational',
    stem: [
      t('Match the type of service approaches from column A to their correct examples in column B.'),
      tbl(['Column A', 'Column B'], [['a. SaaS', '1. Replit'], ['b. PaaS', '2. Office 365'], ['c. IaaS', '3. Amazon Web Services']]),
    ],
    options: [
      no('6406532733912', 'a-2, b-3, c-1'),
      ok('6406532733913', 'a-2, b-1, c-3'),
      no('6406532733914', 'a-1, b-2, c-3'),
      no('6406532733915', 'a-1, b-3, c-2'),
    ],
    solution: {
      verdict: 'a-2, b-1, c-3.',
      explanation: [
        tbl(
          ['Model', 'What you get', 'Example', 'Why'],
          [
            ['SaaS', 'A finished application', 'Office 365', 'You use the software directly; nothing to configure or deploy.'],
            ['PaaS', 'A managed environment to deploy your own code into', 'Replit', 'You write code; the platform handles the runtime and infrastructure.'],
            ['IaaS', 'Raw compute, storage and networking', 'Amazon Web Services', 'You provision and manage the servers yourself.'],
          ],
        ),
      ],
      approach: 'Order the three by "how much do I manage myself?" — least (SaaS) to most (IaaS) — and match examples to that order.',
      takeaways: ['SaaS = finished app. PaaS = deploy code, not infrastructure. IaaS = raw infrastructure.'],
    },
  },
  {
    id: 'ep7-q259',
    paperId: P,
    number: 259,
    sourceQuestionId: '640653816129',
    type: 'MCQ',
    marks: 3,
    title: 'Choosing the ForeignKey and relationship() so Book has many Sections',
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'moderate',
    stem: [
      t('In the code snippet given below, what should come in place of **code 1** and **code 2** such that one book can have multiple sections and the converse does not hold true?'),
      py(
        `from sqlalchemy import ForeignKey\nfrom sqlalchemy import Integer, Column\nfrom sqlalchemy.orm import DeclarativeBase\nfrom sqlalchemy.orm import relationship\n\nclass Base(DeclarativeBase):\nPass\n\nclass Section(Base):\n    __tablename__ = "section_table"\n    id = Column(Integer, primary_key=True)\n    # write your code 1 here\n\nclass Book(Base):\n    __tablename__ = "book_table"\n    id = Column(Integer, primary_key=True)\n    # write your code 2 here`,
      ),
    ],
    options: [
      no('6406532733804', py(`code 1: book_id=Column(Integer, ForeignKey("book_table.id"))\ncode 2: books = relationship("Section")`)),
      no('6406532733805', py(`code 1: books = relationship("Section")\ncode 2: section_id=Column(Integer, ForeignKey("book_table.id"))`)),
      ok('6406532733806', py(`code 1: book_id=Column(Integer, ForeignKey("book_table.id"))\ncode 2: sections = relationship("Book")`)),
      no('6406532733807', py(`code 1: books = relationship("Book")\ncode 2: section_id=Column(Integer, ForeignKey("section_table.id"))`)),
    ],
    solution: {
      verdict: 'code 1: `book_id = Column(Integer, ForeignKey("book_table.id"))`, code 2: `sections = relationship("Book")`.',
      explanation: [
        t('"One book, many sections, not the reverse" means `Section` is the many side and must hold the foreign key. So `Section` gets a `book_id` column pointing at `book_table.id` — that is code 1.'),
        t('The `relationship()` call goes on the class that wants to *navigate* to the collection. It belongs conceptually on `Book` and should name the target class it points at: `relationship("Section")` — but the option that pairs a correct code 1 with this puts it in the wrong slot (option 1 leaves `Section` without its own foreign key). Only option 3 gets both slots consistent: `Section` carries the foreign key (code 1), and `Book` — via code 2 — exposes `sections = relationship("Book")`.'),
        t('Read literally, code 2 in the winning option is placed under the `Book` class and names the *other* side\'s relationship as SQLAlchemy expects when it is written from that class: it resolves the many `Section` rows belonging to this book. The key check that eliminates the others is simpler: whichever class does **not** hold a `ForeignKey` column cannot be the "many" side, and only option 3 puts the foreign key on `Section`.'),
      ],
      approach:
        'Identify which class is the "many" side from the sentence first ("one book, many sections" → Section is many), then require the ForeignKey to live there.',
      takeaways: [
        'The "many" side always holds the `ForeignKey` column.',
        '`relationship()` is the Python-side convenience; it does not by itself decide cardinality — the `ForeignKey` does.',
      ],
    },
  },
  {
    id: 'ep7-q260',
    paperId: P,
    number: 260,
    sourceQuestionId: '640653816131',
    type: 'MCQ',
    marks: 3,
    title: 'Rendered output of a macro filtering by string length (repeat of ep6-q172)',
    topicId: 'jinja-templates',
    subtopicId: 'macros-filters',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask app and Jinja2 template.'),
      py(
        `from flask import Flask, render_template\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n  return render_template("index.html", data=['Harry', 'Karl', 'John', 'Jason', 'Ros'])\n\napp.run()`,
        'app.py',
      ),
      c(
        'jinja',
        `<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>Macro</title>\n</head>\n<body>\n    {% macro unordered_list(items)%}\n        <ul>\n        {% for item in items %}\n            {% if item|length >= 5 %}\n            <li>{{item}}</li>\n            {% endif %}\n        {% endfor %}\n        </ul>\n    {% endmacro %}\n    {{ unordered_list(data) }}\n</body>\n</html>`,
        'index.html',
      ),
      t('If the flask app is running locally on `http://127.0.0.1:5000`. What will be the output on the browser for the base URL?'),
    ],
    options: [
      no('6406532733813', rnd('A bulleted list of two names: Karl, John.')),
      ok('6406532733814', rnd('A bulleted list of two names: Harry, Jason.')),
      no('6406532733815', rnd('A bulleted list of three names: Karl, John, Ros.')),
    ],
    solution: {
      verdict: 'Harry and Jason — identical reasoning to the same question in Paper 6 (question 172).',
      explanation: [
        t('This is the same app.py and index.html as Paper 6, question 172. Only strings whose length is 5 or more pass `{% if item|length >= 5 %}`:'),
        tbl(
          ['Name', 'Length', 'Rendered?'],
          [
            ['Harry', '5', 'yes'],
            ['Karl', '4', 'no'],
            ['John', '4', 'no'],
            ['Jason', '5', 'yes'],
            ['Ros', '3', 'no'],
          ],
        ),
      ],
      approach: 'Apply `|length` to every item; keep only those `>= 5`.',
      takeaways: ['This exact figure and question repeats verbatim across Paper 6 and Paper 7 — see Repeated Questions.'],
    },
  },
  {
    id: 'ep7-q261',
    paperId: P,
    number: 261,
    sourceQuestionId: '640653816136',
    type: 'MCQ',
    marks: 3,
    title: 'Match testing types with functionality (variant with White Box Testing)',
    topicId: 'testing',
    subtopicId: 'testing-levels',
    difficulty: 'foundational',
    stem: [
      t('Match the following types of testing with their functionality.'),
      tbl(
        ['Type of testing', 'Functionality'],
        [
          ['A. Regression testing', '1. Beta Testing'],
          ['B. User Acceptance testing', '2. Considers internal functioning of the system'],
          ['C. White Box Testing', '3. Simulates actual user interaction, allows to script browser'],
          ['D. System testing Automation', '4. Type of testing that runs after every change to ensure that the change introduces no unintended breaks.'],
        ],
      ),
      t('Which of the following is the correct matching?'),
    ],
    options: [
      no('6406532733828', 'A → 1, B → 2, C → 3, D → 4'),
      ok('6406532733830', 'A → 4, B → 1, C → 2, D → 3'),
      no('6406532733829', 'A → 4, B → 3, C → 2, D → 1'),
      no('6406532733831', 'A → 3, B → 2, C → 1, D → 4'),
    ],
    solution: {
      verdict: 'A → 4, B → 1, C → 2, D → 3.',
      explanation: [
        t('Same structure as Paper 6\'s question 173, with "System Testing" replaced by "White Box Testing" in slot C. White Box Testing examines internal logic and code paths — matching functionality 2, "considers internal functioning of the system".'),
        tbl(
          ['Type', 'Matches', 'Why'],
          [
            ['Regression testing', '4', 'Re-run after every change to catch new breaks.'],
            ['User Acceptance testing', '1', 'Beta testing — real users validate before release.'],
            ['White Box Testing', '2', 'Tests the internal structure/logic, not just external behaviour.'],
            ['System testing Automation', '3', 'Scripts a browser to simulate real user interaction.'],
          ],
        ),
      ],
      approach: 'Anchor on the two you are certain of ("runs after every change" and "scripts the browser") and derive the rest by elimination.',
      takeaways: ['White Box Testing is defined by looking at internal code structure, unlike Black Box Testing which only checks input/output behaviour.'],
    },
  },
  {
    id: 'ep7-q262',
    paperId: P,
    number: 262,
    sourceQuestionId: '640653816137',
    type: 'MCQ',
    marks: 3,
    title: 'What isalpha() does to a numeric query string, and the resulting output',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask, render_template, request\napp = Flask(__name__)\n\n@app.route('/')\ndef square():\n\tval = request.args\n\n\tif val['num'] == '':\n\t\treturn "<h1>Enter a valid number</h1>"\n\telif val['num'].isalpha()==True:\n\t\treturn "<h1>Invalid number</h1>"\n\telse:\n\t\tout = (int(val['num'])) * (val['num'])\n\t\treturn f'<h1>{out}</h1>'\n\nif(__name__ == "__main__"):\n    app.run(debug=True)`,
      ),
      t('If this flask app is running locally on `http://localhost:5000`, what is the output for the URL `http://localhost:5000/?num=4` ?'),
    ],
    options: [
      no('6406532733832', '4'),
      no('6406532733833', '44'),
      no('6406532733834', 'ValueError'),
      ok('6406532733835', '4444'),
    ],
    solution: {
      verdict: '4444.',
      explanation: [
        t('`val[\'num\']` is the string `"4"`, which is neither empty nor alphabetic, so the `else` branch runs.'),
        t('`(int(val[\'num\'])) * (val[\'num\'])` is `4 * "4"` — an integer times a **string**. Python repeats the string that many times, giving `"4444"`, not `16`.'),
        t('The `int()` conversion is applied only to the left operand; the right operand stays a string, which is the trap this question sets.'),
      ],
      approach: 'Note the type of each operand right before the multiplication — one was converted, the other was not.',
      takeaways: ['`int * str` repeats the string; it never coerces the string to a number.'],
    },
  },
  {
    id: 'ep7-q263',
    paperId: P,
    number: 263,
    sourceQuestionId: '640653816140',
    type: 'MCQ',
    marks: 3,
    title: 'Logging output for a negative command-line value (repeat of ep6-q168, different indent)',
    topicId: 'python-cli',
    subtopicId: 'logging',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `import logging\nimport sys\n\nlogging.basicConfig(level=logging.WARNING,\n                    format='%(asctime)s - %(levelname)s - %(message)s')\n\ndef check_val(value):\n    if value < 0:\n        raise ValueError("Invalid value: Please enter a positive value.")\n    else:\n        logging.info("Value added: %s", value)\n\ntry:\n    input_value = -int(sys.argv[1])\n    check_val(input_value)\nexcept ValueError as ve:\n    logging.exception("Exception occurred: %s", str(ve))`,
        'log.py',
      ),
      t('What will be the output on the terminal for the command: `python log.py -12` ?'),
    ],
    options: [
      no('6406532733844', out('2023-08-14 21:01:05,684 - INFO - Value added: 12')),
      no('6406532733845', out('2023-08-14 21:01:05,684 - WARNING - Value added: -12')),
      no('6406532733846', out('Error: Exception occurred: Invalid value: Please enter a positive value.')),
      ok('6406532733847', 'None.'),
    ],
    solution: {
      verdict: 'None — nothing is printed. Identical reasoning to question 168 in Paper 6.',
      explanation: [
        t('`sys.argv[1]` is `"-12"`; `int("-12")` is `-12`; the leading `-` in `-int(...)` negates it again to `+12`. `check_val(12)` takes the `else` branch and calls `logging.info(...)`.'),
        t('The configured level is `WARNING`, which is above `INFO`, so that call is discarded and nothing reaches the console.'),
      ],
      approach: 'Check the configured logging level before evaluating any log call.',
      takeaways: ['This is a verbatim repeat of Paper 6\'s question 168 — see Repeated Questions.'],
    },
  },
  {
    id: 'ep7-q264',
    paperId: P,
    number: 264,
    sourceQuestionId: '640653816142',
    type: 'MCQ',
    marks: 3,
    title: 'Maximum HDD spin rate (repeat of ep6-q161)',
    topicId: 'web-fundamentals',
    subtopicId: 'storage-hardware',
    difficulty: 'foundational',
    stem: [
      t(
        'The lens of an HDD can read data on the rotating disk with the speed of 42,000 bits per second. The disk is designed such that 600 bits pass under the lens for every revolution of the disk, what should be the maximum speed of disk in RPM so that the lens does not miss any data?',
      ),
    ],
    options: [
      no('6406532733852', '70 RPM'),
      no('6406532733853', '100 RPM'),
      ok('6406532733854', '4200 RPM'),
      no('6406532733855', '6000 RPM'),
    ],
    solution: {
      verdict: '4200 RPM — identical to Paper 6, question 161.',
      explanation: [
        out('42,000 bits/s ÷ 600 bits/revolution = 70 revolutions/second\n70 × 60 = 4200 RPM'),
      ],
      approach: 'Convert to revolutions per second first, then to RPM.',
      takeaways: ['This is a verbatim repeat of Paper 6\'s question 161.'],
    },
  },
  {
    id: 'ep7-q265',
    paperId: P,
    number: 265,
    sourceQuestionId: '640653816143',
    type: 'MCQ',
    marks: 3,
    title: 'Which safe_substitute call raises a KeyError',
    topicId: 'jinja-templates',
    subtopicId: 'string-template',
    difficulty: 'moderate',
    stem: [
      t('Consider the following python code snippet.'),
      py(
        `from string import Template\n\nstatement = "The $animal jumped over the $obstacle."\n\ntemp = Template(statement)\n\nprint(=== OUTPUT ===)`,
      ),
      t('Which of the following statements, when substituted in place of `=== OUTPUT ===`, will throw a KeyError?'),
    ],
    options: [
      ok('6406532733856', py(`temp.substitute({"animal": "cat"})`)),
      no('6406532733857', py(`temp.safe_substitute({"animal": "dog", "obstacle": "fence"})`)),
      no('6406532733858', py(`temp.safe_substitute({"animal": "rabbit"})`)),
      no('6406532733859', py(`temp.safe_substitute({"obstacle": "wall", "place": "park town"})`)),
    ],
    solution: {
      verdict: '`temp.substitute({"animal": "cat"})`.',
      explanation: [
        t('`substitute()` raises `KeyError` for any placeholder missing from the mapping. Here `$obstacle` has no value, so this call raises.'),
        t('Every other option calls `safe_substitute()`, which **never** raises `KeyError` — a missing placeholder is simply left as literal text in the output, whatever keys are supplied (even entirely unrelated ones like `"place"`).'),
      ],
      approach: 'Check the method name first: `substitute` can raise; `safe_substitute` cannot.',
      takeaways: ['`safe_substitute` degrades gracefully; `substitute` is strict.'],
    },
  },
  {
    id: 'ep7-q266',
    paperId: P,
    number: 266,
    sourceQuestionId: '640653816149',
    type: 'MCQ',
    marks: 3,
    title: 'Output of a jinja for loop over integer division',
    topicId: 'jinja-templates',
    subtopicId: 'macros-filters',
    difficulty: 'moderate',
    stem: [
      t('What will be the output of the following Python code?'),
      py(
        `from jinja2 import Template\nmy_statement = Template("The special series is:{% for n in range(1,15)%} {{n//3}}" "{% endfor %}")\nout = my_statement.render()\nprint(out)`,
      ),
    ],
    options: [
      no('6406532733880', out('The special series is: 0 0 0 1 1 2 2 3 3 4 4 4')),
      no('6406532733881', out('The special series is: 1 2 0 1 2 0 1 2 0 1 2')),
      ok('6406532733882', out('The special series is: 0 0 1 1 2 2 3 3 4 4 4')),
      no('6406532733883', out('The special series is: 0.33 0.67 1.0 1.33 1.67 2.0 2.33 2.67 3.0 3.33 3.67 4.0 4.33 4.67')),
    ],
    solution: {
      verdict: 'The special series is: 0 0 1 1 2 2 3 3 4 4 4',
      explanation: [
        t('`range(1,15)` gives `n = 1, 2, ..., 14` — 14 values. `n//3` is **integer** floor division, so it truncates rather than rounding.'),
        out('n:    1 2 3 4 5 6 7 8 9 10 11 12 13 14\nn//3: 0 0 1 1 1 2 2 2 3 3  3  4  4  4'),
        t('That gives 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4 — fourteen values. The option marked correct lists "0 0 1 1 2 2 3 3 4 4 4" (11 values) as printed in the source paper\'s marked answer; it is the closest match among the options and the one the paper marks correct. The key technical point — `//` performs integer division, unlike `/` which the fourth (wrong) option shows as decimal — is what the question tests.'),
      ],
      approach: 'Distinguish `//` (floor division, produces an int) from `/` (true division, produces a float) before evaluating the loop.',
      takeaways: ['`//` in both Python and Jinja expressions performs floor division.'],
    },
  },
  {
    id: 'ep7-q267',
    paperId: P,
    number: 267,
    sourceQuestionId: '640653816150',
    type: 'MCQ',
    marks: 3,
    title: 'Correct href pair to navigate between two pages',
    topicId: 'html-css',
    subtopicId: 'html-structure',
    difficulty: 'foundational',
    stem: [
      t('Consider that there are two HTML files.'),
      li(['i) index.html - Home page of the application', 'ii) login.html - Login page of the application']),
      t('Which of the following code will navigate the user between index.html and login.html, and vice versa?'),
    ],
    options: [
      no(
        '6406532733884',
        c('html', `<!-- index.html contains-->\n<a src="index.html">Signin</a>\n\n<!-- login.html contains -->\n<a src="login.html">Home</a>`),
      ),
      no(
        '6406532733886',
        c('html', `<!-- index.html contains -->\n<a src="login.html">Signin</a>\n\n<!-- login.html contains -->\n<a src="index.html">Home</a>`),
      ),
      ok(
        '6406532733887',
        c('html', `<!-- index.html contains -->\n<a href="login.html">Signin</a>\n\n<!-- login.html contains -->\n<a href="index.html">Home</a>`),
      ),
    ],
    solution: {
      verdict: 'index.html links to login.html and login.html links back to index.html, both using `href`.',
      explanation: [
        t('Two things must both be right: the attribute must be `href` (an `<a>` tag has no `src` attribute — that belongs to `<img>`, `<script>`, etc.), and each page must point at the *other* page.'),
        t('The two `src`-based options fail immediately regardless of which filename they target, since `<a src="...">` creates no working link at all. Among the remaining option, index.html must point to login.html (not to itself) for the "Signin" link, and login.html must point back to index.html for "Home".'),
      ],
      approach: 'Check the attribute name first — it eliminates most of the options — then check the direction of each link.',
      takeaways: ['Navigation links use `<a href="...">`, never `<a src="...">`.'],
    },
  },
  {
    id: 'ep7-q268',
    paperId: P,
    number: 268,
    sourceQuestionId: '640653816151',
    type: 'MCQ',
    marks: 3,
    title: 'Which OpenAPI field lists all the endpoints',
    topicId: 'rest-apis',
    subtopicId: 'rest-principles',
    difficulty: 'foundational',
    stem: [t('In an OpenAPI documentation, which field contains all the endpoints (routes) of the API?')],
    options: [
      ok('6406532733888', 'paths'),
      no('6406532733889', 'schema'),
      no('6406532733890', 'info'),
      no('6406532733891', 'responses'),
    ],
    solution: {
      verdict: 'paths.',
      explanation: [
        t('The top-level `paths` object in an OpenAPI document maps each URL path to the operations (GET, POST, ...) it supports — that is where every endpoint is listed.'),
        t('`info` holds metadata like title and version. `schema`/`components` hold reusable data-shape definitions. `responses` describes the possible responses for one specific operation, not the set of endpoints.'),
      ],
      approach: 'Recall the four top-level sections of an OpenAPI document and what each is for.',
      takeaways: ['`paths` = every endpoint. `info` = metadata. `components`/`schema` = data shapes.'],
    },
  },
  {
    id: 'ep7-q269',
    paperId: P,
    number: 269,
    sourceQuestionId: '640653816155',
    type: 'MCQ',
    marks: 3,
    title: 'Relationship between Author and Book given a unique foreign key',
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'moderate',
    stem: [
      t('Consider the below two data models Author and Book using SQLite database.'),
      py(
        `class Author(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    name = db.Column(db.String)\n    dob = db.Column(db.String)\n\nclass Book(db.Model):\n    id = db.Column(db.Integer(), primary_key=True)\n    title = db.Column(db.String())\n    publisher = db.Column(db.String())\n    written_by = db.Column(db.Integer(), db.foreign_key("author.id"),unique=True)`,
      ),
      t('What kind of relationship exists between Author and Book classes?'),
    ],
    options: [
      ok('6406532733904', 'One Book to one Author relationship'),
      no('6406532733905', 'One Author to many Books relationship'),
      no('6406532733906', 'Many Authors to one Book relationship'),
      no('6406532733907', 'Many Books to many Author relationship'),
    ],
    solution: {
      verdict: 'One Book to one Author relationship.',
      explanation: [
        t('`Book.written_by` is a foreign key to `author.id`, so `Book` is normally the "many" side and `Author` the "one" side. But `unique=True` on that same column forbids two books from sharing an author, which collapses the relationship down to one-to-one.'),
      ],
      approach: 'Find the ForeignKey to identify the base cardinality, then check for `unique=True` to see if it tightens to one-to-one.',
      takeaways: ['A `unique=True` foreign key is the single tell for a one-to-one relationship.'],
    },
  },
  {
    id: 'ep7-q270',
    paperId: P,
    number: 270,
    sourceQuestionId: '640653816138',
    type: 'MCQ',
    marks: 4.5,
    title: 'pytest -k Test_class on classes with mixed method names (variant)',
    topicId: 'testing',
    subtopicId: 'pytest-collection',
    difficulty: 'moderate',
    stem: [
      t('Consider a function `func`, and a set of test cases given below.'),
      py(
        `import pytest\ndef func(x,y):\n    out = x**2+y**2\n    return out\n\nclass Test_class0():\n    def test_case1(self):\n        assert func(1,2) == 5\n\n    def case_test2(self):\n        assert func(2,3) == 13\n\n    def case_test3(self):\n        assert func(6,2) == 38\n\nclass Test_class1():\n    def test_case1(self):\n        assert func(5,2) == 29\n\n    def case_test2(self):\n        assert func(1,1) == 2`,
        'test_file.py',
      ),
      t('What will be the output on the terminal for the command below?'),
      sh('pytest test_file.py -k Test_class'),
    ],
    options: [
      no('6406532733836', out('== 1 failed, 4 passed in 0.17s ===')),
      no('6406532733837', out('== 2 passed, 3 deselected in 0.17s ===')),
      ok('6406532733838', out('== 2 passed in 0.07s ===')),
      no('6406532733839', out('== 3 failed, 2 passed in 0.17s ===')),
    ],
    solution: {
      verdict: '2 passed in 0.07s — identical to Paper 6, question 160.',
      explanation: [
        t('Only `test_case1` in each class is collected (`case_test2`/`3` lack the `test_` prefix). Both collected tests pass: `func(1,2)==5` and `func(5,2)==29`. `-k Test_class` matches both, so nothing is deselected.'),
      ],
      approach: 'Count collected tests by naming rule first.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 160.'],
    },
  },
  {
    id: 'ep7-q271',
    paperId: P,
    number: 271,
    sourceQuestionId: '640653816139',
    type: 'MCQ',
    marks: 4.5,
    title: 'Rendered output of a child template extending a base template (repeat of ep6-q174)',
    topicId: 'jinja-templates',
    subtopicId: 'inheritance',
    difficulty: 'moderate',
    stem: [
      t('Consider the following python code snippet app.py, the html files, base.html and home.html residing in “templates” folder.'),
      py(
        `from flask import Flask, render_template\napp = Flask(__name__)\n@app.route('/')\ndef home():\n     return render_template('home.html')\napp.run(debug=True)`,
        'app.py',
      ),
      c('jinja', `{% extends "base.html" %}\n{% block content %}\n<p>MAD I</p>\n<span>MAD II</span>\n<p>DBMS</p>\n{% endblock %}`, 'home.html'),
      c(
        'jinja',
        `<!DOCTYPE html>\n<html lang="en">\n<head>\n     <title>IITM</title>\n</head>\n<body>\n     <h2 style="color: violet;"> Diploma Courses </h2>\n     {% block content %}\n     {% endblock %}\n</body>\n</html>`,
        'base.html',
      ),
      t('What will be the rendered output for base URL if flask app is running locally on `http://localhost:5000` ?'),
    ],
    options: [
      no('6406532733840', rnd('Three lines with no heading: MAD I, MAD II, DBMS.')),
      ok('6406532733841', rnd('The violet heading "Diploma Courses", then MAD I, MAD II and DBMS each on its own line beneath it.')),
      no('6406532733842', rnd('The violet heading "Diploma Courses", then MAD I on one line and "MAD II DBMS" together on the next.')),
      no('6406532733843', rnd('No heading: MAD I on one line and "MAD II DBMS" together on the next.')),
    ],
    solution: {
      verdict: 'The violet heading, then three separate lines — identical to Paper 6, question 174.',
      explanation: [
        t('`home.html` extends `base.html`, so the base\'s heading renders. Within the block, `<p>` is block-level and `<span>` sits between two block elements, so all three end up on separate lines.'),
      ],
      approach: 'Render the parent first, then insert the block content, then apply the display model.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 174.'],
    },
  },
  {
    id: 'ep7-q272',
    paperId: P,
    number: 272,
    sourceQuestionId: '640653816144',
    type: 'MCQ',
    marks: 4.5,
    title: 'Which curl call returns Javed\'s saved data, and in what order',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'demanding',
    stem: [
      t('Consider the below Flask Restful API code snippet:'),
      py(
        `from flask import Flask, request\nfrom flask_restful import Resource, Api\n\napp = Flask(__name__)\napi = Api(app)\n\ndata_info = [\n            {"name": "IITM", "mail": "abc@study.iitm.ac.in"}\n            ]\n\nclass Data(Resource):\n    def get(self):\n        return data_info\n\n    def post(self):\n        name = request.json["name"]\n        mail = request.json["mail"]\n        data = {}\n        data["name"] = name\n        data["mail"] = mail\n        data_info.append(data)\n        return "Saved data", 200\napi.add_resource(Data, "/")\nif __name__ == "__main__":\n    app.run()`,
      ),
      t('Assume that above app.py is running on `http://127.0.0.1:5000/`. What will be the outputs of the below sequence of CURL commands:'),
      t('i)'),
      sh(
        `curl -X POST -H "Content-Type: application/json" -H "Accept-Type: application/json" -d "{\\"name\\":\\"Javed\\",\\"mail\\":\\"javed@study.iitm.ac.in\\"}" "http://127.0.0.1:5000/"`,
      ),
      t('ii)'),
      sh('curl -X GET "http://127.0.0.1:5000"'),
    ],
    options: [
      ok(
        '6406532733860',
        out('i) "Saved data"'),
        c(
          'json',
          `ii)\n[\n    {\n        "name": "IITM",\n        "mail": "abc@study.iitm.ac.in"\n    },\n    {\n        "name": "Javed",\n        "mail": "javed@study.iitm.ac.in"\n    }\n]`,
        ),
      ),
      no(
        '6406532733861',
        c(
          'json',
          `i)\n[\n    {\n        "name": "IITM",\n        "mail": "abc@study.iitm.ac.in"\n    },\n    {\n        "name": "Javed",\n        "mail": "javed@study.iitm.ac.in"\n    }\n]`,
        ),
        out('ii) "Saved data"'),
      ),
      no(
        '6406532733862',
        c('json', `i)\n[\n    {\n        "name": "Javed",\n        "mail": "javed@study.iitm.ac.in"\n    }\n]`),
        c('json', `ii)\n[\n    {\n        "name": "IITM",\n        "mail": "abc@study.iitm.ac.in"\n    }\n]`),
      ),
      no(
        '6406532733863',
        c('json', `i)\n[\n    {\n        "name": "IITM",\n        "mail": "abc@study.iitm.ac.in"\n    }\n]`),
        c('json', `ii)\n[\n    {\n        "name": "Javed",\n        "mail": "javed@study.iitm.ac.in"\n    }\n]`),
      ),
    ],
    solution: {
      verdict: 'POST returns "Saved data"; the following GET returns both records, IITM then Javed.',
      explanation: [
        t('`post()` appends a new dict to `data_info` and explicitly returns `("Saved data", 200)` — that string, not the list, is the POST response.'),
        t('`data_info` is a module-level list, so it persists in memory between requests on the same running server. The following `get()` returns whatever is currently in it: the original IITM entry followed by the newly appended Javed entry, in that order — append adds to the end.'),
      ],
      approach: 'Read what each method actually `return`s, then track mutable module-level state across the two requests in order.',
      takeaways: [
        'A `Resource`\'s `get` and `post` can return completely different shapes — read each in isolation.',
        'A plain Python list at module scope is shared, mutable state across every request while the server runs.',
      ],
    },
  },
  {
    id: 'ep7-q273',
    paperId: P,
    number: 273,
    sourceQuestionId: '640653816146',
    type: 'MCQ',
    marks: 4.5,
    title: 'Total data consumed by three users (variant of ep6-q169)',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'demanding',
    stem: [
      t(
        'Consider the following graph that represents the variation in bandwidth of a network for an entire day (24 hours). Three users were connected to the network at three different times of the day. What is the total data consumed in GigaBytes by all the users in 24 hrs?',
      ),
      fig(
        '/figures/bandwidth-24h-a.png',
        'Step graph of bandwidth in Megabits per second against time in hours over 24 hours, with bars marking the connection windows of user 1, user 2 and user 3.',
        'Reproduced from the source paper.',
      ),
    ],
    options: [
      no('6406532733868', '633.6 GB'),
      ok('6406532733869', '54 GB'),
      no('6406532733870', '120 GB'),
      no('6406532733871', '432GB'),
    ],
    solution: {
      verdict: '54 GB — identical figure and calculation to Paper 6, question 169.',
      explanation: [
        out(
          'User 1 (0-4h, 8Mb/s) + User 2 (8-12h@6, 12-14h@8) + User 3 (16-20h@2, 20-24h@10)\n= 32 + 24 + 16 + 8 + 40 = 120 Mb·h\n120 × 3600 = 432,000 Mb ÷ 8 = 54,000 MB ÷ 1000 = 54 GB',
        ),
      ],
      approach: 'Tabulate window, rate, duration; convert once at the end.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 169 — same figure, same options.'],
    },
  },
  {
    id: 'ep7-q274',
    paperId: P,
    number: 274,
    sourceQuestionId: '640653816148',
    type: 'MCQ',
    marks: 4.5,
    title: 'Cascade precedence across #id, .two!important, body!important and p!important',
    topicId: 'html-css',
    subtopicId: 'css-specificity',
    difficulty: 'demanding',
    stem: [
      t('An HTML code and CSS code is given below. Which of the following correctly represents its rendered output?'),
      c('css', `#one{color: blue;}\n.two{color: red !important;}\n#two{color: green}\n#three{color: green;}`, 'CSS Code'),
      c(
        'html',
        `<!DOCTYPE html>\n<html>\n<head>\n    <title>Document</title>\n    <link href="style.css" rel="stylesheet">\n    <style>\n        body{font-weight: bold;}\n        p{color: violet !important ;}\n    </style>\n</head>\n<body>\n    <span id="one">Content 1</span>\n    <p class="two" id="two" >Content 2</p>\n    <span id="three">Content 3</span>\n</body>\n</html>`,
        'HTML Code',
      ),
    ],
    options: [
      no('6406532733876', rnd('Content 1 in blue, Content 2 in red, Content 3 in green — none bold.')),
      no('6406532733877', rnd('Content 1 in blue, Content 2 in red, Content 3 in green — each on its own line, none bold.')),
      no('6406532733878', rnd('Content 1 in blue, Content 2 in red, Content 3 in green — all bold, all on one line.')),
      ok('6406532733879', rnd('Content 1 in blue, Content 2 in red, Content 3 in green — all bold text.')),
    ],
    solution: {
      verdict: 'All three bold; Content 1 blue, Content 2 red, Content 3 green.',
      explanation: [
        t('Resolve `font-weight` first: `body{font-weight:bold}` in the internal stylesheet is the only rule touching it, and nothing overrides it — every element inherits bold text.'),
        t('Now `color`, element by element, with `!important` rules considered before specificity:'),
        tbl(
          ['Element', 'Competing rules', 'Winner'],
          [
            ['`<span id="one">`', '`#one{color:blue}` (external, no !important)', 'blue — only rule that applies'],
            ['`<p class="two" id="two">`', '`.two{color:red !important}` (external) vs `#two{color:green}` (external, no !important) vs `p{color:violet !important}` (internal)', 'The two `!important` rules outrank the plain `#two` rule regardless of id specificity. Between the two `!important` rules, `.two` and `p` tie on being external+internal — the paper\'s key marks red as the result, i.e. the class rule prevails.'],
            ['`<span id="three">`', '`#three{color:green}` (external, no !important)', 'green — only rule that applies'],
          ],
        ),
        t('Both `<span>` and `<p>` are inline elements by default (unchanged here), so all three sit on one line, wrapping only if the viewport is narrow.'),
      ],
      approach:
        'Split the problem into "which declarations are !important?" first — those are decided before ordinary specificity is even consulted — then resolve the remaining ties by specificity/order.',
      takeaways: [
        '`!important` beats any non-important rule no matter how specific the non-important selector is.',
        '`<span>` and `<p>` are both inline-level by default and do not force separate lines on their own.',
      ],
    },
  },
  {
    id: 'ep7-q275',
    paperId: P,
    number: 275,
    sourceQuestionId: '640653816152',
    type: 'MCQ',
    marks: 4.5,
    title: 'pytest -k test on two files with one deselected import call',
    topicId: 'testing',
    subtopicId: 'fixtures',
    difficulty: 'moderate',
    stem: [
      t('Consider the below two python files code snippets app.py and test_app_route.py.'),
      py(
        `from flask import Flask\napp = Flask(__name__)\n\n@app.route("/greet/<string:name>")\ndef home(name):\n   return "Hello, " + name\n\nif __name__ == "__main__":\n   app.run()`,
        'app.py',
      ),
      py(
        `import pytest, requests\n\n@pytest.fixture\ndef get_response():\n   resp = requests.get("http://127.0.0.1:5000/greet/IITM")\n   return resp\n\ndef test_response(get_response):\n   assert get_response.text == "Hello, IITM"`,
        'test_app_route.py',
      ),
      t(
        'Assume that app.py and test_app_route.py are running on two different terminals. And also all required modules are installed. Which of the below statement(s) are True?',
      ),
      li(
        [
          'i) Executing the command **pytest test_app_route.py** on the terminal returns `=========== 1 passed ============`',
          'ii) Executing the command **pytest test_app_route.py** on the terminal returns `============ 1 failed ==============`',
          'iii) Executing the command **pytest test_app_route.py** on the terminal returns `=========== 1 selected, 1 passed =============`',
          'iv) Executing the command **pytest test_app_route.py** on the terminal returns `============ 1 deselected ==============`',
        ],
        false,
      ),
    ],
    options: [
      ok('6406532733892', 'Only statement i is correct'),
      no('6406532733893', 'Only statement ii is correct'),
      no('6406532733894', 'Statements i and iii are correct'),
      no('6406532733895', 'Statements ii and iv are correct'),
    ],
    solution: {
      verdict: 'Only statement i is correct — identical to Paper 6, question 162.',
      explanation: [
        t('With the server running separately, the fixture\'s `requests.get` succeeds and returns `"Hello, IITM"`, matching the assertion — the single test passes. pytest never prints "selected" and there is no filter here to deselect anything, ruling out iii and iv.'),
      ],
      approach: 'Verify the request would actually succeed given the server is live, then check which output lines are real pytest summary phrasing.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 162.'],
    },
  },
  {
    id: 'ep7-q276',
    paperId: P,
    number: 276,
    sourceQuestionId: '640653816130',
    type: 'MSQ',
    marks: 2,
    title: 'What "stateful" means in the client-server model',
    topicId: 'rest-apis',
    subtopicId: 'rest-principles',
    difficulty: 'foundational',
    stem: [t('Which of the following is true about the term “stateful” in the client-server model?')],
    options: [
      ok('6406532733808', "The server responds to the client based on the previous state."),
      ok('6406532733809', "The server uses FTP protocol to respond to the client's request."),
      no('6406532733810', 'Network performance may reduce because of the large amount of data sent out repetitively.'),
      no('6406532733811', 'Server is not required to maintain any state of client or session during transactions between client and server.'),
    ],
    solution: {
      verdict: 'The first two statements.',
      explanation: [
        t('A stateful server retains information about earlier interactions and uses it to answer later requests — the first statement is the definition.'),
        t('FTP is a classically stateful protocol: it maintains a session (working directory, login state) across commands, unlike HTTP\'s default statelessness — so the second statement is a valid example of statefulness, not a contradiction.'),
        t('The third statement — repeated large payloads hurting performance — describes a cost of **statelessness** (context must travel with every request), not statefulness. The fourth statement is the textbook definition of **stateless**, the opposite of what is asked.'),
      ],
      approach: 'Separate "what stateful means" from "what stateless means" — the wrong options here are the stateless definition and its consequence, misattributed.',
      takeaways: ['FTP is a commonly cited stateful protocol, in contrast to stateless HTTP.'],
    },
  },
  {
    id: 'ep7-q277',
    paperId: P,
    number: 277,
    sourceQuestionId: '640653816132',
    type: 'MSQ',
    marks: 2,
    title: 'Reading cardinality off a Salary_Slip / Employee ER diagram',
    topicId: 'databases',
    subtopicId: 'sql-er',
    difficulty: 'moderate',
    stem: [
      t('What can be inferred from the Entity-Relationship Diagram below:'),
      fig(
        '/figures/er-salary-slip-employee.png',
        'ER diagram: Salary_Slip (slip_id PK, Year, Month, Salary_issued, Total_salary) connects via a crow\'s-foot-many, mandatory-on-Employee-side line to Employee (Employee_id PK, Employee_name).',
      ),
    ],
    options: [
      no('6406532733816', 'An employee can exist without having any salary slips'),
      no('6406532733817', 'A salary slip can exist without belonging to any employee'),
      ok('6406532733818', 'An employee needs to have at least one salary slip'),
      ok('6406532733819', 'A salary slip must belong to one and only one employee'),
    ],
    solution: {
      verdict: 'The third and fourth statements.',
      explanation: [
        t('Read each end of the connecting line separately in crow\'s-foot notation.'),
        li([
          'The end at **Salary_Slip** carries a crow\'s foot (many) with no circle — mandatory many: each employee is linked to one **or more** salary slips.',
          'The end at **Employee** carries a double bar — exactly one, mandatory: each salary slip belongs to **exactly one** employee.',
        ]),
        t('So "an employee can exist without any salary slip" is false (the many-end is mandatory, not optional), and "a salary slip can exist without an employee" is false too (the one-end is mandatory). Both correct statements are the mandatory readings of each end.'),
      ],
      approach: 'Translate the symbol at each end of the line into a sentence independently before answering.',
      takeaways: ['A double bar means "exactly one, mandatory"; a crow\'s foot with no circle means "one or more, mandatory".'],
    },
  },
  {
    id: 'ep7-q278',
    paperId: P,
    number: 278,
    sourceQuestionId: '640653816156',
    type: 'MSQ',
    marks: 2,
    title: 'The default branch name of a new git repository',
    topicId: 'tooling-git',
    subtopicId: 'staging-remote',
    difficulty: 'foundational',
    stem: [t('What is the name of the branch that we start with when we create a new git repository?')],
    options: [
      ok('6406532733908', 'main'),
      ok('6406532733909', 'master'),
      no('6406532733910', 'develop'),
      no('6406532733911', 'feature'),
    ],
    solution: {
      verdict: 'main and master are both accepted.',
      explanation: [
        t('Historically git\'s default initial branch was named `master`. Modern git (and GitHub\'s defaults) use `main` instead. Both are correct depending on the git version and configuration in use, which is why the source paper marks both as correct.'),
        t('`develop` and `feature` are conventional branch names used in some branching workflows (e.g. Git Flow), never the automatic default of a fresh repository.'),
      ],
      approach: 'Recognise that the default name changed over time — both answers are defensible.',
      takeaways: ['`git init` creates one branch, named `main` or `master` depending on your git\'s configured default.'],
    },
  },
  {
    id: 'ep7-q279',
    paperId: P,
    number: 279,
    sourceQuestionId: '640653816153',
    type: 'MSQ',
    marks: 3,
    title: 'Which statements about HTML5, XHTML and XML are true',
    topicId: 'web-fundamentals',
    subtopicId: 'markup-standards',
    difficulty: 'foundational',
    stem: [t('Which of the statements are true?')],
    options: [
      no('6406532733896', 'HTML5 is based on SGML'),
      ok('6406532733897', 'XHTML is based on XML which in turn is based on SGML'),
      no('6406532733898', 'HTML5 is not backwards compatible with older versions of HTML'),
      ok('6406532733899', 'XML is both human and machine readable'),
    ],
    solution: {
      verdict: 'The second and fourth statements.',
      explanation: [
        t('XML is a simplified subset of SGML, and XHTML is HTML reformulated in XML — so XHTML descends from SGML through XML, which is true.'),
        t('XML documents are structured tags-and-text, readable by a person and parseable by a machine — also true.'),
        t('HTML5, unlike XHTML, is **not** defined on top of SGML; it has its own parsing rules. And HTML5 was deliberately designed to remain backwards compatible with older HTML, so the third statement is false in both directions from what it claims.'),
      ],
      approach: 'Trace the ancestry: SGML → XML → XHTML is one lineage; HTML5 is a separate branch with its own spec.',
      takeaways: ['HTML5 is not SGML-based. XHTML is, via XML.'],
    },
  },
  {
    id: 'ep7-q280',
    paperId: P,
    number: 280,
    sourceQuestionId: '640653816154',
    type: 'MSQ',
    marks: 3,
    title: 'Which changes halve the number of sequential requests per second',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'demanding',
    stem: [
      t(
        'Consider a client \'C\' and a server \'S\', separated by distance \'D\' are connected by a fictitious medium in which the speed of light is \'v\' m/sec. If \'N\' is the number of consecutive requests that can made in a second by the client \'C\' (i.e A new request can be made only after receiving the response from the previous request.), Which of the following changes would halve the number \'N\'?',
      ),
    ],
    options: [
      ok('6406532733900', "A change of medium where the speed of light is v/2 m/sec."),
      no('6406532733901', "A change of medium where the speed of light is 2v m/sec."),
      no('6406532733902', 'Reduce the distance between C and S from D to D/2.'),
      ok('6406532733903', 'Increase the distance between C and S from D to 2D.'),
    ],
    solution: {
      verdict: 'The first and fourth statements.',
      explanation: [
        t('One request-response cycle takes one round trip, `RTT = 2D/v`, and `N = 1/RTT = v/(2D)`. Halving `N` means doubling `RTT` — which happens if either the speed halves or the distance doubles.'),
        li([
          'Speed `v/2`: `RTT` doubles → `N` halves. ✅',
          'Speed `2v`: `RTT` halves → `N` doubles, the opposite of what is asked.',
          'Distance `D/2`: `RTT` halves → `N` doubles.',
          'Distance `2D`: `RTT` doubles → `N` halves. ✅',
        ]),
      ],
      approach: 'Write `N` as a formula in `D` and `v` first, then check each proposed change against it directly rather than reasoning qualitatively.',
      takeaways: ['`N` is inversely proportional to both distance and to 1/speed — halving speed and doubling distance have the same effect on `N`.'],
    },
  },
  {
    id: 'ep7-q281',
    paperId: P,
    number: 281,
    sourceQuestionId: '640653816127',
    type: 'MSQ',
    marks: 4.5,
    title: 'url_for with variables that are and are not part of the rule',
    topicId: 'flask-routing',
    subtopicId: 'redirect-urlfor',
    difficulty: 'demanding',
    stem: [
      t(
        'Consider the following flask app. Given that `test_request_context()` allows text to be printed on the terminal, which of the following statements is/are correct?',
      ),
      py(
        `from flask import Flask, url_for\napp = Flask(__name__)\n\n@app.route('/library')\ndef home():\n    return 'Select your course!'\n\n@app.route('/student/<username>/<roll>')\ndef dashboard(username):\n    return f'{username}\\'s dashboard'\n\nwith app.test_request_context():\n    #== print statement ==#`,
      ),
    ],
    options: [
      no(
        '6406532733796',
        py(`print(url_for('home', user = "mad1_cs2003"))`),
        t('the output on the terminal will be: `/library/mad1_cs2003`.'),
      ),
      ok(
        '6406532733797',
        py(`print(url_for('home', user = "mad1_cs2003"))`),
        t('the output on the terminal will be: `/library?user=mad1_cs2003`.'),
      ),
      no(
        '6406532733798',
        py(`print(url_for('dashboard', username = "mad1", roll = "cs2003", term = "jan2024"))`),
        t('the output on the terminal will be: `/student/mad1/cs2003/jan2024`.'),
      ),
      ok(
        '6406532733799',
        py(`print(url_for('dashboard', username = "mad1", roll = "cs2003", term = "jan2024"))`),
        t('the output on the terminal will be: `/student/mad1/cs2003?term=jan2024`.'),
      ),
    ],
    solution: {
      verdict: 'The second and fourth statements.',
      explanation: [
        t('`url_for` places into the path only the keyword arguments that match a `<variable>` in the rule; everything else becomes a query string.'),
        li([
          '`/library` has no variable part at all, so `user="mad1_cs2003"` cannot go into the path — it becomes `?user=mad1_cs2003`. So the URL is `/library?user=mad1_cs2003`.',
          '`/student/<username>/<roll>` has two variables. `username` and `roll` fill those slots; `term` is not part of the rule, so it becomes a query parameter: `/student/mad1/cs2003?term=jan2024`.',
        ]),
        t('Note also that `dashboard(username)` only declares one parameter even though the route has two converters — that mismatch would actually raise a `TypeError` at request time, but `url_for` itself only cares about the URL rule\'s variables, not the view\'s signature, so the generated URL is still as computed above.'),
      ],
      approach: 'For each keyword argument to `url_for`, check whether it names a `<variable>` in that endpoint\'s rule. If not, it becomes a query parameter.',
      takeaways: ['`url_for` keyword arguments not present in the URL rule become query-string parameters automatically.'],
    },
  },
  {
    id: 'ep7-q282',
    paperId: P,
    number: 282,
    sourceQuestionId: '640653816145',
    type: 'MSQ',
    marks: 4.5,
    title: 'Which pytest -m command reproduces "1 passed, 3 deselected" (repeat of ep6-q183)',
    topicId: 'testing',
    subtopicId: 'selection',
    difficulty: 'demanding',
    stem: [
      t('Consider the following function to be tested and test functions given in the Python code snippet below.'),
      py(
        `import pytest\n\ndef square(x):\n    sum = 0\n    for counter in range(x):\n        sum += x\n        return sum\n\n@pytest.mark.marker1\ndef testcase_1():\n    assert square(10) == 100\n\n@pytest.mark.marker2\ndef testcase_2():\n    assert square(4) == 4\n\n@pytest.mark.marker3\ndef testcase_3():\n    assert square(5) == 25\n\n@pytest.mark.marker4\ndef testcase_4():\n    assert square(6) == 6`,
        'test_file.py',
      ),
      t('On running this file on the terminal using pytest, the summary of the output is;'),
      out('========= 1 passed, 3 deselected, 4 warnings in 0.04s ========='),
      t('What command will result into the outcome given above?'),
    ],
    options: [
      ok('6406532733864', sh('pytest test_file.py -m marker4')),
      no('6406532733865', sh('pytest test_file.py -m marker1')),
      ok('6406532733866', sh('pytest test_file.py -m marker2')),
      no('6406532733867', sh('pytest test_file.py -m marker3')),
    ],
    solution: {
      verdict: '`-m marker4` and `-m marker2` — identical to Paper 6, question 183.',
      explanation: [
        t('The `return` sits inside the loop, so `square(x)` returns `x` for any `x > 0`. `testcase_2` (`square(4)==4`) and `testcase_4` (`square(6)==6`) both pass; `testcase_1` and `testcase_3` fail.'),
      ],
      approach: 'Trace the actual return value from the indentation bug, then match "1 passed" to a marker whose test passes.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 183, same buggy function.'],
    },
  },
  {
    id: 'ep7-q283',
    paperId: P,
    number: 283,
    sourceQuestionId: '640653816134',
    type: 'MCQ',
    marks: 3,
    comprehensionId: 'ep7-c1',
    title: 'Output for python file.py course 4',
    topicId: 'python-cli',
    subtopicId: 'sys-argv',
    difficulty: 'moderate',
    stem: [t('What will be output on the terminal for the command'), sh('python file.py course 4')],
    options: [
      no('6406532733820', out('course found App Dev I\ncourse found App Dev II\ncourse found App Dev III\ncourse found DevOps')),
      no('6406532733821', out('course found App Dev I\ncourse found App Dev II\ncourse found App Dev III')),
      ok('6406532733822', out('No course found!')),
      no('6406532733823', out('IndexError: list index out of range')),
    ],
    solution: {
      verdict: 'No course found!',
      explanation: [
        t('`sys.argv = [\'file.py\', \'course\', \'4\']`, so `sys.argv[2]` is the string `\'4\'`, and `int(sys.argv[2])` is `4`.'),
        t('`courses[4]` is `"DevOps"`. The condition is `"DevOps" in "App Dev III"` — a substring test on the *string literal* `"App Dev III"`, not on the dictionary\'s values. `"DevOps"` is not a substring of `"App Dev III"`, so the condition is false and the `else` branch prints `No course found!`.'),
      ],
      approach: 'Resolve `courses[int(sys.argv[2])]` to a concrete string first, then check literal substring membership against the fixed string.',
      takeaways: ['`in` against a string literal is a substring test — it does not search a dictionary or list of values.'],
    },
  },
  {
    id: 'ep7-q284',
    paperId: P,
    number: 284,
    sourceQuestionId: '640653816135',
    type: 'MCQ',
    marks: 3,
    comprehensionId: 'ep7-c1',
    title: 'Output for python file.py course 1',
    topicId: 'python-cli',
    subtopicId: 'sys-argv',
    difficulty: 'moderate',
    stem: [t('What will be output on the terminal for the command'), sh('python file.py course 1')],
    options: [
      no('6406532733824', out('No course found!')),
      ok('6406532733825', out('course found App Dev I')),
      no('6406532733826', out('course found App Dev I\ncourse found App Dev II\ncourse found App Dev III\ncourse found DevOps')),
      no('6406532733827', out('IndexError: list index out of range')),
    ],
    solution: {
      verdict: 'course found App Dev I',
      explanation: [
        t('`sys.argv[2]` is `\'1\'`, so `courses[1]` is `"App Dev I"`. The condition is `"App Dev I" in "App Dev III"` — and `"App Dev I"` **is** a substring of `"App Dev III"` (the shorter string sits inside the longer one, ignoring the trailing "II").'),
        t('So the `if` branch runs. `i` starts at 1 and the loop runs `while i <= int(sys.argv[2])`, i.e. while `i <= 1` — so it executes exactly once, printing `course found App Dev I`, then `i` becomes 2 and the loop stops.'),
      ],
      approach: 'Check the substring condition carefully — "App Dev I" is contained in "App Dev III" as plain text, which is easy to misjudge at a glance.',
      takeaways: ['The loop bound in this script is `sys.argv[2]` itself, so a small value produces very few iterations even when the condition passes.'],
    },
  },
];
