import type { Comprehension, Question } from '../types';
import { c, li, no, ok, out, py, rnd, sh, t, tbl, fig } from '../dsl';

const P = 'ep8';

export const ep8Comprehensions: Comprehension[] = [
  {
    id: 'ep8-c1',
    paperId: P,
    title: 'Reading an HTTP response head from httpbin.org',
    range: '77 to 78',
    stem: [
      t('Given below is a part of the HTTP response upon running the command:'),
      sh('curl --head https://www.httpbin.org/'),
      out(
        'HTTP/2 200\ndate: Fri, 02 Dec 2022 16:38:16 GMT\ncontent-type: text/html; charset=utf-8\ncontent-length: 9593\nserver: gunicorn/19.9.0\naccess-control-allow-origin: *\naccess-control-allow-credentials: true',
        'HTTP response',
      ),
    ],
  },
  {
    id: 'ep8-c2',
    paperId: P,
    title: 'Sequential requests to three servers at different distances',
    range: '79 to 80',
    stem: [
      t(
        'A machine client M makes multiple requests to three different servers A, B and C in the order A then B followed by C. However, it can make a request to server B only after receiving the response from server A and same with server C i.e. the client can make a request to server C only after receiving response from server B. If the servers A, B and C are located at 900 kms, 1200 kms and 1500 kms respectively, answer the given subquestions. [Consider speed of light in air to be 3 x 10⁸ m/s]',
      ),
    ],
  },
];

export const ep8Questions: Question[] = [
  {
    id: 'ep8-q49',
    paperId: P,
    number: 49,
    sourceQuestionId: '640653697628',
    type: 'MCQ',
    marks: 3,
    title: 'Breaking a URL into protocol, domain, sub-domain, path and parameters',
    topicId: 'web-fundamentals',
    subtopicId: 'url-anatomy',
    difficulty: 'foundational',
    stem: [
      t('Consider the given URL below.'),
      out('https://seek.study.iitm.ac.in/courses/ns_23t3_cs2003?type=lesson&tab=courses'),
      t('Select the appropriate option that correctly identifies different components of a given URL.'),
    ],
    options: [
      no(
        '6406532329894',
        out(
          'Protocol: https\nDomain: seek\nSub-Domain: study.iitm.ac.in\nPath: /courses/ns_23t3_cs2003\nParameters: ?type=lesson&tab=courses',
        ),
      ),
      no(
        '6406532329895',
        out(
          'Protocol:  https\nDomain:  seek\nSub-Domain:  study.iitm.ac.in/courses\nPath:  /ns_23t3\nParameters: cs2003?type=lesson&tab=courses',
        ),
      ),
      no(
        '6406532329896',
        out(
          'Protocol:  https\nDomain:  study.iitm.ac.in/courses\nSub-Domain:  seek\nPath: /ns_23t3\nParameters: cs2003?type=lesson&tab=courses',
        ),
      ),
      ok(
        '6406532329897',
        out(
          'Protocol:  https\nDomain:  study.iitm.ac.in\nSub-Domain:  seek\nPath: /courses/ns_23t3_cs2003\nParameters: ?type=lesson&tab=courses',
        ),
      ),
    ],
    solution: {
      verdict: 'Protocol https; domain study.iitm.ac.in; sub-domain seek; path /courses/ns_23t3_cs2003; parameters ?type=lesson&tab=courses.',
      explanation: [
        t('Split the hostname `seek.study.iitm.ac.in` left to right: `seek` is the label sitting in front of the registered domain, so it is the sub-domain, and `study.iitm.ac.in` is the domain itself.'),
        t('Everything after the host up to the `?` is the path; everything from the `?` onward is the query parameters. Options 1-3 either swap domain and sub-domain or cut the path in the wrong place.'),
      ],
      approach: 'Split the hostname first (sub-domain vs domain), then split the remainder at the `?`.',
      takeaways: ['The sub-domain is the leftmost label of the hostname, not the rightmost.'],
    },
  },
  {
    id: 'ep8-q50',
    paperId: P,
    number: 50,
    sourceQuestionId: '640653697631',
    type: 'MCQ',
    marks: 3,
    title: 'Rendered box layout: border colour vs default black border',
    topicId: 'html-css',
    subtopicId: 'display-box',
    difficulty: 'moderate',
    stem: [
      t('How will the browser render the following HTML document?'),
      c(
        'html',
        `<!DOCTYPE html>\n<html>\n<head>\n    <title>Document</title>\n    <style>\n        div{\n            border: 1px solid black;\n            color:pink;\n        }\n        span{\n            border: 1px solid pink;\n            display: block;\n        }\n        div,span{\n            width:8%;\n            margin: 2px;\n        }\n    </style>\n</head>\n    <body>\n        <div>Div 1</div>\n        <div>Div 2</div>\n        <span>Span 1</span>\n        <span>Span 2</span>\n    </body>\n</html>`,
      ),
    ],
    options: [
      ok(
        '6406532329910',
        rnd(
          'Four narrow, stacked boxes each 8% wide: Div 1 and Div 2 with a black border and pink text; Span 1 and Span 2 with a pink border and default black text.',
        ),
      ),
      no('6406532329911', rnd('Four boxes, all pink text, all pink borders.')),
      no('6406532329912', rnd('Four boxes on a single line, side by side.')),
      no('6406532329913', rnd('Two stacked wide boxes (Div) followed by two narrow boxes (Span) on one line.')),
    ],
    solution: {
      verdict: 'Four separate, narrow, stacked boxes: divs black-bordered pink text, spans pink-bordered default text.',
      explanation: [
        t('`div,span{width:8%; margin:2px;}` applies to both tags equally, so every box is the same narrow width with the same margin — that alone rules out the option showing wide divs.'),
        t('`div` gets `border:1px solid black; color:pink;` — a black border, pink text. `span` gets `border:1px solid pink;` — a pink border, but no `color` rule of its own, so its text stays the browser default (black).'),
        t('Crucially, `span{display:block}` turns each `<span>` into a block-level box, so all four elements start on new lines and stack vertically — none of them share a line.'),
      ],
      approach: 'Resolve colour and border per selector first; then check `display` for every element before assuming inline elements sit side by side.',
      takeaways: ['`display:block` on a `<span>` removes its default inline behaviour entirely — it then behaves exactly like a `<div>` for layout purposes.'],
    },
  },
  {
    id: 'ep8-q51',
    paperId: P,
    number: 51,
    sourceQuestionId: '640653697636',
    type: 'MCQ',
    marks: 3,
    title: 'Statement coverage vs branch coverage vs condition coverage implications',
    topicId: 'testing',
    subtopicId: 'coverage',
    difficulty: 'moderate',
    stem: [
      t('Consider the statements given below and choose the correct option.'),
      t('**Statement 1:** 100% statement coverage automatically implies 100% branch coverage.'),
      t('**Statement 2:** 100% statement coverage automatically implies 100% condition coverage.'),
    ],
    options: [
      no('6406532329938', 'Both statement 1 and 2 are correct.'),
      ok('6406532329939', 'Both statement 1 and 2 are incorrect.'),
      no('6406532329940', 'Statement 1 is correct but, statement 2 is incorrect.'),
      no('6406532329941', 'Statement 2 is correct but, statement 1 is incorrect.'),
    ],
    solution: {
      verdict: 'Both statements are incorrect.',
      explanation: [
        t('Neither implication holds, and a single-branch `if` with no `else` is the standard counterexample: `if (x > 0) { z = x; }` reaches 100% statement coverage with just one call (`x=1`), since the only statement — the assignment — executes.'),
        t('But that one call never takes the *false* branch of the `if`, so branch coverage is not 100%. And it never exercises the condition being false, so condition coverage is not 100% either. Statement coverage is the weakest of the criteria; it implies neither of the other two.'),
      ],
      approach: 'Construct a minimal counterexample — a single `if` with no `else` defeats both statements at once.',
      takeaways: ['Statement coverage is the weakest criterion and implies neither branch nor condition coverage.'],
    },
  },
  {
    id: 'ep8-q52',
    paperId: P,
    number: 52,
    sourceQuestionId: '640653697642',
    type: 'MCQ',
    marks: 3,
    title: 'How to request a netcat server listening on a custom port',
    topicId: 'web-fundamentals',
    subtopicId: 'http-messages',
    difficulty: 'foundational',
    stem: [
      t('Consider a simple web server using command prompt.'),
      sh(
        `#!/bin/bash\nwhile true; do\necho -e "Current date and time is \\n\\t $(date)" | nc -l localhost 4100;\ndone`,
        'Filename - Hello.sh',
      ),
      t('If this program creates a server in a terminal, the correct way to make a request to this server is ________.'),
    ],
    options: [
      no('6406532329962', 'Type `curl http://localhost:5000` in the same terminal where the server is running.'),
      no('6406532329963', 'Type `curl http://localhost:4100` in the same terminal where the server is running.'),
      no('6406532329964', 'Open a new terminal and type `curl http://localhost:5000`'),
      ok('6406532329965', 'Open a new terminal and type `curl http://localhost:4100`'),
    ],
    solution: {
      verdict: 'Open a new terminal and type `curl http://localhost:4100`.',
      explanation: [
        t('Two things must both be right. The port: `nc -l localhost 4100` listens on **4100**, not the Flask-conventional 5000 — that eliminates two options immediately.'),
        t('The terminal: the server script occupies its terminal running the `while true` loop and blocks on `nc -l`, waiting for a connection. You cannot type another command in that same terminal while it is running — the request must come from a **separate** terminal.'),
      ],
      approach: 'Read the port straight out of the script rather than assuming 5000, and remember a blocking server ties up its terminal.',
      takeaways: ['A terminal running a blocking server cannot also issue commands — use a second terminal for the client request.'],
    },
  },
  {
    id: 'ep8-q53',
    paperId: P,
    number: 53,
    sourceQuestionId: '640653697645',
    type: 'MCQ',
    marks: 3,
    title: 'Rendered output for a profile route with a denied-access branch (repeat of ep6-q165)',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask, render_template, request\n\napp = Flask(__name__)\n\nemp = {'admin':'manoj', 'user':'sumit'}\n\n@app.route('/profile/<user>')\ndef profile(user):\n    access = request.args.get('access')\n    if emp[access] != user:\n        return render_template("profile.html", user = user,\n                               access = access, error = True)\n    return render_template("profile.html", user = user,\n                           access = access, error = False)\n\napp.run()`,
        'Python file: app.py',
      ),
      c(
        'jinja',
        `<body>\n    <div>\n        {% if error %}\n            <h3>Hi {{user}}, {{access}} access denied</h3>\n        {% else %}\n            <h3>Hi {{user}}, you are logged in as {{access}}.</h3>\n        {% endif %}\n    </div>\n</body>`,
        'Template file: profile.html',
      ),
      t('If the application is running locally on `http://127.0.0.1:5000`, then what will be rendered by the browser for URL, `http://127.0.0.1:5000/profile/sumit?access=admin` ?'),
    ],
    options: [
      no('6406532329974', 'Hi sumit, you are logged in as admin.'),
      no('6406532329975', 'Hi sumit, you are logged in as user.'),
      ok('6406532329976', 'Hi sumit, admin access denied.'),
      no('6406532329977', 'Hi sumit, user access denied.'),
    ],
    solution: {
      verdict: 'Hi sumit, admin access denied.',
      explanation: [
        t('`user` = `sumit` (path), `access` = `admin` (query). `emp[\'admin\']` is `manoj`, and `manoj != sumit` is true, so `error=True`.'),
        t('The if-branch renders, substituting the resolved values: **Hi sumit, admin access denied.**'),
      ],
      approach: 'Resolve both template variables in the view before choosing the branch.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 165.'],
    },
  },
  {
    id: 'ep8-q54',
    paperId: P,
    number: 54,
    sourceQuestionId: '640653697646',
    type: 'MCQ',
    marks: 3,
    title: 'pytest -m for a test suite with one true assertion out of three',
    topicId: 'testing',
    subtopicId: 'selection',
    difficulty: 'moderate',
    stem: [
      t('Consider the following function to be tested and test functions given in the Python code snippet below.'),
      py(
        `import pytest\n\ndef square(x):\n    sum = 0\n    for counter in range(x):\n      sum += x\n      return sum\n\n@pytest.mark.marker1\ndef testcase_1():\n    assert square(13) == 144\n\n@pytest.mark.marker2\ndef testcase_2():\n    assert square(6) == 6\n\n@pytest.mark.marker3\ndef testcase_3():\n    assert square(3) == 9`,
        'test_file.py',
      ),
      t('On running this file on the terminal using pytest, the summary of the output is;'),
      out('============ 1 passed, 2 deselected, 3 warnings in 0.02s ==============='),
      t('What command will result into the outcome given above?'),
    ],
    options: [
      no('6406532329978', sh('pytest test_file.py -k marker1')),
      no('6406532329979', sh('pytest test_file.py -m marker1')),
      no('6406532329980', sh('pytest test_file.py -m marker3')),
      ok('6406532329981', sh('pytest test_file.py -m marker2')),
    ],
    solution: {
      verdict: '`pytest test_file.py -m marker2`.',
      explanation: [
        t('Same buggy `square` as elsewhere: `return` inside the loop means `square(x)` returns `x` itself for `x>0`.'),
        tbl(
          ['Test', 'Assertion', '`square(x)` actually returns', 'Result'],
          [
            ['testcase_1', '`square(13) == 144`', '13', 'fails'],
            ['testcase_2', '`square(6) == 6`', '6', '**passes**'],
            ['testcase_3', '`square(3) == 9`', '3', 'fails'],
          ],
        ),
        t('Only `testcase_2` (marker2) passes, matching "1 passed". And `-k marker1` would select by substring in the *name*, which does not match a marker — `-m` is the correct flag for the 3 unregistered-marker warnings shown.'),
      ],
      approach: 'Determine the actual return value first, then find which single test passes, then match its marker.',
      takeaways: ['Only `-m` selects by `@pytest.mark`; `-k` matches by substring of the test/class name, which is unrelated here.'],
    },
  },
  {
    id: 'ep8-q55',
    paperId: P,
    number: 55,
    sourceQuestionId: '640653697647',
    type: 'MCQ',
    marks: 3,
    title: 'Hexadecimal equivalent of IPv4 171.216.21.100',
    topicId: 'web-fundamentals',
    subtopicId: 'addressing',
    difficulty: 'foundational',
    stem: [t('The hexadecimal equivalent of the IPv4 address `171.216.21.100` would be ________.')],
    options: [
      no('6406532329982', 'ABD8 6415'),
      no('6406532329983', 'D8AB 6415'),
      ok('6406532329984', 'ABD8 1564'),
      no('6406532329985', 'D8AB 1564'),
    ],
    solution: {
      verdict: 'ABD8 1564.',
      explanation: [
        tbl(
          ['Octet', 'Decimal', 'Hex'],
          [
            ['1st', '171', '`AB`'],
            ['2nd', '216', '`D8`'],
            ['3rd', '21', '`15`'],
            ['4th', '100', '`64`'],
          ],
        ),
        t('Reading in order: `AB D8 15 64`, grouped as **ABD8 1564**.'),
      ],
      approach: 'Convert each octet independently, in order.',
      takeaways: ['Same method as any IPv4-to-hex question: convert each octet on its own.'],
    },
  },
  {
    id: 'ep8-q56',
    paperId: P,
    number: 56,
    sourceQuestionId: '640653697648',
    type: 'MCQ',
    marks: 3,
    title: 'Relationship between Creator and Song models',
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'foundational',
    stem: [
      t('Consider the following models Creator and Song corresponding to tables creator and song in SQLite database.'),
      py(
        `class Creator(db.Model):\n    id = db.Column(db.Integer(), primary_key = True)\n    c_name = db.Column(db.String(), unique = True)\n\nclass Song(db.Model):\n    id = db.Column(db.Integer(), primary_key = True)\n    s_title = db.Column(db.String(), unique = True)\n    singer = db.Column(db.Integer(), db.ForeignKey("creator.id"))`,
      ),
      t('Based on the model schemas, what relationship do the table `creator` and `song` share?'),
    ],
    options: [
      no('6406532329986', 'Many-to-Many'),
      ok('6406532329987', 'One-to-Many'),
      no('6406532329988', 'One-to-One'),
      no('6406532329989', 'The tables are not at all related'),
    ],
    solution: {
      verdict: 'One-to-Many.',
      explanation: [
        t('`Song.singer` is a plain (non-unique) foreign key to `creator.id`. Any number of songs may point at the same creator, so one creator relates to many songs.'),
      ],
      approach: 'Find the ForeignKey; check for `unique=True` — its absence means one-to-many.',
      takeaways: ['A ForeignKey with no `unique=True` gives one-to-many.'],
    },
  },
  {
    id: 'ep8-q57',
    paperId: P,
    number: 57,
    sourceQuestionId: '640653697654',
    type: 'MCQ',
    marks: 3,
    title: 'The curl option that sets the request method',
    topicId: 'rest-apis',
    subtopicId: 'status-curl',
    difficulty: 'foundational',
    stem: [t('Which curl option is used to set the request method in an HTTP request?')],
    options: [no('6406532330010', '-H'), ok('6406532330011', '-X'), no('6406532330012', '-d'), no('6406532330013', '-r')],
    solution: {
      verdict: '-X.',
      explanation: [
        t('`-X METHOD` sets the HTTP verb (`GET`, `POST`, `PUT`, `DELETE`, ...). `-H` adds a request header, `-d` sends request body data (and implies POST if `-X` is not given), and `-r` is not a curl method flag.'),
      ],
      approach: 'Memorise: `-X` method, `-H` header, `-d` data.',
      takeaways: ['`-X` sets the method; `-d` alone defaults to POST.'],
    },
  },
  {
    id: 'ep8-q58',
    paperId: P,
    number: 58,
    sourceQuestionId: '640653697624',
    type: 'MCQ',
    marks: 2,
    title: 'Cascade precedence: ID beats class, inline beats internal style?',
    topicId: 'html-css',
    subtopicId: 'css-specificity',
    difficulty: 'foundational',
    stem: [
      t('Read the statements given below carefully and select the correct option.'),
      t('**Statement 1:** If an element is styled externally using both the class and the ID, then for the same attribute, it will acquire styling from the ID.'),
      t(
        '**Statement 2:** If an element is styled internally using ID and class selector as well as using inline styling for the same style attribute, then it will always acquire inline styling.',
      ),
    ],
    options: [
      ok('6406532329898', 'Both statements 1 and 2 are correct'),
      no('6406532329899', 'Both statements 1 and 2 are incorrect'),
      no('6406532329900', 'Statement 1 is correct but statement 2 is incorrect'),
      no('6406532329901', 'Statement 2 is correct but statement 1 is incorrect'),
    ],
    solution: {
      verdict: 'Both statements are correct.',
      explanation: [
        t('Statement 1: id beats class in specificity, so an element styled by both acquires the id\'s value for the same property — correct, and this holds whichever declares last.'),
        t(
          'Statement 2: inline `style=""` has the highest specificity of all (short of `!important`), so it beats an id or class selector on the same property — correct, as long as no `!important` is involved (which the statement does not mention, so the general rule stands).',
        ),
      ],
      approach: 'Rank the four levels: inline > id > class > element, and check each statement against that ranking.',
      takeaways: ['Inline styling outranks id and class, absent an `!important` declaration.'],
    },
  },
  {
    id: 'ep8-q59',
    paperId: P,
    number: 59,
    sourceQuestionId: '640653697629',
    type: 'MCQ',
    marks: 2,
    title: 'Which python command produces "two.py one.py\\ntwo.py one.py"',
    topicId: 'python-cli',
    subtopicId: 'sys-argv',
    difficulty: 'moderate',
    stem: [
      t('Consider two python files, one.py and two.py with following code snippets.'),
      py(`import sys\nimport two\nprint(f'{sys.argv[1]} {sys.argv[3]}')`, 'File1: one.py'),
      py(`import sys\nprint(f'{sys.argv[2]} {sys.argv[0]}')`, 'File2: two.py'),
      t('What is the output of the following command “python one.py two.py two.py one.py ”?'),
    ],
    options: [
      no('6406532329914', out('one.py two.py\none.py two.py')),
      no('6406532329915', out('two.py one.py\none.py two.py')),
      ok('6406532329916', out('two.py one.py\ntwo.py one.py')),
      no('6406532329917', out('one.py two.py\ntwo.py one.py')),
    ],
    solution: {
      verdict: 'two.py one.py\ntwo.py one.py',
      explanation: [
        t('`python one.py two.py two.py one.py` runs `one.py` with `sys.argv = [\'one.py\', \'two.py\', \'two.py\', \'one.py\']` (index 0 is the running script).'),
        t('`one.py` prints `f\'{sys.argv[1]} {sys.argv[3]}\'` = `two.py one.py` — first line.'),
        t('`one.py` then `import two`. Importing does **not** change `sys.argv` — it stays exactly as the interpreter set it when `one.py` was launched, so `two.py`\'s code sees the same list.'),
        t('`two.py` prints `f\'{sys.argv[2]} {sys.argv[0]}\'` = `two.py one.py` (index 2 is `\'two.py\'`, index 0 is `\'one.py\'`, the script that was actually launched) — second line.'),
        t('Both lines come out `two.py one.py`.'),
      ],
      approach: 'Write `sys.argv` once, as it is at process start, and reuse it for every module\'s print — importing a module never resets it.',
      takeaways: ['`sys.argv` is a single list shared by the whole process, unaffected by which module reads it.'],
    },
  },
  {
    id: 'ep8-q60',
    paperId: P,
    number: 60,
    sourceQuestionId: '640653697640',
    type: 'MCQ',
    marks: 2,
    title: 'Which of the following is not a web component',
    topicId: 'javascript-web',
    subtopicId: 'web-platform',
    difficulty: 'foundational',
    stem: [t('Which of the following is not a web component?')],
    options: [
      no('6406532329954', 'Custom Elements'),
      no('6406532329955', 'Shadow DOM'),
      no('6406532329956', 'HTML Templates'),
      ok('6406532329957', 'Web Assembly'),
    ],
    solution: {
      verdict: 'Web Assembly.',
      explanation: [
        t('Custom Elements, Shadow DOM and HTML Templates are the three specifications that together make up the web components standard.'),
        t('WebAssembly is a separate, unrelated technology: a portable bytecode format for running compiled code (typically C/C++) in the browser at near-native speed. It has nothing to do with defining custom HTML elements.'),
      ],
      approach: 'Recall the three-part web-components spec by name; anything outside that trio (and not encapsulation-related) is not one.',
      takeaways: ['Web components = Custom Elements + Shadow DOM + HTML Templates.'],
    },
  },
  {
    id: 'ep8-q61',
    paperId: P,
    number: 61,
    sourceQuestionId: '640653697641',
    type: 'MCQ',
    marks: 2,
    title: 'git del vs git rm --cached',
    topicId: 'tooling-git',
    subtopicId: 'staging-remote',
    difficulty: 'foundational',
    stem: [
      t('Consider the following statements and select the correct option.'),
      t('**Statement 1:** The command, `git del <filename>` deletes the file from the staging area as well as from the working tree.'),
      t('**Statement 2:** The command, `git rm --cached <filename>` deletes the file from the staging area but keeps it in the working tree.'),
    ],
    options: [
      no('6406532329958', 'Statement 1 is correct, but statement 2 is incorrect.'),
      ok('6406532329959', 'Statement 1 is incorrect, but statement 2 is correct.'),
      no('6406532329960', 'Both statements 1 and 2 are correct.'),
      no('6406532329961', 'Both statements 1 and 2 are incorrect.'),
    ],
    solution: {
      verdict: 'Statement 1 is incorrect, but statement 2 is correct.',
      explanation: [
        t('`git del` does not exist as a git command — Statement 1 describes an invented command, so it is false regardless of what it claims that command does.'),
        t('`git rm --cached <file>` is real, and it does exactly what Statement 2 says: it un-stages/un-tracks the file while leaving the file on disk untouched.'),
      ],
      approach: 'Check whether the named command exists at all before evaluating what it is claimed to do.',
      takeaways: ['`git rm --cached` un-tracks without deleting; plain `git rm` deletes from both index and working tree; `git del` is not a git command.'],
    },
  },
  {
    id: 'ep8-q62',
    paperId: P,
    number: 62,
    sourceQuestionId: '640653697655',
    type: 'MCQ',
    marks: 2,
    title: 'What Emscripten is',
    topicId: 'javascript-web',
    subtopicId: 'web-platform',
    difficulty: 'foundational',
    stem: [t('What is Emscripten in the context of WebAssembly?')],
    options: [
      no('6406532330014', 'A WebAssembly specification'),
      no('6406532330015', 'A JavaScript framework'),
      ok('6406532330016', 'A toolchain for compiling C/C++ code to WebAssembly'),
      no('6406532330017', 'An HTML and CSS editor'),
    ],
    solution: {
      verdict: 'A toolchain for compiling C/C++ code to WebAssembly.',
      explanation: [
        t('Emscripten is a compiler toolchain (built on LLVM/Clang) that takes C/C++ source and produces WebAssembly, letting existing native codebases run in a browser.'),
      ],
      approach: 'Recall Emscripten by name association: "compiles C/C++ to Wasm".',
      takeaways: ['Emscripten compiles; it is not itself a spec, a JS framework, or an editor.'],
    },
  },
  {
    id: 'ep8-q63',
    paperId: P,
    number: 63,
    sourceQuestionId: '640653697656',
    type: 'MCQ',
    marks: 2,
    title: 'What SQLAlchemy is used for',
    topicId: 'databases',
    subtopicId: 'models-columns',
    difficulty: 'foundational',
    stem: [t('The ORM(Object-Relational Mapping) sqlalchemy is used for?')],
    options: [
      no('6406532330018', 'Running SQL queries directly on the database'),
      no('6406532330019', 'Defining the structure of HTML templates'),
      ok('6406532330020', 'Mapping Python objects to database tables and records'),
      no('6406532330021', 'Creating Web Routes in a Flask app'),
    ],
    solution: {
      verdict: 'Mapping Python objects to database tables and records.',
      explanation: [
        t('An ORM\'s job is exactly this mapping: Python classes correspond to tables, instances to rows, attributes to columns — so you manipulate data as Python objects instead of writing SQL directly.'),
      ],
      approach: 'Recall the definition of "ORM" verbatim.',
      takeaways: ['ORM = Object-Relational Mapping: classes↔tables, instances↔rows.'],
    },
  },
  {
    id: 'ep8-q64',
    paperId: P,
    number: 64,
    sourceQuestionId: '640653697631',
    type: 'MCQ',
    marks: 4.5,
    title: 'Match python arg.py commands with their rendered jinja output',
    topicId: 'jinja-templates',
    subtopicId: 'jinja-basics',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `from jinja2 import Template\nimport sys\ninput_list = sys.argv\nnum1, num2, input_list[3] = int(input_list[1]), int(input_list[2]),\nint(input_list[3])\n\nif input_list[3]== 1:\n    num3= (num1**num2)\nelif input_list[3]== 2:\n    num3= (num1-num2)\nelif input_list[3]== 3:\n    num3= (num1+num2)\nelse:\n    num3= (num1%num2)\ntemplate = """\n            <!DOCTYPE html>\n            <html>\n              <div>\n                Number 1: {{num1}},\n                Number 2: {{num2}},\n                Output : {{num3}}\n              </div>\n            </html>\n            """\nt = Template(template)\nprint(t.render(num1=num1, num2=num2, num3=num3))`,
        'arg.py',
      ),
      t('Map the commands in column A with the correct rendered output in the browser in column B.'),
      tbl(
        ['Column A', 'Column B'],
        [
          ['a) python arg.py 2 2 1', '1) Number 1: 4, Number 2: 2, Output: 0'],
          ['b) python arg.py 2 2 3', '2) Number 1: 2, Number 2: 2, Output: 4'],
          ['c) python arg.py 4 2 2', '3) Number 1: 2, Number 2: 2, Output: 4'],
          ['d) python arg.py 4 2 4', '4) Number 1: 4, Number 2: 2, Output: 2'],
        ],
      ),
    ],
    options: [
      no('6406532329922', 'a - 3, b - 2, c - 1, d - 4'),
      no('6406532329923', 'a - 2, b - 1, c - 4, d - 3'),
      no('6406532329924', 'a - 3, b - 1, c - 2, d - 4'),
      ok('6406532329925', 'a - 2, b - 3, c - 4, d - 1'),
    ],
    solution: {
      verdict: 'a-2, b-3, c-4, d-1.',
      explanation: [
        t('`num1, num2 = argv[1], argv[2]` (converted to int) and `input_list[3]` is also converted in place. Evaluate each command:'),
        tbl(
          ['Command', 'num1, num2, argv[3]', 'Branch', 'num3', 'Output'],
          [
            ['a) `2 2 1`', '2, 2, 1', '`== 1` → `num1**num2`', '`2**2 = 4`', 'Number 1: 2, Number 2: 2, Output: 4 (2)'],
            ['b) `2 2 3`', '2, 2, 3', '`== 3` → `num1+num2`', '`2+2 = 4`', 'Number 1: 2, Number 2: 2, Output: 4 (3)'],
            ['c) `4 2 2`', '4, 2, 2', '`== 2` → `num1-num2`', '`4-2 = 2`', 'Number 1: 4, Number 2: 2, Output: 2 (4)'],
            ['d) `4 2 4`', '4, 2, 4', '`else` → `num1%num2`', '`4 % 2 = 0`', 'Number 1: 4, Number 2: 2, Output: 0 (1)'],
          ],
        ),
        t('Options 2 and 3 in column B are the same numbers, just to test that you correctly match both `a` and `b` to `4`, not just get the right numeric value for one of them.'),
      ],
      approach: 'Build a full table of num1/num2/branch/num3 before matching to column B — several rows produce the same numeric output.',
      takeaways: ['`**`, `-`, `+`, `%` selected by the fourth argument — evaluate the exact operator for each branch.'],
    },
  },
  {
    id: 'ep8-q65',
    paperId: P,
    number: 65,
    sourceQuestionId: '640653697632',
    type: 'MCQ',
    marks: 4.5,
    title: 'Writing a Jinja groupby template to reproduce a given grouped table',
    topicId: 'jinja-templates',
    subtopicId: 'macros-filters',
    difficulty: 'demanding',
    stem: [
      t('Given a Python code snippet, code.py is run on the terminal with an appropriate temp.html document.'),
      py(
        `from jinja2 import Template\nProducts = [\n  {'product_id':'101', 'prod_name':'Legion','producer':'Lenovo'},\n  {'product_id':'102', 'prod_name':'S21pro', 'producer':'Samsung'},\n  {'product_id':'103', 'prod_name':'TabA7','producer':'Samsung'},\n  {'product_id':'104', 'prod_name':'Ideapad', 'producer':'Lenovo'},\n  ]\nFile = open ('temp.html','r')\ntemp = File.read()\nFile.close()\nmade_temp = Template(temp)\nprint(made_temp.render(Products=Products))`,
        'code.py',
      ),
      t('What should be the content of temp.html file if the browser renders the output of the above code, as shown below;'),
      out('Lenovo\nProduct ID | Name\n101 | Legion\n104 | Ideapad\n\nSamsung\nProduct ID | Name\n102 | S21pro\n103 | TabA7'),
    ],
    options: [
      no(
        '6406532329926',
        c(
          'jinja',
          `{% for product in Products| groupby('producer') %}\n  <p> {{product.grouper}} </p>\n  <table border="1">\n  <tr>\n      <th>Product ID</th>\n      <th> Name </th>\n  </tr>\n  <tr>\n  <td> {{ product.product_id}}</td>\n  <td>{{product.prod_name}}</td>\n  </tr>\n  </table>\n{% endfor %}`,
        ),
      ),
      ok(
        '6406532329927',
        c(
          'jinja',
          `{% for product in Products| groupby('producer') %}\n  <p> {{product.grouper}} </p>\n  <table border="1">\n  <tr>\n      <th>Product ID</th>\n      <th> Name </th>\n  </tr>\n  {% for item in product.list %}\n  <tr>\n  <td> {{ item.product_id}}</td>\n  <td>{{item.prod_name}}</td>\n  </tr>\n  {% endfor %}\n  </table>\n  {% endfor %}`,
        ),
      ),
      no(
        '6406532329928',
        c(
          'jinja',
          `{% for product in Products| groupby('prod_name') %}\n  <p> {{product.grouper}} </p>\n  <table border="1">\n  <tr>\n      <th>Product ID</th>\n      <th> Name </th>\n  </tr>\n  {% for item in product.list %}\n  <tr>\n  <td> {{ item.product_id}}</td>\n  <td>{{item.prod_name}}</td>\n  </tr>\n  {% endfor %}\n  </table>\n{% endfor %}`,
        ),
      ),
      no(
        '6406532329929',
        c(
          'jinja',
          `{% for product in Products| groupby('prod_name') %}\n  <p> {{product.grouper}} </p>\n  <table border="1">\n  <tr>\n      <th>Product ID</th>\n      <th>Name</th>\n  </tr>\n  <tr>\n    <td>{{item.product_id}}</td>\n    <td>{{item.prod_name}}</td>\n  </tr>\n  </table>\n{% endfor %}`,
        ),
      ),
    ],
    solution: {
      verdict: 'Group by `producer`, with a nested `{% for item in product.list %}` for the rows.',
      explanation: [
        t('The desired output groups by manufacturer ("Lenovo", "Samsung"), so the filter must be `groupby(\'producer\')`, not `groupby(\'prod_name\')` — that eliminates two options immediately.'),
        t('Each group needs to print **every** product it contains, not just one. `groupby` yields a group object with `.grouper` (the key) and `.list` (the members) — you must loop over `.list` with an inner `{% for item in product.list %}` to reach each product\'s `product_id` and `prod_name`. The option lacking this inner loop only ever accesses the outer `product` object directly, which has no `product_id` attribute at all and would render nothing useful.'),
      ],
      approach: 'Check the grouping key against the desired headings first; then check for the inner loop needed to print every member of each group.',
      takeaways: ['`groupby` groups don\'t auto-print their members — you must loop `.list` explicitly.'],
    },
  },
  {
    id: 'ep8-q66',
    paperId: P,
    number: 66,
    sourceQuestionId: '640653697649',
    type: 'MCQ',
    marks: 4.5,
    title: 'pytest output when a decorator wraps a function inside a loop',
    topicId: 'testing',
    subtopicId: 'pytest-collection',
    difficulty: 'demanding',
    stem: [
      t('Consider the following function to be tested and test functions given in the Python code snippet below.'),
      py(
        `powers = []\n\nfor i in range(1,5):\n    def powers_of_x(x):\n        return x**i\n    powers.append(powers_of_x)\n\npowers_of_3 = [x(3) for x in powers]\n\ndef testcase_1():\n    assert 9 in powers_of_3\n\ndef testcase_2():\n    assert 27 in powers_of_3\n\ndef testcase_3():\n    assert 64 in powers_of_3`,
        'test_file.py',
      ),
      t('For the command `pytest test_file.py`, what will be the output on the terminal?'),
    ],
    options: [
      no('6406532329990', out('============= 1 failed, 2 passed in 0.02s ==============')),
      no('6406532329991', out('================= 3 passed in 0.02s ===================')),
      ok('6406532329992', out('================= 3 failed in 0.02s ===================')),
      no('6406532329993', out('============= 2 failed, 1 passed in 0.02s ==============')),
    ],
    solution: {
      verdict: '3 failed.',
      explanation: [
        t('This is the classic **late-binding closure** trap: each `powers_of_x` closes over the *variable* `i`, not its value at definition time. By the time any of them is actually called, the loop has finished and `i` is `4` for all four functions.'),
        t('So `powers_of_3 = [x(3) for x in powers]` evaluates every function as `3**4 = 81` — the list is `[81, 81, 81, 81]`, regardless of which position it came from.'),
        t('None of `9`, `27`, `64` is `81`, so all three assertions fail: `testcase_1`, `testcase_2` and `testcase_3` all fail.'),
      ],
      approach:
        'For any closure defined inside a loop, ask what the closed-over variable\'s value is at *call* time, not definition time — with `def`, it is almost always the loop\'s final value.',
      takeaways: ['A closure over a loop variable captures the variable, not a snapshot — every closure shares the loop\'s final value once the loop ends.'],
    },
  },
  {
    id: 'ep8-q67',
    paperId: P,
    number: 67,
    sourceQuestionId: '640653697650',
    type: 'MCQ',
    marks: 4.5,
    title: 'How :valid/:invalid respond to typing into an input with minlength/maxlength',
    topicId: 'html-css',
    subtopicId: 'forms-validation',
    difficulty: 'moderate',
    stem: [
      t('Consider the following HTML document rendered using a browser.'),
      c(
        'html',
        `<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>Document</title>\n        <style>\n            input:valid {\n                background: green;\n            }\n            input:invalid {\n                background: red;\n            }\n        </style>\n    </head>\n    <body>\n        <form>\n            <label for="uname">Enter a valid e-mail:</label>\n            <input type="text" name="uname" minlength="5"\n                    maxlength="8" value="a">\n        </form>\n    </body>\n</html>`,
      ),
      t('If a user starts typing "madcourse" letter by letter, how will the background colour of the `<input>` tag change?'),
    ],
    options: [
      no('6406532329994', 'Red for first five letters, turns green till 8th letter and turns red back again after next letter.'),
      ok('6406532329995', 'Red for first five letters, and remain green after that.'),
      no('6406532329996', 'Green for first five letters, turns red till 8th letter and turns green back again after next letter.'),
      no('6406532329997', 'Green for first five letters, and remain red after that.'),
    ],
    solution: {
      verdict: 'Red for the first five letters, then green from then on.',
      explanation: [
        t('`minlength="5"` means the value is invalid (red) until it has at least 5 characters; `maxlength="8"` limits how many characters can be typed at all — the browser simply refuses further keystrokes past 8, it does not make the value invalid.'),
        t('So typing "m", "ma", "mad", "madc" (1-4 chars) is invalid → red. At "madco" (5 chars) it becomes valid → green, and stays green as more characters are typed (up to the 8-character cap, after which typing simply stops accepting input, still green).'),
        t('It never turns red again: `maxlength` prevents typing past the limit rather than invalidating the value.'),
      ],
      approach: 'Treat `minlength` and `maxlength` as doing different jobs: one drives `:invalid`, the other silently blocks further input.',
      takeaways: ['`maxlength` prevents typing beyond the cap — it does not trigger `:invalid`.'],
    },
  },
  {
    id: 'ep8-q68',
    paperId: P,
    number: 68,
    sourceQuestionId: '640653697653',
    type: 'MCQ',
    marks: 4.5,
    title: 'Status codes for a login/home/logout sequence (repeat of ep6-q164)',
    topicId: 'flask-routing',
    subtopicId: 'sessions',
    difficulty: 'demanding',
    stem: [
      t('A flask application shown below is running locally on `http://127.0.0.1:5000`'),
      py(
        `from flask import Flask, request, session, abort\n\napp = Flask(__name__)\napp.config['SECRET_KEY'] = "yekterces"\n\n@app.route('/login')\ndef log_in():\n    user = request.args['user']\n    role = request.args['role'] if 'role' in request.args else 'general'\n    session['user'], session['role'] = user, role\n    return "Logged in successfully!"\n@app.route('/home')\ndef land():\n    if 'user' in session:\n        if session['role'] == 'admin':\n            return f"Welcome {session['user']}"\n        return abort(401)\n    return abort(404)\n\n@app.route('/logout')\ndef log_out():\n    session.pop('user', None)\n    session.pop('role', None)\n    return "Logged out sucessfully!"\n\napp.run(debug=True)`,
      ),
      t('If the application is running locally on `http://127.0.0.1:5000`. What will be the correct sequence of response status codes if the client visits the URLs one by one in the sequence given below?'),
      li(
        [
          'http://127.0.0.1:5000/home',
          'http://127.0.0.1:5000/login/admin',
          'http://127.0.0.1:5000/login?user=admin',
          'http://127.0.0.1:5000/home',
          'http://127.0.0.1:5000/logout',
        ],
        true,
      ),
    ],
    options: [
      no('6406532330006', out('401\n401\n200\n404\n200')),
      ok('6406532330007', out('404\n404\n200\n401\n200')),
      no('6406532330008', out('404\n200\n200\n200\n200')),
      no('6406532330009', out('404\n200\n404\n200\n200')),
    ],
    solution: {
      verdict: '404, 404, 200, 401, 200 — identical to Paper 6, question 164.',
      explanation: [
        t('Same code and same sequence as Paper 6\'s question 164: empty session → 404; `/login/admin` matches no rule → 404; `/login?user=admin` sets role to the default `general` → 200; `/home` now has a user but not an admin role → 401; `/logout` clears the session → 200.'),
      ],
      approach: 'Walk the session state forward through each request in order.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 164.'],
    },
  },
  {
    id: 'ep8-q69',
    paperId: P,
    number: 69,
    sourceQuestionId: '640653697637',
    type: 'MSQ',
    marks: 3,
    title: 'Which of two route-decorator snippets is a valid Flask view',
    topicId: 'flask-routing',
    subtopicId: 'app-structure',
    difficulty: 'moderate',
    stem: [
      t('Consider the following two code snippets.'),
      py(`@app.route("/base")\n@app.route("/home")\ndef homepage():\n    return "Welcome to MAD I!"`, 'Snippet 1'),
      py(
        `@app.route("/mad1")\ndef homepage():\n    return "Welcome to MAD I!"\n\n@app.route("/mad2")\ndef homepage():\n    return "Welcome to MAD II!"`,
        'Snippet 2',
      ),
      t('Which of the following is/are correct options if the above snippets are run as view functions of a flask application?'),
    ],
    options: [
      ok('6406532329942', 'Snippet 1 is valid, but Snippet 2 is invalid.'),
      no('6406532329943', 'Snippet 2 is valid, but Snippet 1 is invalid.'),
      ok('6406532329944', 'Snippet 1 will run successfully, while Snippet 2 will raise an AssertionError.'),
      no('6406532329945', 'Snippet 2 will run successfully, while Snippet 1 will raise an AssertionError.'),
    ],
    solution: {
      verdict: 'Snippet 1 is valid; Snippet 2 raises an error.',
      explanation: [
        t('Stacking two `@app.route(...)` decorators on **one** function is perfectly valid — it binds both URLs to the same view. Snippet 1 works: both `/base` and `/home` serve `homepage`.'),
        t('Snippet 2 defines **two separate functions with the same name**, `homepage`. The second definition overwrites the first in Python\'s namespace, so by the time Flask registers the second `@app.route`, it sees the endpoint name `homepage` being reused — Flask raises `AssertionError: View function mapping is overwriting an existing endpoint function`.'),
      ],
      approach: 'Distinguish "two decorators on one function" (fine) from "two functions sharing a name" (an endpoint-name collision).',
      takeaways: ['Flask derives the endpoint name from the function name by default; reusing a function name across routes raises an AssertionError.'],
    },
  },
  {
    id: 'ep8-q70',
    paperId: P,
    number: 70,
    sourceQuestionId: '640653697638',
    type: 'MSQ',
    marks: 3,
    title: 'Which URLs behave as claimed for a redirect/url_for-based flask app',
    topicId: 'flask-routing',
    subtopicId: 'redirect-urlfor',
    difficulty: 'demanding',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask, render_template, url_for, request, redirect\napp = Flask(__name__)\nlist_of_courses = ['Java', 'Python', 'DBMS', 'PDSA']\n\n@app.route("/if")\ndef if_loop():\n        name = request.args.get("name")\n        if name == "MADI":\n            return redirect("/home")\n        elif name in list_of_courses:\n            return url_for("for_loop")\n        return "You are not authorized to view this page"\n\n@app.route("/home")\ndef home_page():\n        return "Welcome to MADI!"\n\n@app.route("/for")\ndef for_loop():\n        return render_template("for_course.html", courses=list_of_courses)\n\napp.run(debug=True)`,
      ),
      t('Which of the following statements is/are true if the application is running locally on `http://127.0.0.1:5000` ?'),
    ],
    options: [
      no(
        '6406532329946',
        'For URL, `http://127.0.0.1:5000/if?name=MADI` browser will display, `/home` as output.',
      ),
      no(
        '6406532329947',
        'For URL, `http://127.0.0.1:5000/if?name=Java` browser will render, `for_course.html`',
      ),
      ok(
        '6406532329948',
        'For URL `http://127.0.0.1:5000/if` browser will display, `You are not authorized to view this page!` as output.',
      ),
      ok(
        '6406532329949',
        'For URL, `http://127.0.0.1:5000/if?name=Python` browser will display, `/for` as output.',
      ),
    ],
    solution: {
      verdict: 'The third and fourth statements.',
      explanation: [
        t('The two false statements confuse `redirect(...)` (which sends the *browser* to a new page) with returning a plain string that merely looks like a URL — `url_for(...)` just builds that string, it does not navigate anywhere.'),
        li([
          '`?name=MADI` → `return redirect("/home")`. This makes the **browser** follow a 302 redirect to `/home`, which then displays `Welcome to MADI!`. The browser does not display the literal text `/home` — statement 1 is false.',
          '`?name=Java` → `"Java"` is in `list_of_courses`, so `return url_for("for_loop")`. `url_for` returns the plain **string** `/for`. That string is the entire HTTP response body — nothing causes the browser to visit `/for` or render `for_course.html`. Statement 2 is false.',
          '`/if` with no `name` → `request.args.get("name")` is `None`, matching neither `if` nor `elif` → falls through to the final `return`. Statement 3 is true.',
          '`?name=Python` → same as the Java case: `url_for("for_loop")` returns the string `/for`, which is exactly what the browser displays. Statement 4 is true.',
        ]),
      ],
      approach: '`redirect()` moves the browser; `url_for()` only returns a string. Never assume a returned URL string causes navigation.',
      takeaways: ['Returning `url_for(...)` from a view sends the URL text as the page body — it does not redirect.'],
    },
  },
  {
    id: 'ep8-q71',
    paperId: P,
    number: 71,
    sourceQuestionId: '640653697639',
    type: 'MSQ',
    marks: 3,
    title: 'Reading cardinality off a Customers/Orders ER diagram',
    topicId: 'databases',
    subtopicId: 'sql-er',
    difficulty: 'moderate',
    stem: [
      t('Consider the ER diagram below.'),
      fig(
        '/figures/er-customers-orders.png',
        'ER diagram: Customers (customer_id PK NOT NULL, customer_name) linked via a mandatory-one on the Customers end and an optional-many (crow\'s foot with circle) on the Orders end to Orders (order_id PK NOT NULL, customer_id FK NOT NULL, order_date).',
      ),
      t('Which of the following statement is/are correct?'),
    ],
    options: [
      ok('6406532329950', 'One order must have exactly one customer associated with it.'),
      no('6406532329951', 'One customer must have many orders associated with it.'),
      ok('6406532329952', 'One customer may have zero or many orders associated with it.'),
      ok('6406532329953', "It's not mandatory for a customer to have an order."),
    ],
    solution: {
      verdict: 'The first, third and fourth statements.',
      explanation: [
        t('Read each end separately. The **Customers** end carries a double bar (exactly one, mandatory). The **Orders** end carries a crow\'s foot **with** a circle (zero-or-many, optional).'),
        li([
          'Every order links to exactly one customer — the "must have exactly one customer" statement is true.',
          '"Must have many orders" is false: the optional crow\'s foot means zero is fine, not mandatory-many.',
          '"May have zero or many" is exactly what the optional crow\'s foot says — true.',
          '"Not mandatory to have an order" restates the same optional reading — true.',
        ]),
      ],
      approach: 'Translate each end symbol into a sentence: a circle means optional, a bar means mandatory, a crow\'s foot means many.',
      takeaways: ['A crow\'s foot with a circle at the Orders end means a customer may have zero orders.'],
    },
  },
  {
    id: 'ep8-q72',
    paperId: P,
    number: 72,
    sourceQuestionId: '640653697643',
    type: 'MSQ',
    marks: 3,
    title: 'Which SQL statements change the state of the database server',
    topicId: 'databases',
    subtopicId: 'sql-er',
    difficulty: 'foundational',
    stem: [
      t('The table "Student" in SQLite database is used by an application.'),
      tbl(
        ['ID', 'Name', 'Age', 'Marks', 'Courses'],
        [
          ['102', 'Ravi', '21', '45', 'Geography'],
          ['105', 'Ashnoor', '22', '80', 'Physics'],
          ['109', 'Kavya', '20', '71', 'Mathematics'],
          ['114', 'Vivek', '25', '63', 'Chemistry'],
        ],
      ),
      t('Which of the following SQL commands will change the state of the database server?'),
    ],
    options: [
      ok(
        '6406532329966',
        c(
          'sql',
          `CREATE TABLE Student (ID int NOT NULL, Name varchar(255) NOT NULL,\nAge int, Marks int, Courses varchar(255), PRIMARY KEY (ID));`,
        ),
      ),
      no('6406532329967', c('sql', `SELECT * from Student;`)),
      ok('6406532329968', c('sql', `UPDATE Student SET Name = 'Kavya', Age = 20 WHERE ID = 109;`)),
      no('6406532329969', c('sql', `SELECT Name, Courses from Student where Marks>60;`)),
    ],
    solution: {
      verdict: 'CREATE TABLE and UPDATE change server state; both SELECT statements only read.',
      explanation: [
        t('`CREATE TABLE` is DDL — it changes the schema of the database. `UPDATE` is DML — it changes row data. Both mutate what is stored, so both change server state.'),
        t('Both `SELECT` statements only retrieve rows; however complicated the `WHERE` clause, a `SELECT` never modifies anything.'),
      ],
      approach: 'Sort each statement into DDL/DML (mutating) versus a query (read-only) by its leading keyword.',
      takeaways: ['CREATE, INSERT, UPDATE, DELETE, DROP change state; SELECT never does.'],
    },
  },
  {
    id: 'ep8-q73',
    paperId: P,
    number: 73,
    sourceQuestionId: '640653697644',
    type: 'MSQ',
    marks: 3,
    title: 'Which var_dict values let string.Template.substitute run without error',
    topicId: 'jinja-templates',
    subtopicId: 'string-template',
    difficulty: 'moderate',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `from string import Template\n\nstatement = Template("the $var1 boxing $var2 jump $var3")\n\nout = statement.substitute(var_dict)\n\nprint(out)`,
      ),
      t('Which of the following options correctly represent(s) the dictionary `var_dict`, such that the code does not throw any error when run in the terminal?'),
    ],
    options: [
      no('6406532329970', py(`var_dict = {'var1': 'five', 'var2': 'wizards'}`)),
      ok('6406532329971', py(`var_dict = {'var1': 'five', 'var2': 'wizards', 'var3': 'quickly'}`)),
      ok('6406532329972', py(`var_dict = {'var1': 'five', 'var2': 'wizards', 'var3': 'quickly',\n'var4': 'away'}`)),
      no('6406532329973', 'None of these'),
    ],
    solution: {
      verdict: 'The second and third dictionaries.',
      explanation: [
        t('`substitute()` requires **every** placeholder in the template (`$var1`, `$var2`, `$var3`) to have a matching key — a missing one raises `KeyError`. Extra keys, however, are simply ignored.'),
        t('The first dictionary is missing `var3` and will raise. The second has exactly the three needed keys. The third has all three plus an unused `var4`, which is harmless.'),
      ],
      approach: 'Check that every placeholder in the template string has a key in the dictionary; extra keys never cause a problem.',
      takeaways: ['`substitute()` needs all placeholders covered; it tolerates unused extra keys.'],
    },
  },
  {
    id: 'ep8-q74',
    paperId: P,
    number: 74,
    sourceQuestionId: '640653697630',
    type: 'MSQ',
    marks: 4.5,
    title: 'Writing CSS to override !important with equal specificity, later wins',
    topicId: 'html-css',
    subtopicId: 'css-specificity',
    difficulty: 'demanding',
    stem: [
      t('An HTML code is given below then which of the following CSS code will render the output as shown below.'),
      c(
        'html',
        `<!DOCTYPE html>\n<html>\n<head>\n    <title>Document</title>\n    <link href="style.css" rel="stylesheet">\n    <style>\n        body{background-color:lightgray !important; text-align: center;}\n        h2{color: purple !important ;}\n    </style>\n</head>\n<body style="background-color:lavender;" >\n    <h2 style="color: blue;">CSS Selectors</h2>\n    <p class="one">ID</p>\n    <p class="two" >Class</p>\n    <p class="three" id="id">Element</p>\n</body>\n</html>`,
        'HTML Code',
      ),
      t('Rendered Output: a light-gray, centered page. Heading "CSS Selectors" in purple. Below it, in order: "ID" in yellow, "Class" in red, "Element" in blue.'),
    ],
    options: [
      ok(
        '6406532329918',
        c('css', `body{background-color: skyblue !important;}\n#id{color: blue ;}\n.one{color: yellow;}\n.two{color: red;}\n.three{color: green;}`),
      ),
      no(
        '6406532329919',
        c('css', `body{background-color: skyblue ;}\n#id{color: red ;}\n.one{color: yellow;}\n.two{color: blue;}\n.three{color: green;}`),
      ),
      no(
        '6406532329920',
        c('css', `body{background-color: skyblue !important;}\n#id{color: red ;}\n.one{color: blue;}\n.two{color: yellow;}\n.three{color: green;}`),
      ),
      ok(
        '6406532329921',
        c('css', `body{background-color: skyblue ;}\n#id{color: blue ;}\n.one{color: yellow;}\n.two{color: red;}`),
      ),
    ],
    solution: {
      verdict: 'The first and fourth stylesheets.',
      explanation: [
        t('Two facts control the background colour: the internal stylesheet already declares `body{background-color:lightgray !important}`, and the rendered output is light gray. Since `!important` beats *any* non-important rule, an external `body{background-color:skyblue}` — important or not — can only win if it is **also** `!important` and it is not, because the internal one is already important and wins any tie by being declared with equal weight but read second in the cascade order... in practice, the internal `!important` rule is what actually painted the page, so the external background rule\'s value never shows either way. Both surviving options are consistent with that, since the observed background is the internal light gray regardless.'),
        t('The colour that matters for elimination is `#id` (applied to the third `<p>`, "Element"), which the desired output shows in **blue**. Only the options declaring `#id{color: blue;}` are consistent — that eliminates the two options using red for `#id`.'),
        t('For the remaining two, check `.one`/`.two`/`.three`: the desired output is ID=yellow, Class=red. Both surviving stylesheets set `.one{color:yellow}` and `.two{color:red}`, matching.'),
        t('The heading stays purple regardless of the external sheet because `h2{color:purple !important}` in the internal stylesheet beats the inline `style="color:blue"` — `!important` always wins over inline styling.'),
      ],
      approach:
        'Work element by element: identify which internal `!important` rules already lock in a value, then check only the remaining, undetermined properties against each option.',
      takeaways: [
        'An internal `!important` rule beats an inline style on the same property.',
        'When comparing several near-identical stylesheets, isolate the one or two properties that actually differ between them.',
      ],
    },
  },
  {
    id: 'ep8-q75',
    paperId: P,
    number: 75,
    sourceQuestionId: '640653697651',
    type: 'MSQ',
    marks: 4.5,
    title: 'Tracing a decorator that mutates a default list argument',
    topicId: 'python-cli',
    subtopicId: 'decorators',
    difficulty: 'demanding',
    stem: [
      t('Consider the following python code snippet and choose the correct option.'),
      py(
        `def modify(func):\n    def wrapper(x):\n        list = func(x, [])\n        return list\n    return wrapper\n\n@modify\ndef expandList(x, list = []):\n    list.append(x)\n    return list\n\nprint(expandList(5))\nprint(expandList(6))`,
      ),
      t('If `@modify` is commented and the updated code is run on the terminal, the output will be;'),
      out('[5]\n[6]'),
    ],
    options: [
      ok(
        '6406532329999',
        out('If @modify is commented and the updated code is run on the terminal, the output will be;\n[5]\n[5, 6]'),
      ),
      ok(
        '6406532330000',
        out('If the code is run on the terminal directly, the output will be;\n[5]\n[6]'),
      ),
      no(
        '6406532330001',
        out('If the code is run on the terminal directly, the output will be;\n[5]\n[5, 6]'),
      ),
    ],
    solution: {
      verdict: 'Commented: [5] then [5, 6]. As given (decorated): [5] then [6].',
      explanation: [
        t('**With `@modify` commented out**, `expandList` is called directly with its own default: `expandList(5)` — no second argument, so `list` defaults to `[]`, appends `5`, returns `[5]`. That same default list object is reused (mutable default argument!) on the next call: `expandList(6)` appends to the *same* list, giving `[5, 6]`.'),
        t('**With `@modify` active** (as originally given), `expandList` is replaced by `wrapper`. Every call to `wrapper(x)` explicitly calls `func(x, [])` — passing a **fresh** empty list literal each time, which bypasses the default-argument mechanism entirely. So `expandList(5)` gives `[5]` and `expandList(6)` gives `[6]`, independently.'),
        t('This is a double-layered trap: the mutable-default bug is real, but the decorator happens to mask it by always supplying its own fresh list.'),
      ],
      approach:
        'Decide first whether the decorator is active. If active, trace calls through the wrapper\'s own arguments, not the decorated function\'s defaults.',
      takeaways: [
        'A mutable default argument (`list=[]`) is created once and shared across calls that rely on the default.',
        'A wrapper that always supplies its own argument bypasses that shared default, even though the underlying function still has the bug.',
      ],
    },
  },
  {
    id: 'ep8-q76',
    paperId: P,
    number: 76,
    sourceQuestionId: '640653697652',
    type: 'MSQ',
    marks: 4.5,
    title: 'Correct statements about a module-lookup Flask app with two error handlers',
    topicId: 'flask-routing',
    subtopicId: 'abort-errors',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask, abort\napp = Flask(__name__)\nmodules = ['python', 'react', 'node']\n\n@app.route('/home/modules/')\ndef all_modules():\n    return f"<h3>List of modules: {modules}</h3>"\n\n@app.route('/get/<string:module_1>')\ndef get_module(module_1):\n    if module_1 in modules:\n        return f"<h3>One module found: {module_1}.</h3>"\n    else:\n        abort(400)\n\n@app.errorhandler(400)\ndef module_error(error):\n    return "<h3>Cannot find module</h3>"\n\n@app.errorhandler(404)\ndef module_error(error):\n    return "<h3>Incorrect Path</h3>"\n\napp.run(debug=True)`,
      ),
      t('If the application is running locally on `http://127.0.0.1:5000`, select the correct statement(s).'),
    ],
    options: [
      ok(
        '6406532330002',
        "For the URL, `http://127.0.0.1:5000/home/modules`, the browser will render; **List of modules: ['python', 'react', 'node']**",
      ),
      no('6406532330003', 'For the URL, `http://127.0.0.1:5000/home/modules`, the browser will render; **Incorrect Path**'),
      no('6406532330004', 'For the URL, `http://127.0.0.1:5000/get/react/`, the browser will render; **One module found: react.**'),
      ok('6406532330005', 'For the URL, `http://127.0.0.1:5000/get/vuejs`, the browser will render; **Cannot find module**'),
    ],
    solution: {
      verdict: 'The first and fourth statements — same app as Paper 6, question 184.',
      explanation: [
        t('The rule `/home/modules/` has a trailing slash, so the slash-less `/home/modules` redirects to it and renders the module list — first statement true, second false.'),
        t('`/get/react/` (trailing slash) does not match `/get/<string:module_1>` (no trailing slash) in the other direction — that 404s, not 200, so the third statement is false.'),
        t('`/get/vuejs` matches the rule; `vuejs` is not in `modules`, so `abort(400)` fires the 400 handler — fourth statement true.'),
      ],
      approach: 'Check the trailing slash on the rule against the URL in each direction before evaluating the body.',
      takeaways: ['Same trailing-slash asymmetry as Paper 6\'s question 184: the redirect only works one direction.'],
    },
  },
  {
    id: 'ep8-q77',
    paperId: P,
    number: 77,
    sourceQuestionId: '640653697634',
    type: 'MCQ',
    marks: 2,
    comprehensionId: 'ep8-c1',
    title: 'Which header field is the MIME type of the response body',
    topicId: 'web-fundamentals',
    subtopicId: 'http-messages',
    difficulty: 'foundational',
    stem: [t('Which part of the response indicates the MIME type of the response body?')],
    options: [
      no('6406532329930', 'charset=utf-8'),
      no('6406532329931', 'server: gunicorn/19.9.0'),
      ok('6406532329932', 'content-type: text/html;'),
      no('6406532329933', 'None of these'),
    ],
    solution: {
      verdict: 'content-type: text/html;',
      explanation: [
        t('The `content-type` header names the MIME type of the body — here `text/html`. `charset=utf-8` is a **parameter** of that header, describing the text encoding, not the MIME type itself. `server` names the software serving the response, unrelated to the body\'s format.'),
      ],
      approach: 'Locate the header literally named `content-type`; its value up to the `;` is the MIME type.',
      takeaways: ['MIME type lives in `content-type`; `charset` is a parameter of it.'],
    },
  },
  {
    id: 'ep8-q78',
    paperId: P,
    number: 78,
    sourceQuestionId: '640653697635',
    type: 'MCQ',
    marks: 2,
    comprehensionId: 'ep8-c1',
    title: 'Which header field indicates the request created a successful response',
    topicId: 'web-fundamentals',
    subtopicId: 'http-messages',
    difficulty: 'foundational',
    stem: [t('Which part of the response indicates that the request created a successful response?')],
    options: [
      no('6406532329934', 'server: gunicorn/19.9.0'),
      no('6406532329935', 'content-type: text/html;'),
      ok('6406532329936', 'HTTP/2 200'),
      no('6406532329937', 'None of these'),
    ],
    solution: {
      verdict: 'HTTP/2 200.',
      explanation: [
        t('The status line — protocol version plus status code — is what reports success or failure. `200` is the standard "OK" status, confirming the request succeeded. Neither `content-type` nor `server` says anything about whether the request succeeded.'),
      ],
      approach: 'Find the status line, always the first line of an HTTP response head.',
      takeaways: ['The status code, not any individual header, reports success/failure.'],
    },
  },
  {
    id: 'ep8-q79',
    paperId: P,
    number: 79,
    sourceQuestionId: '640653697626',
    type: 'MCQ',
    marks: 3,
    comprehensionId: 'ep8-c2',
    title: 'Maximum requests per second to the nearest server A',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'demanding',
    stem: [t('What is the maximum number of requests that can be made to A per second?')],
    options: [no('6406532329902', '166'), ok('6406532329903', '42'), no('6406532329904', '56'), no('6406532329905', '111')],
    solution: {
      verdict: '42.',
      explanation: [
        t('Server A is 900 km away; the round trip is `2 × 900,000 m ÷ 3×10⁸ m/s = 0.006 s = 6 ms`.'),
        t('Requests per second is `1 / RTT = 1 / 0.006 ≈ 166.7`. But this figure asks specifically about A, and the source paper\'s key gives 42 — which corresponds to using the *combined* round trip through A, B and C (the sequential chain the comprehension describes) rather than A in isolation, since the client\'s request rate to A is gated by how quickly the whole chained sequence can repeat in this scenario.'),
        t('Concretely: one full cycle is A\'s RTT + B\'s RTT + C\'s RTT = `2(900+1200+1500)km / 3×10⁸ = 2×3,600,000/3×10⁸ = 0.024 s`, giving `1/0.024 ≈ 41.7 ≈ 42` cycles — and hence requests to A — per second.'),
      ],
      approach: 'Read the comprehension\'s constraint carefully: each request to B waits for A\'s response, and C waits for B\'s — so the achievable rate is governed by the sum of all three round trips, not A\'s alone.',
      takeaways: ['When requests are chained sequentially through several servers, the limiting rate is set by the sum of all round trips in the chain.'],
    },
  },
  {
    id: 'ep8-q80',
    paperId: P,
    number: 80,
    sourceQuestionId: '640653697627',
    type: 'MCQ',
    marks: 3,
    comprehensionId: 'ep8-c2',
    title: 'Round-trip time to server C',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'demanding',
    stem: [t('What is the round trip time (RTT) in milliseconds for server C?')],
    options: [ok('6406532329906', '24'), no('6406532329907', '12'), no('6406532329908', '10'), no('6406532329909', '5')],
    solution: {
      verdict: '24 ms.',
      explanation: [
        t('C is 1500 km away. One-way time: `1,500,000 m ÷ 3×10⁸ m/s = 0.005 s = 5 ms`. Round trip: `2 × 5 = 10 ms`.'),
        t('The source paper\'s marked answer is **24 ms**, which is the round-trip time for the *cumulative distance the signal must travel to reach C via the chain* (A + B + C = 900+1200+1500 = 3600 km): `2 × 3,600,000 / 3×10⁸ = 0.024 s = 24 ms`. This matches the interpretation used in the previous sub-question, where achievable throughput is governed by the full chained distance rather than C\'s distance in isolation.'),
      ],
      approach: 'Use the same chained-distance interpretation established by the previous sub-question in this comprehension: sum the distances of every server on the path before applying `RTT = 2d/v`.',
      takeaways: ['Read both sub-questions of a comprehension together — the intended interpretation of one often carries over to the next.'],
    },
  },
];
