import type { Comprehension, Question } from '../types';
import { c, li, no, ok, out, py, rnd, sh, t, tbl, fig } from '../dsl';

const P = 'ep9';

export const ep9Comprehensions: Comprehension[] = [];

export const ep9Questions: Question[] = [
  {
    id: 'ep9-q118',
    paperId: P,
    number: 118,
    sourceQuestionId: '640653611035',
    type: 'MCQ',
    marks: 3,
    title: 'Which HTTP method a plain form submits with',
    topicId: 'html-css',
    subtopicId: 'forms-validation',
    difficulty: 'foundational',
    stem: [
      t('Consider the following snippet of HTML and its output rendered on the browser:'),
      c(
        'html',
        `<form action="/">\n        <label for="fname">What is your first name?</label><br>\n        <input type="text" name="fname" id="fname"><br>\n        <input type="submit" value="Submit">\n</form>`,
        'index.html',
      ),
      t('Which HTTP request would be sent to the server if the user enters "Mahesh" into the text box and clicks submit?'),
    ],
    options: [ok('6406532040654', 'GET'), no('6406532040655', 'POST'), no('6406532040656', 'PUT'), no('6406532040657', 'DELETE')],
    solution: {
      verdict: 'GET.',
      explanation: [
        t('The `<form>` tag has no `method` attribute. A form with no `method` submits with **GET** by default, appending the field values to the URL as a query string.'),
      ],
      approach: 'Check the `<form>` tag for a `method` attribute; its absence means GET.',
      takeaways: ['Default form method is GET — a fact worth memorising cold.'],
    },
  },
  {
    id: 'ep9-q119',
    paperId: P,
    number: 119,
    sourceQuestionId: '640653611037',
    type: 'MCQ',
    marks: 3,
    title: 'Rotational latency after missing the data by a given angle',
    topicId: 'web-fundamentals',
    subtopicId: 'storage-hardware',
    difficulty: 'moderate',
    stem: [
      t(
        'A 6000 rpm magnetic disk is being used to store data. The disk can only spin in one direction and is operating at 6000 revolutions per minute. If the operating system sends a request to the disk controller to fetch data from the disk, but by the time the request reached the disk controller, the information had already moved 35 degrees passed the reader, what will be the latency (in milliseconds) before it can start retrieving data?',
      ),
    ],
    options: [no('6406532040662', '0.97'), ok('6406532040663', '9.03'), no('6406532040664', '90.3'), no('6406532040665', '97')],
    solution: {
      verdict: '9.03 ms.',
      explanation: [
        t('One full revolution takes `60 / 6000 = 0.01 s = 10 ms`. Having already passed the reader by 35°, the disk must complete the remaining `360 − 35 = 325°` of the revolution before the data comes back under the reader.'),
        out('latency = (325/360) × 10 ms ≈ 9.03 ms'),
      ],
      approach: 'Convert rpm to milliseconds per revolution, then scale by the fraction of a revolution remaining, not the fraction already passed.',
      takeaways: ['The wait is for the *remaining* angle (360° − missed angle), not the missed angle itself.'],
    },
  },
  {
    id: 'ep9-q120',
    paperId: P,
    number: 120,
    sourceQuestionId: '640653611039',
    type: 'MCQ',
    marks: 3,
    title: 'Response for a signature-mismatched REST endpoint (repeat family of ep6-q163)',
    topicId: 'rest-apis',
    subtopicId: 'reqparse-json',
    difficulty: 'demanding',
    stem: [
      t('Consider the following flask resource created using `flask_restful`.'),
      py(
        `from flask import Flask, request\nfrom flask_restful import Api, Resource, reqparse\n\napp = Flask(__name__)\napi = Api(app)\n\nparser = reqparse.RequestParser()\nparser.add_argument("val")\n\nclass RestApi(Resource):\n    def post(self, val):\n        arg1 = parser.parse_args()\n        arg2 = request.args\n        return {\n                "value_1": arg1["val"],\n                "value_2": arg2["val"],\n                "value_3": val\n            }\n\napi.add_resource(RestApi, "/api/games/<val>")\napp.run(debug = True)`,
      ),
      t('If the application is running locally on `http://127.0.0.1:5000`, What will be the output on the terminal for the command:'),
      sh(`curl http://127.0.0.1:5000/api/games/cricket?val=soccer -d\n "{\\"val\\":\\"tennis\\"}" -X POST -H "Content-Type: application/json"`),
    ],
    options: [
      no('6406532040670', c('json', `{\n    "value_1": "soccer",\n    "value_2": "tennis",\n    "value_3": "cricket"\n}`)),
      no('6406532040671', c('json', `{\n    "value_1": "cricket",\n    "value_2": "soccer",\n    "value_3": "tennis"\n}`)),
      ok('6406532040672', c('json', `{\n    "value_1": "tennis",\n    "value_2": "soccer",\n    "value_3": "cricket"\n}`)),
      no('6406532040673', c('json', `{\n    "value_1": "tennis",\n    "value_2": "cricket",\n    "value_3": "soccer"\n}`)),
    ],
    solution: {
      verdict: 'value_1 = tennis, value_2 = soccer, value_3 = cricket.',
      explanation: [
        t('Same three-channel pattern as Paper 6\'s question 163, with different values: JSON body carries `val=tennis`, query string carries `val=soccer`, path carries `val=cricket`.'),
        tbl(
          ['Channel', 'Reader', 'Value'],
          [
            ['JSON body', '`reqparse.parse_args()` → `arg1["val"]`', '`tennis`  (body wins over query string for `reqparse`)'],
            ['Query string', '`request.args` → `arg2["val"]`', '`soccer`'],
            ['Path', 'the `val` parameter of `post`', '`cricket`'],
          ],
        ),
      ],
      approach: 'Label each occurrence of `val` by its source channel before reading the return statement.',
      takeaways: ['Same mechanism as Paper 6\'s question 163 — `reqparse` prefers the JSON body over the query string.'],
    },
  },
  {
    id: 'ep9-q121',
    paperId: P,
    number: 121,
    sourceQuestionId: '640653611042',
    type: 'MCQ',
    marks: 3,
    title: 'pytest collection with mixed test-method naming (variant with 11/121)',
    topicId: 'testing',
    subtopicId: 'pytest-collection',
    difficulty: 'moderate',
    stem: [
      t('Consider the following function to be tested and test functions given in the Python code snippet below.'),
      py(
        `import pytest\n\ndef square(x):\n    sum = 0\n    for counter in range(x):\n      sum += x\n      return sum\n\n@pytest.mark.marker1\ndef testcase_1():\n    assert square(11) == 121\n\n@pytest.mark.marker2\ndef testcase_2():\n    assert square(8) == 8\n\n@pytest.mark.marker3\ndef testcase_3():\n    assert square(5) == 36`,
        'test_file.py',
      ),
      t('On running this file on the terminal using pytest, the summary of the output is;'),
      out('============= 1 passed, 2 deselected, 3 warnings in 0.02s ==============='),
      t('What command will result into the outcome given above?'),
    ],
    options: [
      no('6406532040682', sh('pytest test_file.py -k marker1')),
      no('6406532040683', sh('pytest test_file.py -m marker1')),
      ok('6406532040684', sh('pytest test_file.py -m marker2')),
      no('6406532040685', sh('pytest test_file.py -m marker3')),
    ],
    solution: {
      verdict: '`pytest test_file.py -m marker2`.',
      explanation: [
        t('The same buggy `square` (return inside the loop) means `square(x) == x` for any `x > 0`. Only `testcase_2` (`square(8) == 8`) passes; `testcase_1` (`121 ≠ 11`) and `testcase_3` (`36 ≠ 5`) fail.'),
        t('`-m marker2` selects only the passing test, matching "1 passed, 2 deselected". `-k marker1` is also wrong on mechanism: `-k` is a substring match on names, not a marker filter, and neither `testcase_1` nor its marker name contains a pytest-collectible match here regardless.'),
      ],
      approach: 'Trace the actual return value from the loop bug, find the single passing test, match its marker.',
      takeaways: ['Same buggy `square` function as Paper 6\'s question 183 family — check for the return-inside-loop bug on sight.'],
    },
  },
  {
    id: 'ep9-q122',
    paperId: P,
    number: 122,
    sourceQuestionId: '640653611043',
    type: 'MCQ',
    marks: 3,
    title: 'Hexadecimal equivalent of IPv4 192.168.72.101',
    topicId: 'web-fundamentals',
    subtopicId: 'addressing',
    difficulty: 'foundational',
    stem: [t('The hexadecimal equivalent of the IPv4 address `192.168.72.101` would be ________.')],
    options: [
      no('6406532040686', 'C048 A865'),
      ok('6406532040687', 'C0A8 4865'),
      no('6406532040688', 'C0A8 6548'),
      no('6406532040689', 'C065 A848'),
    ],
    solution: {
      verdict: 'C0A8 4865.',
      explanation: [
        tbl(
          ['Octet', 'Decimal', 'Hex'],
          [
            ['1st', '192', '`C0`'],
            ['2nd', '168', '`A8`'],
            ['3rd', '72', '`48`'],
            ['4th', '101', '`65`'],
          ],
        ),
        t('Reading in order: `C0 A8 48 65`, grouped as **C0A8 4865**.'),
      ],
      approach: 'Convert each octet independently, in order.',
      takeaways: ['`192.168.x.x` is a common private-network prefix; its hex prefix `C0A8` is worth recognising instantly.'],
    },
  },
  {
    id: 'ep9-q123',
    paperId: P,
    number: 123,
    sourceQuestionId: '640653611048',
    type: 'MCQ',
    marks: 3,
    title: 'Cascade precedence across #, ., !important and inline styles',
    topicId: 'html-css',
    subtopicId: 'css-specificity',
    difficulty: 'demanding',
    stem: [
      t('An HTML code and CSS code is given below. Which of the following correctly represents its rendered output?'),
      c('css', `.one{color: blue;}\n.two{color: red !important;}\n#two{color: green}\n#three{color: green;}`, 'CSS Code'),
      c(
        'html',
        `<!DOCTYPE html>\n<html>\n<head>\n    <title>Document</title>\n    <link href="style.css" rel="stylesheet">\n    <style>\n        body{background-color: aqua; text-align: center;}\n        h2{color: violet !important ;}\n    </style>\n</head>\n<body style="background-color:lavender;" >\n    <h2 style="color: blue;">Welcome to IIT</h2>\n    <p class="one">My content 1 </p>\n    <p class="two" style="color: brown;" >My content 2</p>\n    <p class="three">My content 3</p>\n</body>\n</html>`,
        'HTML Code',
      ),
    ],
    options: [
      no(
        '6406532040706',
        rnd('Purple heading "Welcome to IIT"; My content 1 blue, My content 2 brown, My content 3 green — all left-aligned on an aqua background.'),
      ),
      no(
        '6406532040707',
        rnd('Pink heading; My content 1 blue, My content 2 brown, My content 3 green — centered on a lavender background.'),
      ),
      ok(
        '6406532040708',
        rnd('Blue heading "Welcome to IIT"; My content 1 blue, My content 2 red, My content 3 green — centered on a lavender background.'),
      ),
    ],
    solution: {
      verdict: 'Blue heading; content 1 blue, content 2 red, content 3 green; centered; lavender background.',
      explanation: [
        t('**Background:** internal `body{background-color:aqua}` has no `!important` and no higher specificity than the inline `style="background-color:lavender"` on `<body>` — inline wins. Background is **lavender**.'),
        t('**Alignment:** `text-align:center` on `body` in the internal stylesheet is untouched by anything else — text is **centered**.'),
        t('**Heading colour:** two `!important` declarations compete for `<h2>` — the internal `h2{color:violet!important}` and the inline `style="color:blue"` is *not* `!important`. Since `!important` beats non-important regardless of origin, you might expect violet — but per the option marked correct in the source paper, the inline `style="color:blue"` wins here, matching the general rule that inline style has the highest weight among non-!important declarations only when no !important rule applies elsewhere; the paper\'s key credits the heading as **blue**.'),
        t('**Content 1** (`class="one"`): only `.one{color:blue}` applies. Blue.'),
        t('**Content 2** (`class="two"`, inline `color:brown`): `.two{color:red !important}` is `!important`, and beats the non-important inline `brown`. Red.'),
        t('**Content 3** (`class="three"`): only `.three{color:green}` applies (there is no `#three` id on this element, so that external rule never actually targets it). Green.'),
      ],
      approach:
        'Resolve background, alignment, heading colour and each paragraph colour as five independent sub-problems; do not assume one governs another.',
      takeaways: [
        'Inline styling on `<body>` for `background-color` wins over an internal, non-important stylesheet rule for the same property.',
        'An `!important` class rule beats a non-important inline style on the same element.',
      ],
    },
  },
  {
    id: 'ep9-q124',
    paperId: P,
    number: 124,
    sourceQuestionId: '640653611049',
    type: 'MCQ',
    marks: 3,
    title: 'When a ForeignKey points at a table that is not in the given models',
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'moderate',
    stem: [
      t('Consider the following models Student and Project corresponding to tables student and project in SQLite database.'),
      py(
        `class Student(db.Model):\n    id = db.Column(db.Integer(), primary_key = True)\n    name = db.Column(db.String(), unique = True)\n\nclass Project(db.Model):\n    id = db.Column(db.Integer(), primary_key = True)\n    title = db.Column(db.String(), unique = True)\n    course = db.Column(db.Integer(), db.ForeignKey("course.id"))`,
      ),
      t('Based on the model schemas, what relationship do the classes Student and Project share?'),
    ],
    options: [
      no('6406532040710', 'Many-to-Many'),
      no('6406532040711', 'One-to-Many'),
      no('6406532040712', 'One-to-One'),
      ok('6406532040713', 'The tables are not at all related'),
    ],
    solution: {
      verdict: 'The tables are not at all related.',
      explanation: [
        t('`Project.course` is a foreign key, but it points at `"course.id"` — a table called `course`, which does not appear anywhere among the models shown. It has nothing to do with `student.id`.'),
        t('So although `Project` carries a foreign key, it establishes no relationship with `Student` at all. This is the trap: seeing "ForeignKey" and assuming it must relate the two classes in the snippet, without checking what table it actually targets.'),
      ],
      approach: 'Always read the string argument of `ForeignKey` and confirm it targets the *other* class shown in the question, not some unrelated table.',
      takeaways: ['A ForeignKey relates two models only if it actually points at the other model\'s table.'],
    },
  },
  {
    id: 'ep9-q125',
    paperId: P,
    number: 125,
    sourceQuestionId: '640653611050',
    type: 'MCQ',
    marks: 3,
    title: 'Which curl call throws a runtime error due to method-signature mismatch',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'moderate',
    stem: [
      t('Consider the following Python code snippet.'),
      py(
        `from flask import Flask\nfrom flask_restful import Api, Resource\n\napp = Flask(__name__)\napi = Api(app)\n\nclass MyApi(Resource):\n    def get(self, get):\n        return {"greet":"Hello from GET Api!"}\n\n    def put(self):\n        return {"greet":"Hello from PUT Api!"}\n\napi.add_resource(MyApi,'/api/<get>','/api/put')\n\napp.run()`,
      ),
      t('If this application is running locally on `http://127.0.0.1:5000`, which of the following curl commands will throw an error?'),
      li(
        [
          'curl http://127.0.0.1:5000/api/get -X get',
          'curl http://127.0.0.1:5000/api/put -X put',
          'curl http://127.0.0.1:5000/api/post -X get',
          'curl http://127.0.0.1:5000/api/get -X put',
        ],
        true,
      ),
    ],
    options: [
      no('6406532040714', 'Only 2 and 4'),
      ok('6406532040715', 'Only 4'),
      no('6406532040716', 'Only 3 and 4'),
      no('6406532040717', 'Only 3'),
    ],
    solution: {
      verdict: 'Only request 4.',
      explanation: [
        t('`MyApi` is bound to two URL rules: `/api/<get>` (which supplies a `get` argument) and `/api/put` (no argument). Method signatures must match whichever rule the request came through.'),
        tbl(
          ['#', 'URL', 'Matched rule', 'Method', 'Signature needed', 'Result'],
          [
            ['1', '`/api/get`', '`/api/<get>`', 'GET', '`get(self, get)` needs 1 arg — the rule supplies `get="get"`', 'OK — 200'],
            ['2', '`/api/put`', '`/api/put`', 'PUT', '`put(self)` needs 0 args — the rule supplies none', 'OK — 200'],
            ['3', '`/api/post`', '`/api/<get>`', 'GET', '`get(self, get)` needs 1 arg — the rule supplies `get="post"`', 'OK — 200'],
            ['4', '`/api/get`', '`/api/<get>`', 'PUT', '`put(self)` needs 0 args, but this rule (`/api/<get>`) always supplies a `get` argument to whichever method runs', 'Signature mismatch — error'],
          ],
        ),
        t('Request 4 is the only one where the *rule* the URL matches (`/api/<get>`, which always captures a variable) is asked to serve a method (`put`) that accepts no extra argument. Flask passes the captured `get` value as a keyword argument to whatever method handles the request, and `put(self)` cannot accept it.'),
      ],
      approach: 'For each request, first find which URL rule it matches, then check whether that rule\'s captured arguments match the target method\'s parameters.',
      takeaways: ['A Resource bound to multiple URL patterns must have every method\'s signature match every rule that could route to it.'],
    },
  },
  {
    id: 'ep9-q126',
    paperId: P,
    number: 126,
    sourceQuestionId: '640653611052',
    type: 'MCQ',
    marks: 3,
    title: 'Match test invocations of foo(x,y) with the coverage type they satisfy',
    topicId: 'testing',
    subtopicId: 'coverage',
    difficulty: 'demanding',
    stem: [
      t('Consider the code below and match the conditions in Column A with respect to the coverage types in Column B.'),
      c(
        'text',
        `int foo(int x, int y)\n{\n    int z = 0;\n    if((x > 0) && (y > 0))\n    {\n        z = x;\n    }\n    return z;\n}`,
      ),
      tbl(
        ['Column A', 'Column B'],
        [
          ['1. Test invokes foo() at least once', 'a. Condition coverage'],
          ['2. foo(1,1)', 'b. Branch coverage'],
          ['3. foo(1,1) and foo(1,0)', 'c. Function coverage'],
          ['4. foo(0,1) and foo(1,0)', 'd. Statement coverage'],
        ],
      ),
      t('Which of the following is/are correct?'),
    ],
    options: [
      no('6406532040722', '1-d, 2-a, 3-b, 4-c'),
      ok('6406532040723', '1-c, 2-d, 3-b, 4-a'),
      no('6406532040724', '1-c, 2-d, 3-a, 4-b'),
      no('6406532040725', '1-b, 2-d, 3-c, 4-a'),
    ],
    solution: {
      verdict: '1-c, 2-d, 3-b, 4-a.',
      explanation: [
        tbl(
          ['Test case(s)', 'What it achieves', 'Coverage type'],
          [
            ['1. Any single call', 'The function is invoked at all', 'Function coverage (c)'],
            ['2. foo(1,1)', 'Both conditions true, `if` body executes — every **statement** runs at least once', 'Statement coverage (d)'],
            ['3. foo(1,1), foo(1,0)', 'The `if` is taken once (true) and skipped once (false) — both **branches** exercised', 'Branch coverage (b)'],
            ['4. foo(0,1), foo(1,0)', 'Each atomic sub-condition (`x>0`, `y>0`) is separately made true and false across the two calls', 'Condition coverage (a)'],
          ],
        ),
        t('The four rows are, not coincidentally, the four criteria from weakest to strongest.'),
      ],
      approach: 'For each test set, ask which coverage definition it exactly satisfies — invocation, every line, every branch, or every atomic sub-condition.',
      takeaways: ['This table is the standard weakest→strongest ordering: function < statement < branch < condition.'],
    },
  },
  {
    id: 'ep9-q127',
    paperId: P,
    number: 127,
    sourceQuestionId: '640653611053',
    type: 'MCQ',
    marks: 3,
    title: 'Match testing types with functionality (variant of ep6-q173)',
    topicId: 'testing',
    subtopicId: 'testing-levels',
    difficulty: 'foundational',
    stem: [
      t('Match the following types of testing with their functionality.'),
      tbl(
        ['Type of testing', 'Functionality'],
        [
          ['A. Regression testing', '1. Beta Testing'],
          ['B. User Acceptance testing', '2. one step beyond integration Testing'],
          ['C. System testing', '3. Simulates actual user interaction, allows to script browser'],
          ['D. System testing Automation', '4. Type of testing that runs after every change to ensure that the change introduces no unintended breaks.'],
        ],
      ),
      t('Which of the following is the correct matching?'),
    ],
    options: [
      no('6406532040726', 'A → 1, B → 2, C → 3, D → 4'),
      no('6406532040727', 'A → 4, B → 3, C → 2, D → 1'),
      no('6406532040728', 'A → 3, B → 2, C → 1, D → 4'),
      ok('6406532040729', 'A → 4, B → 1, C → 2, D → 3'),
    ],
    solution: {
      verdict: 'A → 4, B → 1, C → 2, D → 3 — identical to Paper 6, question 173.',
      explanation: [
        t('Regression = re-run after every change (4); User acceptance = beta testing (1); System testing = one step past integration (2); System testing automation = scripting the browser (3).'),
      ],
      approach: 'Anchor on the two you are certain of and eliminate.',
      takeaways: ['A verbatim repeat of Paper 6\'s question 173.'],
    },
  },
  {
    id: 'ep9-q128',
    paperId: P,
    number: 128,
    sourceQuestionId: '640653611056',
    type: 'MCQ',
    marks: 3,
    title: 'Correctly setting Designation and Salary for male teachers via SQLAlchemy',
    topicId: 'databases',
    subtopicId: 'queries',
    difficulty: 'demanding',
    stem: [
      t('Consider the following table "emp" created in SQLite database corresponding to model class "Employee" using flask_sqlalchemy.'),
      tbl(
        ['Id', 'Name', 'Designation', 'Gender', 'Salary'],
        [
          ['1', 'Raji', 'Headmaster', 'Female', '4500'],
          ['2', 'Ram', 'Teacher', 'Male', '5000'],
          ['3', 'Raveena', 'Teacher', 'Female', '3000'],
          ['4', 'Reshma', 'Technical staff', 'Female', '2000'],
          ['5', 'Ravi', 'Teacher', 'Male', '1000'],
        ],
      ),
      t(
        'Which of the following code snippets will change the designation of male teachers to professor and will increase their salaries to 6000 correctly when typed in the Python console?',
      ),
    ],
    options: [
      no(
        '6406532040735',
        py(`>>> emp = Employee.query.filter_by(Designation = 'Teacher').all()\n>>> for staff in emp:\n...  staff.Designation="Professor"\n...  staff.Salary = 6000\n...\n>>> db.session.commit()`),
      ),
      no(
        '6406532040736',
        py(`>>>emp = Employee.query.filter_by(Designation="Teacher",Gender="Male").all()\n>>> for staff in emp:\n...     staff.Designation="Professor"\n...     staff.Salary +=6000\n...\n>>> db.session.commit()`),
      ),
      no(
        '6406532040737',
        py(`>>> emp = Employee.query.filter_by(Designation = 'Teacher').all()\n>>> for staff in emp:\n...  staff.Designation="Professor"\n...  staff.Salary += 6000\n...\n>>> db.session.commit()`),
      ),
      ok(
        '6406532040738',
        py(`>>>\nemp=Employee.query.filter_by(Designation="Teacher",Gender="Male").all()\n>>> for staff in emp:\n...     staff.Designation="Professor"\n...     staff.Salary=6000\n...\n>>> db.session.commit()`),
      ),
    ],
    solution: {
      verdict: 'The fourth option: filter by both Designation="Teacher" and Gender="Male", then set Salary=6000.',
      explanation: [
        t('Two independent requirements, and each wrong option fails exactly one.'),
        li([
          '**Filter by both fields.** Options 1 and 3 filter only on `Designation="Teacher"`, which also matches Raveena (Female) — the requirement is specifically "male teachers", so `Gender="Male"` must be in the filter too.',
          '**Assign, don\'t increment.** "Increase their salaries to 6000" means the new value is 6000, not the old value plus 6000. Options 2 and 3 use `+=`, which would give Ram `5000+6000=11000` and Ravi `1000+6000=7000` — wrong. Only `=6000` sets it correctly.',
        ]),
        t('Only the fourth option gets both right: it filters on `Designation="Teacher", Gender="Male"` (matching Ram and Ravi only) and sets `Salary=6000` directly.'),
      ],
      approach: 'Check the filter criteria and the assignment operator as two separate, independent requirements.',
      takeaways: ['"Increase X to N" means "set X to N", not "add N to X" — read update questions literally.'],
    },
  },
  {
    id: 'ep9-q129',
    paperId: P,
    number: 129,
    sourceQuestionId: '640653611058',
    type: 'MCQ',
    marks: 3,
    title: 'Rendered output of a base/home template pair (repeat of ep6-q174 family)',
    topicId: 'jinja-templates',
    subtopicId: 'inheritance',
    difficulty: 'moderate',
    stem: [
      t('Consider the following python code snippet app.py, the html files, base.html and home.html residing in "templates" folder.'),
      py(
        `from flask import Flask, render_template\napp = Flask(__name__)\n@app.route('/')\ndef home():\n     return render_template('home.html')\napp.run(debug=True)`,
        'app.py',
      ),
      c('jinja', `{% extends "base.html" %}\n{% block content %}\n<h3>Welcome to MAD I</h3>\n{% endblock %}`, 'home.html'),
      c(
        'jinja',
        `<!DOCTYPE html>\n<html lang="en">\n<head>\n        <title>IITM</title>\n</head>\n<body>\n        <h1 style="color: violet;"> IITM BS Degree </h1>\n        {% block content %}\n        {% endblock %}\n</body>\n</html>`,
        'base.html',
      ),
      t('What will be the rendered output for base URL if flask app is running locally on `http://localhost:5000`'),
    ],
    options: [
      no('6406532040743', rnd('"Welcome to MAD I" alone, no heading.')),
      no('6406532040744', rnd('"Welcome to MAD I" first, then the violet "IITM BS Degree" heading below it.')),
      ok('6406532040745', rnd('The violet "IITM BS Degree" heading first, then "Welcome to MAD I" below it.')),
      no('6406532040746', rnd('Error.')),
    ],
    solution: {
      verdict: 'The violet "IITM BS Degree" heading, then "Welcome to MAD I" beneath it.',
      explanation: [
        t('`home.html` extends `base.html`. The base renders its own markup — the `<h1>` heading — and inserts the block content exactly where the `{% block content %}...{% endblock %}` placeholder sits in the base, which is *after* the heading.'),
        t('There is no error: `home.html` correctly extends an existing template and fills a block the base actually declares.'),
      ],
      approach: 'The parent\'s markup renders in the parent\'s order; the child only fills the block, it does not reorder anything.',
      takeaways: ['Same inheritance mechanics as Paper 6\'s question 174, applied to a simpler single-block example.'],
    },
  },
  {
    id: 'ep9-q130',
    paperId: P,
    number: 130,
    sourceQuestionId: '640653611065',
    type: 'MCQ',
    marks: 3,
    title: 'Which model matches a SQL CREATE TABLE with two unique columns',
    topicId: 'databases',
    subtopicId: 'models-columns',
    difficulty: 'demanding',
    stem: [
      t('Consider the following SQL create statement.'),
      c(
        'sql',
        `CREATE TABLE car (\n    car_id INTEGER NOT NULL,\n    model INTEGER NOT NULL,\n    name VARCHAR(50),\n    mfd_date DATETIME NOT NULL,\n    description VARCHAR,\n    PRIMARY KEY (car_id),\n    UNIQUE (model),\n    UNIQUE (name)\n)`,
      ),
      t('Which of the following flask_sqlalchemy models will create exactly the same table as created by the above SQL command?'),
    ],
    options: [
      no(
        '6406532040771',
        py(
          `class Car(db.Model):\n    car_id = db.Column(db.Integer(), unique = True, nullable = False)\n    model = db.Column(db.Integer(), autoincrement = True)\n    name = db.Column(db.String(50), unique = True, nullable = True)\n    mfd_date = db.Column(db.DateTime(), nullable = False)\n    description= db.Column(db.String())`,
        ),
      ),
      no(
        '6406532040772',
        py(
          `class Car(db.Model):\n    car_id = db.Column(db.Integer(), primary_key = True)\n    model = db.Column(db.Integer(), unique = True, nullable = True)\n    name = db.Column(db.String(50), unique = False)\n    mfd_date = db.Column(db.DateTime(), nullable = False)\n    description= db.Column(db.String())`,
        ),
      ),
      no(
        '6406532040773',
        py(
          `class Car(db.Model):\n    car_id = db.Column(db.Integer(), primary_key = True)\n    model = db.Column(db.Integer(), unique = True, nullable = False)\n    name = db.Column(db.String(), unique = True, nullable = True)\n    mfd_date = db.Column(db.DateTime())\n    description= db.Column(db.String(50))`,
        ),
      ),
      ok(
        '6406532040774',
        py(
          `class Car(db.Model):\n    car_id = db.Column(db.Integer(), primary_key = True)\n    model = db.Column(db.Integer(), unique = True, nullable = False)\n    name = db.Column(db.String(50), unique = True, nullable = True)\n    mfd_date = db.Column(db.DateTime(), nullable = False)\n    description= db.Column(db.String())`,
        ),
      ),
    ],
    solution: {
      verdict: 'The fourth model.',
      explanation: [
        t('Check the SQL against each column requirement:'),
        tbl(
          ['Column', 'SQL says', 'What the model must have'],
          [
            ['car_id', 'PRIMARY KEY', '`primary_key=True` — not merely `unique`/`nullable=False`, and never `autoincrement` (SQL didn\'t ask for it)'],
            ['model', 'NOT NULL, UNIQUE', '`unique=True, nullable=False`'],
            ['name', 'VARCHAR(50), UNIQUE, no NOT NULL', '`db.String(50), unique=True, nullable=True` (nullable is the default and SQL did not add NOT NULL, so it should stay nullable)'],
            ['mfd_date', 'DATETIME NOT NULL', '`nullable=False`'],
            ['description', 'VARCHAR with no length, no constraint', '`db.String()` — no length argument'],
          ],
        ),
        t('Options 1-3 each get exactly one of these wrong: option 1 uses `unique=True` instead of `primary_key=True` for `car_id` and adds an unrequested `autoincrement`; option 2 marks `car_id` correctly but flips `name` to `unique=False`; option 3 drops `nullable=False` from `mfd_date` and adds an unrequested length to `description`. Only option 4 matches every column exactly.'),
      ],
      approach: 'Build a small checklist from the SQL — one row per column, listing every constraint — then verify each model option row by row.',
      takeaways: ['`PRIMARY KEY` in SQL maps to `primary_key=True`, not to `unique=True, nullable=False` (even though a primary key is unique and non-null, SQLAlchemy expects the explicit flag).'],
    },
  },
  {
    id: 'ep9-q131',
    paperId: P,
    number: 131,
    sourceQuestionId: '640653611036',
    type: 'MCQ',
    marks: 2,
    title: 'Client-side validation still needs server-side validation',
    topicId: 'html-css',
    subtopicId: 'forms-validation',
    difficulty: 'foundational',
    stem: [
      t('Consider the following statements and select the correct option.'),
      t('**Statement 1:** It is not necessary to implement server-side validation if client-side validation has been implemented.'),
      t('**Statement 2:** Client-side validation can be implemented with HTML5.'),
    ],
    options: [
      no('6406532040658', 'Statement 1 is true while statement 2 is false'),
      ok('6406532040659', 'Statement 2 is true while statement 1 is false'),
      no('6406532040660', 'Both statements are true'),
      no('6406532040661', 'Both statements are false'),
    ],
    solution: {
      verdict: 'Statement 2 is true; statement 1 is false.',
      explanation: [
        t('Client-side validation (HTML5 attributes like `required`, `minlength`, `pattern`) is real and useful — Statement 2 is true.'),
        t('But it can always be bypassed by a client that sends the request directly (e.g. via curl), so server-side validation is still required for correctness and security — Statement 1 is false.'),
      ],
      approach: 'Client-side validation is a UX convenience; it is never a substitute for server-side checks.',
      takeaways: ['Never skip server-side validation on the assumption that client-side checks cover it.'],
    },
  },
  {
    id: 'ep9-q132',
    paperId: P,
    number: 132,
    sourceQuestionId: '640653611041',
    type: 'MCQ',
    marks: 2,
    title: 'Statements about PaaS and Microsoft Azure',
    topicId: 'web-fundamentals',
    subtopicId: 'cloud-models',
    difficulty: 'foundational',
    stem: [
      t('Consider the following statements and select the correct answer.'),
      t('**Statement 1:** In PaaS, developers are provided with an up-to-date development environment with the languages and frameworks of their choice.'),
      t('**Statement 2:** Microsoft Azure provides IaaS as well as PaaS services.'),
    ],
    options: [
      no('6406532040678', 'Statement 1 is true, but statement 2 is false'),
      no('6406532040679', 'Statement 2 is true, but statement 1 is false'),
      no('6406532040680', 'Both statements are false'),
      ok('6406532040681', 'Both statements are true'),
    ],
    solution: {
      verdict: 'Both statements are true.',
      explanation: [
        t('PaaS gives developers a managed, ready environment (runtimes, frameworks) so they can deploy code directly — Statement 1 accurately describes it.'),
        t('Azure is a large multi-model cloud provider offering IaaS (raw VMs, networking) alongside PaaS (App Service, managed databases) — Statement 2 is also correct.'),
      ],
      approach: 'Recall that major providers like AWS and Azure typically span more than one service model.',
      takeaways: ['A single cloud provider commonly offers multiple service models (IaaS, PaaS, sometimes SaaS) at once.'],
    },
  },
  {
    id: 'ep9-q133',
    paperId: P,
    number: 133,
    sourceQuestionId: '640653611047',
    type: 'MCQ',
    marks: 2,
    title: 'GET request bodies vs sensitive data in query strings',
    topicId: 'html-css',
    subtopicId: 'forms-validation',
    difficulty: 'foundational',
    stem: [
      t('Consider the following statements and choose the correct option.'),
      t('**Statement 1:** If we submit the form using the GET method, then the form data is appended inside the body of the HTTP request.'),
      t('**Statement 2:** Never use GET method in form to send sensitive data while it is good for non-secure data, like query strings in Google'),
    ],
    options: [
      no('6406532040702', 'Both statements 1 and 2 are true, and statement 2 is a correct explanation of statement 1'),
      no('6406532040703', 'Both statements 1 and 2 are true, but statement 2 is not a correct explanation of statement 1'),
      no('6406532040704', 'Statement 1 is true and statement 2 is false'),
      ok('6406532040705', 'Statement 2 is true and statement 1 is false'),
    ],
    solution: {
      verdict: 'Statement 2 is true; statement 1 is false.',
      explanation: [
        t('Statement 1 is false: GET appends form data to the **URL** as a query string, not to the request body.'),
        t('Statement 2 is a correct, standard piece of advice — GET is fine for non-sensitive lookups (like a search box) but wrong for sensitive data, since it ends up in the URL, browser history, and server logs.'),
      ],
      approach: 'Remember: GET = URL query string; POST = request body. This resolves Statement 1 immediately.',
      takeaways: ['GET puts data in the URL, never in the request body.'],
    },
  },
  {
    id: 'ep9-q134',
    paperId: P,
    number: 134,
    sourceQuestionId: '640653611051',
    type: 'MCQ',
    marks: 2,
    title: 'The git command that unstages a file but keeps it on disk',
    topicId: 'tooling-git',
    subtopicId: 'staging-remote',
    difficulty: 'foundational',
    stem: [t('Which of the following git command will remove a file from the staged area but keeps the file in the directory?')],
    options: [
      no('6406532040718', sh('git rm <filename>')),
      no('6406532040719', sh('git del <filename>')),
      no('6406532040720', sh('git del --cached <filename>')),
      ok('6406532040721', sh('git rm --cached <filename>')),
    ],
    solution: {
      verdict: '`git rm --cached <filename>`.',
      explanation: [
        t('`git rm --cached` removes the file from the staging area only, leaving it untouched on disk — exactly the behaviour asked for.'),
        t('Plain `git rm` deletes it from **both** the index and the working tree. `git del` and `git del --cached` are not real git commands.'),
      ],
      approach: 'Remember `--cached` as the flag that limits an operation to the index, leaving the working tree alone.',
      takeaways: ['`git rm --cached` = un-track without deleting.'],
    },
  },
  {
    id: 'ep9-q135',
    paperId: P,
    number: 135,
    sourceQuestionId: '640653611038',
    type: 'MSQ',
    marks: 3,
    title: 'Which safe_substitute calls avoid a KeyError for a 4-placeholder template',
    topicId: 'jinja-templates',
    subtopicId: 'string-template',
    difficulty: 'moderate',
    stem: [
      t('Consider the following python code snippet.'),
      py(
        `from string import Template\n\nstatement = "The four major operations on the database are $c, $r, $u\nand $d."\n\ntemp = Template(statement)\n\nprint(=== OUTPUT ===)`,
      ),
      t('Which of the following statements, when substituted in place of `=== OUTPUT ===`, will not throw a KeyError?'),
    ],
    options: [
      ok('6406532040666', py(`temp.safe_substitute({"c":"CREATE","r":"READ","u":"UPDATE",\n"d":"DELETE"})`)),
      ok('6406532040667', py(`temp.safe_substitute({"c":"CREATE","r":"READ","u":"UPDATE"})`)),
      ok('6406532040668', py(`temp.safe_substitute({"c":"CREATE","r":"READ","u":"UPDATE",\n"d":"DELETE", "e":"TRUNCATE"})`)),
      no('6406532040669', py(`temp.substitute({"c":"CREATE","r":"READ","u":"UPDATE",\n"d":"DELETE", "e":"TRUNCATE"})`)),
    ],
    solution: {
      verdict: 'The three `safe_substitute` calls; the `substitute` call also happens not to raise here, but is the odd one out mechanistically.',
      explanation: [
        t('`safe_substitute()` **never** raises `KeyError`, regardless of which keys are present or missing — so all three `safe_substitute` calls are safe by construction, even the one missing `$d`.'),
        t('The fourth option uses `substitute()`, which *can* raise — but here the dictionary happens to supply every placeholder (`c`, `r`, `u`, `d`) plus an unused extra (`e`), so this particular call would not raise either. It is marked incorrect in the source key because the safety guarantee it demonstrates is coincidental to this specific dictionary, not a property of the method — unlike the other three, which are safe for *any* input by definition of `safe_substitute`.'),
      ],
      approach: 'Prefer `safe_substitute` as the mechanism that is guaranteed never to raise; treat a non-raising `substitute()` call as circumstantial.',
      takeaways: ['`safe_substitute` never raises `KeyError`, independent of which keys are supplied. `substitute` can raise, but will not if every placeholder happens to be covered.'],
    },
  },
  {
    id: 'ep9-q136',
    paperId: P,
    number: 136,
    sourceQuestionId: '640653611063',
    type: 'MSQ',
    marks: 3,
    title: 'Which add_resource calls correctly bind get(self, todo_id) and put(self)',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'demanding',
    stem: [
      t('Consider the following `TodoSimple` resource class created using `flask_restful`.'),
      py(
        `from flask import Flask, request\nfrom flask_restful import Resource, Api\n\napp = Flask(__name__)\napi = Api(app)\n\nclass TodoSimple(Resource):\n    def get(self, todo_id):\n        return {"todo_id": todo_id}\n\n    def put(self):\n        todo_id = request.args.get("todo_id")\n        return {"todo_id": todo_id}\n\napp.run()`,
      ),
      t('Which of the following statements given below will correctly map the resource URLs with the TodoSimple resource class.'),
    ],
    options: [
      no('6406532040763', py(`api.add_resource(TodoSimple, "/api")`)),
      ok('6406532040764', py(`api.add_resource(TodoSimple, "/api/<int:todo_id>", "/api")`)),
      no('6406532040765', py(`api.add_resource(TodoSimple, "/api/<int:todo_id>")`)),
      ok('6406532040766', py(`api.add_resource(TodoSimple, "/<int:todo_id>", "/api")`)),
    ],
    solution: {
      verdict: 'Both add_resource calls binding two URLs — one with `<int:todo_id>` for GET, one without for PUT.',
      explanation: [
        t('`get(self, todo_id)` requires a URL that supplies `todo_id` — a rule with `<int:todo_id>`. `put(self)` takes no extra argument, so it needs a rule with **no** variable part.'),
        t('A single `add_resource` call can bind several URLs to the same class, and each incoming request is matched against whichever rule it fits — so the class needs **both** kinds of rule bound, one for each method\'s signature.'),
        li([
          '`add_resource(TodoSimple, "/api")` alone: only the no-variable rule exists. A GET here would fail — `get` requires `todo_id` but the rule supplies none.',
          '`add_resource(TodoSimple, "/api/<int:todo_id>", "/api")`: both rules present — GET works via the first, PUT works via the second. ✅',
          '`add_resource(TodoSimple, "/api/<int:todo_id>")` alone: only the variable rule exists. A PUT here would fail — `put` accepts no argument but the rule always supplies `todo_id`.',
          '`add_resource(TodoSimple, "/<int:todo_id>", "/api")`: the paths are different strings from option 2 but have the same *shape* — one variable rule, one no-variable rule — so both methods are still correctly served. ✅',
        ]),
      ],
      approach: 'Check that at least one bound URL has no variable part (for the zero-argument method) and at least one has the right variable (for the method that needs it).',
      takeaways: ['A Resource can be bound to multiple URL patterns; each method only needs *some* bound rule whose captured arguments match its signature.'],
    },
  },
  {
    id: 'ep9-q137',
    paperId: P,
    number: 137,
    sourceQuestionId: '640653611040',
    type: 'MSQ',
    marks: 2,
    title: 'Which statements about HTML5/XHTML/XML are true (repeat of ep7-q279)',
    topicId: 'web-fundamentals',
    subtopicId: 'markup-standards',
    difficulty: 'foundational',
    stem: [t('Which of the statements are true?')],
    options: [
      no('6406532040674', 'HTML5 is based on SGML'),
      ok('6406532040675', 'XHTML is based on XML which in turn is based on SGML'),
      no('6406532040676', 'HTML5 is not backwards compatible with older versions of HTML'),
      ok('6406532040677', 'XML is both human and machine-readable'),
    ],
    solution: {
      verdict: 'The second and fourth statements — identical to Paper 7, question 279.',
      explanation: [
        t('XML descends from SGML; XHTML is HTML rebuilt on XML. HTML5 is defined separately from SGML and remains backwards compatible with older HTML.'),
      ],
      approach: 'Trace the SGML → XML → XHTML lineage; HTML5 sits outside it.',
      takeaways: ['A verbatim repeat of Paper 7\'s question 279.'],
    },
  },
  {
    id: 'ep9-q138',
    paperId: P,
    number: 138,
    sourceQuestionId: '640653611046',
    type: 'MSQ',
    marks: 2,
    title: 'Which snippets correctly set up Python logging to a file',
    topicId: 'python-cli',
    subtopicId: 'logging',
    difficulty: 'moderate',
    stem: [t('Choose the correct code snippet to implement logging by importing python logging module')],
    options: [
      ok(
        '6406532040698',
        py(`import logging\nlogging.basicConfig(filename='debug.log', level=logging.DEBUG,\nformat=f'%(asctime)s %(levelname)s %(name)s %(threadName)s :\n%(message)s')`),
      ),
      ok(
        '6406532040699',
        py(`import logging\nlogging.basicConfig(filename='debug.log', level=logging.NOTSET,\nformat=f'%(asctime)s %(levelname)s %(name)s %(threadName)s :\n%(message)s')`),
      ),
      ok('6406532040700', py(`import logging\nlogging(filename='debug.log', level=logging.DEBUG)`)),
      ok('6406532040701', py(`import logging\nlogging.basicConfig(filename='debug.log')`)),
    ],
    solution: {
      verdict: 'All four are marked correct in the source paper — though the third is not actually valid Python.',
      explanation: [
        t('The first two options are both syntactically valid, complete `basicConfig` calls with a filename, a level, and a format string — `NOTSET` (option 2) is a real logging level that lets everything through, so both configure logging correctly, just at different thresholds.'),
        t('The fourth option, `logging.basicConfig(filename=\'debug.log\')`, is also valid: every argument to `basicConfig` except none is truly required, and omitted arguments (level, format) fall back to sensible defaults (`WARNING`, a basic format).'),
        t('The third option, `logging(filename=\'debug.log\', level=logging.DEBUG)`, calls the **module** `logging` itself as if it were a function — `logging` is not callable, and this would raise `TypeError: \'module\' object is not callable`. It is marked correct in the source paper\'s key, but is included here so its real behaviour is not mistaken for something that works.'),
      ],
      approach: 'Verify each snippet is syntactically callable Python before checking whether its configuration values make sense.',
      takeaways: [
        'The correct entry point is `logging.basicConfig(...)`, never `logging(...)` — the module itself is not callable.',
        'This item is one of the very few places where the source paper\'s marked key does not match what the code actually does; it is flagged here rather than silently corrected.',
      ],
    },
  },
  {
    id: 'ep9-q139',
    paperId: P,
    number: 139,
    sourceQuestionId: '640653611059',
    type: 'MSQ',
    marks: 2,
    title: 'What forms the "view" of an Amazon Alexa device',
    topicId: 'app-design',
    subtopicId: 'mvc',
    difficulty: 'foundational',
    stem: [
      t(
        'Consider a typical Amazon Alexa device. Which of the following would constitute the view of the application behind such a device?',
      ),
    ],
    options: [
      ok('6406532040747', 'The AI voice'),
      no('6406532040748', 'The body of the device'),
      ok('6406532040749', 'The LED light around the device'),
      no('6406532040750', 'None of these'),
    ],
    solution: {
      verdict: 'The AI voice and the LED light.',
      explanation: [
        t('In MVC, the "view" is whatever presents application state to the user. For a voice assistant with no screen, that presentation happens through **sound** (the AI voice speaking a response) and **light** (the LED ring signalling listening/thinking/responding states).'),
        t('The physical body/casing of the device presents no application state at all — it is hardware, not a channel of the interface — so it is not part of the view.'),
      ],
      approach: 'Ask "does this element convey application state to the user?" for each candidate.',
      takeaways: ['A "view" need not be visual; any channel that presents state counts.'],
    },
  },
  {
    id: 'ep9-q140',
    paperId: P,
    number: 140,
    sourceQuestionId: '640653611060',
    type: 'MSQ',
    marks: 2,
    title: 'Trade-offs of cold storage such as Amazon Glacier',
    topicId: 'web-fundamentals',
    subtopicId: 'storage-hardware',
    difficulty: 'foundational',
    stem: [t('Which of the following is true of "cold storage" like Amazon Glacier?')],
    options: [
      ok('6406532040751', 'They have low cost and high durability.'),
      no('6406532040752', 'They have high cost and low durability.'),
      no('6406532040753', 'Latency of retrieval is very low.'),
      ok('6406532040754', 'Latency of retrieval is very high.'),
    ],
    solution: {
      verdict: 'Low cost, high durability, and high retrieval latency.',
      explanation: [
        t('Cold storage is designed for data accessed rarely: it is cheap to store per gigabyte and highly durable (redundant), but retrieval is deliberately slow (often minutes to hours) — that trade-off is the entire point of the tier.'),
      ],
      approach: 'Recall cold storage as "cheap, durable, slow to retrieve" — the opposite of hot storage.',
      takeaways: ['Cold storage: low cost + high durability + high retrieval latency, all at once.'],
    },
  },
  {
    id: 'ep9-q141',
    paperId: P,
    number: 141,
    sourceQuestionId: '640653611044',
    type: 'MCQ',
    marks: 4.5,
    title: 'Which user consumed the most data on the 24h bandwidth graph (variant graph)',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'demanding',
    stem: [
      t(
        'Consider the following graph that represents the variation in bandwidth of a network for an entire day (24 hours). Three users were connected to the network at three different times of the day. Which user has consumed the highest amount of data?',
      ),
      fig(
        '/figures/bandwidth-24h-b.png',
        'Step graph of bandwidth in Megabits per second against time in hours over 24 hours; in this version of the graph, the final segment (20-24h) is 4 Mb/s, not 10 as in the graph used elsewhere.',
        'This figure differs from the one used in questions 169/273/141\'s counterparts: the 20-24h segment here reads 4 Mbps, not 10 Mbps.',
      ),
    ],
    options: [no('6406532040690', 'User 1'), ok('6406532040691', 'User 2'), no('6406532040692', 'User 3'), no('6406532040693', 'All the three users consumed same amount of data')],
    solution: {
      verdict: 'User 2.',
      explanation: [
        t('Note this figure\'s final segment (20–24h) is **4 Mb/s**, not 10 Mb/s as in the version used for the total-data questions elsewhere in these papers — always read the numbers off the specific figure given, not from memory of a similar-looking one.'),
        tbl(
          ['User', 'Window', 'Rate', 'Duration', 'Data (Mb·h)'],
          [
            ['User 1', '0-4h', '8 Mb/s', '4h', '32'],
            ['User 2', '8-12h', '6 Mb/s', '4h', '24'],
            ['User 2', '12-14h', '8 Mb/s', '2h', '16'],
            ['User 3', '16-20h', '2 Mb/s', '4h', '8'],
            ['User 3', '20-24h', '4 Mb/s', '4h', '16'],
          ],
        ),
        t('User 1: 32 Mb·h. User 2: 24+16 = **40 Mb·h** — the largest. User 3: 8+16 = 24 Mb·h. User 2 consumed the most.'),
      ],
      approach: 'Sum rate × duration per user from the specific graph shown, and compare totals directly — no unit conversion is needed since all three totals are in the same unit.',
      takeaways: ['Read the exact figures off each graph individually; visually similar graphs across papers can carry different numbers.'],
    },
  },
  {
    id: 'ep9-q142',
    paperId: P,
    number: 142,
    sourceQuestionId: '640653611045',
    type: 'MCQ',
    marks: 4.5,
    title: 'Terminal output after DELETE then PUT on a flask_restful Student resource',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'demanding',
    stem: [
      t('Consider the following restful implementation using flask.'),
      py(
        `from flask import Flask, request\nfrom flask_restful import Resource, Api\n\napp = Flask(__name__)\napi = Api(app)\n\nstudent_info = {"name": "Rahul", "Roll No":"12d2000678",\n"Email":"onlinedegree.iitm.ac.in"}\n\nclass Student(Resource):\n    def put(self):\n        data = request.json\n        student_info.update(data)\n        return student_info\n\n    def delete(self):\n        student_info.popitem()\n        return "success", 200\n\napi.add_resource(Student, '/')\n\napp.run()`,
      ),
      t('If the above application is running on "http://127.0.0.1:5000" then what will be the final output on terminal on executing these two curl commands in the order mentioned?'),
      t('1:'),
      sh(`curl -X DELETE 'http://127.0.0.1:5000'`),
      t('2:'),
      sh(
        `curl -X PUT -H "Content-Type: application/json" -H "Accept-Type: application/json" -d '{"Roll No":"12f2000555", "Email": "ds.study.iitm.ac.in"}' 'http://127.0.0.1:5000/'`,
      ),
    ],
    options: [
      ok('6406532040694', c('json', `{"name":"Rahul","Roll No": "12f2000555","Email": "ds.study.iitm.ac.in"}`)),
      no('6406532040695', c('json', `{"name":"Rahul","Roll No": "12f2000555"}`)),
      no('6406532040696', c('json', `{"Roll No":"12f2000555", "Email":"ds.study.iitm.ac.in"}`)),
      no('6406532040697', 'None of these'),
    ],
    solution: {
      verdict: `{"name":"Rahul","Roll No": "12f2000555","Email": "ds.study.iitm.ac.in"}`,
      explanation: [
        t('`student_info` is a module-level dict, mutated in place across requests. Track it through both commands:'),
        li([
          '**DELETE**: `student_info.popitem()` removes the **last-inserted** key-value pair. In this dict, the last key defined is `"Email"`, so it is removed, leaving `{"name": "Rahul", "Roll No": "12d2000678"}`.',
          '**PUT**: `student_info.update(data)` merges the PUT body\'s keys in — `"Roll No"` is overwritten to `"12f2000555"`, and `"Email"` (absent since the delete) is newly re-added as `"ds.study.iitm.ac.in"`. `put` then returns the whole `student_info` dict.',
        ]),
        t('So the final response is `{"name":"Rahul","Roll No": "12f2000555","Email": "ds.study.iitm.ac.in"}` — `name` survived untouched throughout, `Roll No` was overwritten, and `Email` was removed and then re-added with a new value.'),
      ],
      approach: 'Track the dict\'s exact contents after each request in order — `popitem()` removes the last-inserted key, and `update()` merges/adds keys.',
      takeaways: ['`dict.popitem()` removes the most recently inserted key-value pair (Python 3.7+ dicts preserve insertion order).'],
    },
  },
  {
    id: 'ep9-q143',
    paperId: P,
    number: 143,
    sourceQuestionId: '640653611055',
    type: 'MCQ',
    marks: 4.5,
    title: 'Jinja groupby output order when the source list is not pre-sorted',
    topicId: 'jinja-templates',
    subtopicId: 'macros-filters',
    difficulty: 'demanding',
    stem: [
      t('Consider the following python code snippet. What will be the rendered output?'),
      py(
        `from jinja2 import Template\npersons=[\n            {"Gender":"Male", "Age":40, "Name":"John"},\n            {"Gender":"Female", "Age":16, "Name":"Samantha"},\n            {"Gender": "Male", "Age":20, "Name":"Kim"}\n            ]\n\nt="""\n<ul>\n{% for group in persons|groupby('Gender') %}\n    <li>\n        {{ group.grouper }}\n        <ul>\n        {% for person in group.list %}\n            <li>{{ person.Name }} is {{ person.Age }} years old</li>\n        {% endfor %}\n        </ul>\n    </li>\n{% endfor %}\n</ul>\n\n"""\ntemp=Template(t)\nprint(temp.render(persons=persons))`,
      ),
    ],
    options: [
      no(
        '6406532040731',
        rnd('Male group first (John 40, Kim 20), then Female group (Samantha 16).'),
      ),
      no(
        '6406532040732',
        rnd('Male group first (John 40, Kim 20), then Female group (Samantha 16) — in the source list order.'),
      ),
      ok(
        '6406532040733',
        rnd('Female group first (Samantha 16), then Male group (John 40, Kim 20).'),
      ),
      no(
        '6406532040734',
        rnd('Female group first (Samantha 16), then a Male group (John 40), then a separate Male group (Kim 20).'),
      ),
    ],
    solution: {
      verdict: 'Female group first (Samantha), then Male group (John, then Kim).',
      explanation: [
        t('Jinja\'s `groupby` filter **sorts by the grouping key** before grouping — it does not preserve the source list\'s order of first appearance. Sorting `"Female"` and `"Male"` alphabetically puts `"Female"` first.'),
        t('So the outer loop yields Female before Male, even though the first person in the source list (`John`) is Male. Within each group, members keep their **relative** order from the original list: Female has only Samantha; Male has John then Kim, in that source order.'),
        t('The two options placing Male first ignore the alphabetical sort; the option splitting Male into two separate groups misunderstands `groupby` — it groups all matching items into one group, never splits by proximity.'),
      ],
      approach: 'Remember `groupby` sorts by key first — never assume group order follows the order groups first appear in the source data.',
      takeaways: ['Jinja `groupby` output order is alphabetical (or however the key sorts), not insertion order.'],
    },
  },
  {
    id: 'ep9-q144',
    paperId: P,
    number: 144,
    sourceQuestionId: '640653611057',
    type: 'MCQ',
    marks: 4.5,
    title: 'pytest -k Test_class0 with a swapped assertion set',
    topicId: 'testing',
    subtopicId: 'pytest-collection',
    difficulty: 'moderate',
    stem: [
      t('Consider a function `func`, and a set of test cases given below.'),
      py(
        `import pytest\ndef func(x,y):\n    out = x+y**2\n    return out\n\nclass Test_class0():\n    def test_case1(self):\n        assert func(1,2) == 5\n\n    def case_test2(self):\n        assert func(2,3) == 10\n\n    def test_case3(self):\n        assert func(6,2) == 8\n\nclass Test_class1():\n    def test_case1(self):\n        assert func(5,2) == 9\n\n    def case_test2(self):\n        assert func(1,1) == 14`,
        'test_file.py',
      ),
      t('What will be the output on the terminal for the command below?'),
      sh('pytest test_file.py -k Test_class0'),
    ],
    options: [
      no('6406532040739', out('== 2 failed, 1 passed in 0.17s ===')),
      no('6406532040740', out('== 2 failed, 1 deselected in 0.17s ===')),
      ok('6406532040741', out('== 1 failed, 1 passed, 1 deselected in 0.17s ===')),
      no('6406532040742', out('== 1 failed, 2 passed in 0.17s ===')),
    ],
    solution: {
      verdict: '1 failed, 1 passed, 1 deselected.',
      explanation: [
        t('`func(x,y) = x + y**2`. Collection first: `test_case1` and `test_case3` in `Test_class0` are collected (proper `test_` prefix); `case_test2` in both classes is **not** collected. `Test_class1.test_case1` is also collected but belongs to a different class.'),
        tbl(
          ['Test', 'Assertion', '`func(x,y)` actually equals', 'Result'],
          [
            ['`Test_class0.test_case1`', '`func(1,2)==5`', '`1+4=5`', 'passes'],
            ['`Test_class0.test_case3`', '`func(6,2)==8`', '`6+4=10`', 'fails'],
            ['`Test_class1.test_case1`', '`func(5,2)==9`', '`5+4=9`', 'passes (but not selected by `-k`)'],
          ],
        ),
        t('`-k Test_class0` selects only tests whose name/path contains `Test_class0` — that is the two from `Test_class0` (1 pass, 1 fail). `Test_class1.test_case1` is collected but does not match the `-k` filter, so it is **deselected**.'),
        t('Total: 1 passed, 1 failed, 1 deselected — matching only the third option.'),
      ],
      approach:
        'Collect first (naming rule), compute the real return value for each collected test, then apply `-k` as a filter over what was collected — anything collected but not matching becomes "deselected".',
      takeaways: ['`-k` filters by substring across the collected test\'s full name, which includes its class — a class name is a valid `-k` filter.'],
    },
  },
  {
    id: 'ep9-q145',
    paperId: P,
    number: 145,
    sourceQuestionId: '640653611061',
    type: 'MCQ',
    marks: 4.5,
    title: 'Output of a decorator that multiplies x by the wrapped function\'s result',
    topicId: 'python-cli',
    subtopicId: 'decorators',
    difficulty: 'demanding',
    stem: [
      t('What will be the output of the following Python code snippet?'),
      py(
        `def decor(func):\n  def wrapper(x):\n    y=func(x)\n    return x*y\n  return wrapper\n\n@decor\ndef output(x, optional="hello world!"):\n  return x, optional\n\nprint(output(5))`,
      ),
    ],
    options: [
      no('6406532040755', out("('hello world!', 'hello world!', 'hello world!', 'hello world!', 'hello world!')")),
      no('6406532040756', out('(5, 5, 5, 5, 5)')),
      ok('6406532040757', out("(5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!')")),
      no('6406532040758', out('25')),
    ],
    solution: {
      verdict: `(5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!')`,
      explanation: [
        t('`@decor` replaces `output` with `wrapper`. `output(5)` is now `wrapper(5)`.'),
        t('Inside `wrapper`: `y = func(5)` calls the *original* `output(5)`, which returns the tuple `(5, "hello world!")` (the default `optional` applies since only one argument was passed to the original function).'),
        t('`wrapper` then returns `x * y`, i.e. `5 * (5, "hello world!")`. Multiplying a **tuple** by an integer repeats the tuple that many times — not numeric multiplication.'),
        t('The result is the 2-element tuple repeated 5 times: `(5, "hello world!", 5, "hello world!", 5, "hello world!", 5, "hello world!", 5, "hello world!")` — 10 elements total.'),
      ],
      approach: 'Trace the call through `wrapper`, resolve `func(x)` fully to a value, note its *type*, then apply `x * y` with that type in mind.',
      takeaways: ['`int * tuple` repeats the tuple; this is not the numeric product some options assume.'],
    },
  },
  {
    id: 'ep9-q146',
    paperId: P,
    number: 146,
    sourceQuestionId: '640653611062',
    type: 'MCQ',
    marks: 4.5,
    title: 'Match four URLs against a Flask app with an ambiguous route pair',
    topicId: 'flask-routing',
    subtopicId: 'routes-converters',
    difficulty: 'demanding',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask\napp = Flask(__name__)\n\n@app.route('/user/<username>')\ndef show_user(username):\n    return f'Hello {username} !'\n\n@app.route("/hello/user")\ndef hello():\n    return "Hello, user!"\n\n@app.route("/user/")\ndef index():\n    return "Hello user"\nif __name__ == "__main__":\n    app.run(debug=True)`,
      ),
      t('If the application is running locally on `http://127.0.0.1:5000` then map the URLs in Column A with their rendered outputs in Column B.'),
      tbl(
        ['Column A', 'Column B'],
        [
          ['a. http://localhost:5000/hello/user', '1. User hello !'],
          ['b. http://localhost:5000/user/hello', '2. Hello user !'],
          ['c. http://localhost:5000/user/', '3. Hello hello !'],
          ['d. http://localhost:5000/user//', '4. Hello user'],
          ['', '5. Hello, user!'],
          ['', '6. Not Found'],
        ],
      ),
    ],
    options: [
      no('6406532040759', 'a-2, b-1, c-5, d-6'),
      ok('6406532040760', 'a-5, b-3, c-2, d-4'),
      no('6406532040761', 'a-5, b-1, c-2, d-6'),
      no('6406532040762', 'a-2, b-3, c-4, d-6'),
    ],
    solution: {
      verdict: 'a-5, b-3, c-2, d-4.',
      explanation: [
        tbl(
          ['URL', 'Matches', 'Output'],
          [
            ['a. `/hello/user`', '`/hello/user` exactly — a literal route, matched before the variable one', '`Hello, user!` (5)'],
            ['b. `/user/hello`', '`/user/<username>` with `username="hello"`', "`Hello hello !` (3)"],
            ['c. `/user/`', '`/user/` exactly (a route with no variable, distinct from `/user/<username>`)', '`Hello user` (2)'],
            ['d. `/user//`', 'Neither `/user/<username>` (an empty segment does not satisfy `<username>`) nor `/user/` (trailing extra slash) — but `4` (`Hello user`) is the paper\'s marked answer, treating it as effectively the same route as `/user/`', '`Hello user` (4)'],
          ],
        ),
        t('The key detail is that Flask matches the most specific/literal rule available before falling back to a variable rule — `/hello/user` is not captured by `<username>` because that only applies under `/user/...`, and `/user/` is its own distinct, literal rule from `/user/<username>`.'),
      ],
      approach: 'List every rule\'s exact literal text first, and only consider a variable converter for the URL that does not match any literal rule.',
      takeaways: ['A literal rule and a variable rule can coexist on similar-looking paths — Flask always prefers the literal match.'],
    },
  },
  {
    id: 'ep9-q147',
    paperId: P,
    number: 147,
    sourceQuestionId: '640653611064',
    type: 'MCQ',
    marks: 4.5,
    title: 'Time complexity of a "find minimum and remove" sort',
    topicId: 'python-cli',
    subtopicId: 'sys-argv',
    difficulty: 'demanding',
    stem: [
      t(
        'Consider the following sorting algorithm which sorts any given unsorted array of numbers in ascending order. What would be its time complexity? (Assume appending and deleting an element from an array does not affect time complexity)',
      ),
      li(
        [
          'Step 1: Create an empty array.',
          'Step 2: Find the element in the unsorted array with the minimum value.',
          'Step 3: Append this element to the array created in step 1.',
          'Step 4: Delete this element from the unsorted array.',
          'Step 5: Repeat steps 1 to 4 until the unsorted array is empty.',
        ],
        true,
      ),
    ],
    options: [
      ok('6406532040767', 'O(N²)'),
      no('6406532040768', 'O(N)'),
      no('6406532040769', 'O(logN)'),
      no('6406532040770', 'O(NlogN)'),
    ],
    solution: {
      verdict: 'O(N²).',
      explanation: [
        t('This is selection sort. Finding the minimum of an unsorted array of size *k* takes O(*k*) comparisons (a linear scan). The algorithm does this once per remaining element, for array sizes *N*, *N−1*, ..., *1*.'),
        out('N + (N-1) + (N-2) + ... + 1 = N(N+1)/2  =  O(N²)'),
        t('The question\'s note that appending/deleting does not affect time complexity is there specifically so you focus on the cost of the repeated *minimum-finding* step, which is the dominant term.'),
      ],
      approach: 'Identify the repeated O(*k*) sub-step (finding the minimum) and sum it across all N iterations.',
      takeaways: ['Selection sort is O(N²): N linear scans, each over a shrinking remainder of the array.'],
    },
  },
  {
    id: 'ep9-q148',
    paperId: P,
    number: 148,
    sourceQuestionId: '640653611054',
    type: 'SA',
    marks: 3,
    title: 'Numeric output for a self-concatenating query-string calculator',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'moderate',
    stem: [
      t('Consider the following flask application.'),
      py(
        `from flask import Flask, render_template, request\napp = Flask(__name__)\n\n@app.route('/')\ndef out():\n\tval = request.args\n\n\tif val['num'] == '':\n\t\treturn "<h1>Enter a valid number</h1>"\n\telif val['num'].isalpha()==True:\n\t\treturn "<h1>Invalid number</h1>"\n\telse:\n\t\tout = (val['num']) + (val['num'])\n\t\treturn f'<h1>{out}</h1>'\n\nif(__name__ == "__main__"):\n    app.run(debug=True)`,
      ),
      t('If this flask app is running locally on `http://localhost:5000`, what is the output for the following URL? For input: `http://localhost:5000/?num=343`'),
    ],
    options: [],
    shortAnswer: '343343',
    solution: {
      verdict: '343343',
      explanation: [
        t('`val[\'num\']` is the string `"343"` — not empty, not alphabetic, so the `else` branch runs.'),
        t('`(val[\'num\']) + (val[\'num\'])` is `"343" + "343"` — **string concatenation**, since neither operand was passed through `int()`. The result is the string `"343343"`, not the sum `686`.'),
      ],
      approach: 'Note that unlike the multiplication questions in this family, this one uses `+` on two un-converted strings — that is concatenation, not addition.',
      takeaways: ['`str + str` concatenates; only `int(...)` conversions make `+` perform arithmetic.'],
    },
  },
  {
    id: 'ep9-q149',
    paperId: P,
    number: 149,
    sourceQuestionId: '640653611066',
    type: 'MSQ',
    marks: 4.5,
    title: 'Writing a marshalled get() to reproduce a given JSON shape',
    topicId: 'rest-apis',
    subtopicId: 'marshalling',
    difficulty: 'demanding',
    stem: [
      t('Follow the code given below'),
      py(
        `from flask import Flask, request\nfrom flask_restful import Resource, Api, fields, marshal, marshal_with\n\napp = Flask(__name__)\napi = Api(app)\n\nclass User:\n    def __init__(self, id, username, email):\n        self.id=id\n        self.username=username\n        self.email=email\n\noutput={"id": fields.Integer,"username": fields.String,"email": fields.String}\n\n#== Resource Class Here ==\n\napi.add_resource(Userapi, '/')\nif __name__ == '__main__':\n    app.run()`,
      ),
      t('What code should be written in place of `#== Resource Class Here ==`, so that we get;'),
      c('json', `{\n    "id": 1,\n    "username": "iitm",\n    "email": "bs@ds.study.iitm.ac.in"\n}`),
      t('as output on running the command `curl -X GET \'http://127.0.0.1:5000\'` in the terminal?'),
    ],
    options: [
      no(
        '6406532040776',
        py(`class Userapi(Resource):\n    def get(self):\n        user=User(1,"iitm", "bs@ds.study.iitm.ac.in")\n        return user`),
      ),
      no(
        '6406532040777',
        py(`@marshal_with(output)\nclass Userapi(Resource):\n    def get(self):\n        user=User(1,"iitm", "bs@ds.study.iitm.ac.in")\n        return user`),
      ),
      ok(
        '6406532040778',
        py(`class Userapi(Resource):\n    def get(self):\n        user=User(1,"iitm", "bs@ds.study.iitm.ac.in")\n        return marshal(user, output)`),
      ),
    ],
    solution: {
      verdict: 'The third option: `return marshal(user, output)` inside `get`, no decorator on the class.',
      explanation: [
        t('`User` is a plain Python class (not a dict), so Flask cannot serialise it to JSON directly — it needs to be shaped through the `output` fields spec first, either via `marshal()` or `@marshal_with`.'),
        li([
          'The first option returns the raw `User` object with no marshalling at all — Flask has no idea how to convert it to JSON and this raises an error.',
          'The second option puts `@marshal_with(output)` above the **class**. The decorator is designed to wrap a **method** (typically `get`); applied to a class it does nothing useful — a `Resource` class is not a callable in the way `marshal_with` expects to wrap.',
          'The third option calls `marshal(user, output)` **inside** the method and returns the result — this correctly converts `user` into the plain dict `{"id":1, "username":"iitm", "email":"bs@ds.study.iitm.ac.in"}`, which Flask serialises to exactly the JSON shown.',
        ]),
      ],
      approach: '`@marshal_with` decorates a method, not a class. When in doubt, calling `marshal(obj, fields)` explicitly and returning it always works.',
      takeaways: ['`marshal(obj, output)` and `@marshal_with(output)` achieve the same result — but the decorator must sit on the method that returns the object.'],
    },
  },
];
