import type { Comprehension, Question } from '../types';
import { c, li, no, ok, out, py, sh, t, tbl } from '../dsl';

const P = 'pr1';

export const pr1Comprehensions: Comprehension[] = [
  {
    id: 'pr1-c1',
    paperId: P,
    title: 'A course-lookup Flask app with nested request-arg validation',
    range: '28 to 29',
    stem: [
      t('Consider the following Flask application.'),
      py(
        `from flask import Flask, abort, request\napp = Flask(__name__)\n\ncourses = {\n    "IT2001": "Web Development",\n    "IT2002": "Database Systems",\n    "IT2003": "Software Engineering",\n    "IT2004": "Data Structures"\n}\n\n@app.route('/course')\ndef get_course():\n    course_id = request.args.get('id')\n    level = request.args.get('level', 'beginner')\n\n    if not course_id:\n        abort(400, "Bad Request: Course ID is required")\n\n    if course_id not in courses:\n        abort(404, "Not Found: Course does not exist")\n    return f'<h2>{courses[course_id]} - Level: {level.title()}</h2>'\n\n@app.route('/search')\ndef search_courses():\n    query = request.args.get('q')\n    min_length = int(request.args.get('min', 3))\n    if not query or len(query) < min_length:\n        abort(422, "Unprocessable Entity: Query too short")\n\n    results = [name for name in courses.values() if query.lower() in name.lower()]\n    if not results:\n        return '<p>No courses found</p>'\n\n    return f'<ul>{"".join([f"<li>{course}</li>" for course in results])}</ul>'\n\napp.run(debug=True)`,
      ),
    ],
  },
  {
    id: 'pr1-c2',
    paperId: P,
    title: 'A Flask-RESTful student management API',
    range: '31 to 32',
    stem: [
      t('Consider the following Flask-RESTful resource class for a student management system:'),
      py(
        `class StudentResource(Resource):\n    def get(self, student_id=None):\n        if student_id:\n            return {"message": "Student details", "id": student_id}, 200\n        return {"message": "All students"}, 200\n\n    def post(self):\n        parser = reqparse.RequestParser()\n        parser.add_argument('name', required=True, help='Name is required')\n        parser.add_argument('age', type=int, required=True, help='Age is required')\n        args = parser.parse_args()\n        return {"message": "Student created", "data": args}, 201\n\n    def put(self, student_id):\n        return {"message": "Student updated", "id": student_id}, 200\n\n    def delete(self, student_id):\n        return {"message": "Student deleted", "id": student_id}, 204\n\nclass CourseResource(Resource):\n    def get(self, course_code):\n        return {"course": course_code, "status": "active"}, 200\n\n    def post(self, course_code, student_id):\n        return {\n            "message": "Student enrolled",\n            "course": course_code,\n            "student_id": student_id\n        }, 201\n\napi.add_resource(StudentResource, '/students',\n                 '/students/<int:student_id>')\napi.add_resource(CourseResource, '/courses/<string:course_code>',\n                 '/courses/<string:course_code>/enroll/<int:student_id>')\n\nif __name__ == '__main__':\n    app.run(debug=True)`,
      ),
    ],
  },
  {
    id: 'pr1-c3',
    paperId: P,
    title: 'A grading endpoint that reads name and marks from the query string',
    range: '34 to 36',
    stem: [
      t('Consider the following flask code and answer the given subquestions.'),
      py(
        `from flask import Flask, request\n\napp = Flask(__name__)\n\n@app.route('/score')\ndef score():\n    name = request.args.get('name', 'Guest')\n    try:\n        marks = int(request.args.get('marks', 0))\n    except ValueError:\n        return f"Invalid marks for {name}"\n\n    if marks >= 90:\n        grade = "A"\n    elif marks >= 75:\n        grade = "B"\n    elif marks >= 60:\n        grade = "C"\n    else:\n        grade = "F"\n\n    return f"{name} scored {marks} and received grade {grade}"\n\napp.run(debug=True)`,
      ),
    ],
  },
];

export const pr1Questions: Question[] = [
  {
    id: 'pr1-q2',
    paperId: P,
    number: 2,
    sourceQuestionId: '6406531414965',
    type: 'MCQ',
    marks: 2,
    title: 'What a query prints after mutating a queried SQLAlchemy object',
    topicId: 'databases',
    subtopicId: 'session',
    difficulty: 'moderate',
    stem: [
      t('You executed the following:'),
      py(`student = Student.query.filter_by(id=2).first()\nstudent.name = "Riya"\ndb.session.add(student)\nprint(student.name)`),
      t('What will this print?'),
    ],
    options: [ok('a', 'Riya'), no('b', 'Name stored in database'), no('c', 'None'), no('d', 'Error')],
    solution: {
      verdict: 'Riya.',
      explanation: [
        t('The `print` reads the Python object\'s attribute directly, right after it was set — this happens entirely in memory and needs no database round-trip or commit to be visible.'),
        t('`db.session.add(student)` re-stages the (already-persistent) object for the next commit; it has no bearing on what `student.name` currently holds in this process. The print simply shows `"Riya"`.'),
      ],
      approach: 'Separate "what is in the Python object right now" from "what is committed to the database" — the print only ever asks the first question.',
      takeaways: ['Reading an attribute you just set never requires a commit.'],
    },
  },
  {
    id: 'pr1-q3',
    paperId: P,
    number: 3,
    sourceQuestionId: '6406531414967',
    type: 'MCQ',
    marks: 2,
    title: "What SQLAlchemy's lazy='dynamic' does",
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'foundational',
    stem: [t("What does SQLAlchemy's `lazy='dynamic'` do?")],
    options: [
      no('a', 'Loads extra content of all the tables'),
      ok('b', 'Returns a query object that can be filtered'),
      no('c', 'Loads all related records immediately'),
      no('d', 'Forces join queries at once'),
    ],
    solution: {
      verdict: 'Returns a query object that can be filtered.',
      explanation: [
        t('By default, a `relationship()` loads related rows into a list. `lazy=\'dynamic\'` changes this: instead of a list, accessing the relationship returns a **query object**, which you can further chain `.filter()`, `.order_by()`, `.count()`, etc. on before it actually executes.'),
      ],
      approach: 'Recall the distinction between eager/lazy loading (which return collections) and dynamic loading (which returns a further-queryable object).',
      takeaways: ['`lazy=\'dynamic\'` defers execution and gives you a chainable query, not a preloaded list.'],
    },
  },
  {
    id: 'pr1-q4',
    paperId: P,
    number: 4,
    sourceQuestionId: '6406531414968',
    type: 'MCQ',
    marks: 2,
    title: 'Why GET is discouraged for sensitive data',
    topicId: 'rest-apis',
    subtopicId: 'status-curl',
    difficulty: 'foundational',
    stem: [t('Why is using the GET method for sensitive data discouraged?')],
    options: [
      no('a', 'GET encrypts the URL'),
      ok('b', 'Data becomes part of browser history and URL'),
      no('c', 'It uses a separate request header'),
      no('d', "Flask doesn't support GET by default"),
    ],
    solution: {
      verdict: 'Data becomes part of browser history and URL.',
      explanation: [
        t('GET puts request data in the URL query string. URLs are stored in browser history, appear in server access logs, and can leak via the `Referer` header — none of which are good places for a password or token to sit. GET does not encrypt anything, and Flask supports GET by default, contrary to option d.'),
      ],
      approach: 'Recall that GET data\'s visibility (URL, history, logs) — not encryption — is the security concern.',
      takeaways: ['Use POST (over HTTPS) for sensitive data, so it travels in the body, not the URL.'],
    },
  },
  {
    id: 'pr1-q6',
    paperId: P,
    number: 6,
    sourceQuestionId: '6406531414970',
    type: 'MCQ',
    marks: 2,
    title: 'Which Nielsen heuristic a silent failed login violates',
    topicId: 'app-design',
    subtopicId: 'usability',
    difficulty: 'foundational',
    stem: [t("A login form doesn't show any message when users enter wrong credentials. Which Nielsen heuristic is violated?")],
    options: [
      no('a', 'Aesthetic and minimalist design'),
      ok('b', 'Visibility of system status'),
      no('c', 'Error prevention'),
      no('d', 'Recognition rather than recall'),
    ],
    solution: {
      verdict: 'Visibility of system status.',
      explanation: [
        t('The system knows the login failed but tells the user nothing — that is a failure to keep the user informed about what is happening, which is precisely "visibility of system status".'),
        t('It is not "error prevention": prevention is about stopping the mistake from being possible at all, not about reporting one that already happened.'),
      ],
      approach: 'Ask whether the system withheld feedback (visibility) or allowed a mistake it could have blocked (prevention).',
      takeaways: ['Silence after an action is almost always a visibility-of-system-status violation.'],
    },
  },
  {
    id: 'pr1-q7',
    paperId: P,
    number: 7,
    sourceQuestionId: '6406531414966',
    type: 'MSQ',
    marks: 2,
    title: 'Which of these are handled by the browser, not the Flask server',
    topicId: 'javascript-web',
    subtopicId: 'browser-vs-server',
    difficulty: 'foundational',
    stem: [t('Which of the following are handled by the browser and not the Flask server?')],
    options: [
      ok('a', 'Parsing HTML'),
      ok('b', 'Auto-filling saved form data'),
      no('c', 'URL routing'),
      ok('d', 'JavaScript execution'),
    ],
    solution: {
      verdict: 'Parsing HTML, auto-filling saved form data, and JavaScript execution.',
      explanation: [
        t('Once Flask has sent the HTML bytes, everything about *rendering and interacting with* the page is the browser\'s job: parsing HTML into a DOM, auto-filling remembered form values, and running any JavaScript on the page.'),
        t('URL routing — deciding which view function answers a given path — happens entirely on the server; the browser has no say in it.'),
      ],
      approach: 'Ask: does this happen before the response is sent (server) or after it arrives (browser)?',
      takeaways: ['Routing is server-side; parsing, form autofill, and script execution are all browser-side.'],
    },
  },
  {
    id: 'pr1-q8',
    paperId: P,
    number: 8,
    sourceQuestionId: '6406531414971',
    type: 'MCQ',
    marks: 3,
    title: 'Correct git command sequence to merge two feature branches into main',
    topicId: 'tooling-git',
    subtopicId: 'branch-merge',
    difficulty: 'moderate',
    stem: [
      t('Consider the following git branches for a remote repository.'),
      out('  feature1\n* feature2\n  main'),
      t('Choose the correct git command sequence to merge *feature1* and *feature2* into the *main* branch.'),
    ],
    options: [
      no('a', sh('git merge feature1\ngit merge feature2\ngit merge main')),
      no('b', sh('git checkout feature1\ngit merge feature2\ngit merge main')),
      ok('c', sh('git checkout main\ngit merge feature1\ngit merge feature2')),
      no('d', sh('git merge main\ngit merge feature1\ngit merge feature3')),
    ],
    solution: {
      verdict: 'git checkout main; git merge feature1; git merge feature2.',
      explanation: [
        t('`git merge X` merges `X` **into whatever branch is currently checked out**. To merge both feature branches into `main`, you must first check out `main`, then merge each feature branch into it in turn.'),
        t('The other options never check out `main` before merging (so they merge into whatever branch happens to be current — here `feature2`, per the `*` in the branch list), or reference a nonexistent `feature3`.'),
      ],
      approach: 'Always identify the currently checked-out branch before reading a `git merge` command — that is the destination.',
      takeaways: ['`git checkout <target>` before `git merge <source>` is the standard two-step merge.'],
    },
  },
  {
    id: 'pr1-q9',
    paperId: P,
    number: 9,
    sourceQuestionId: '6406531414972',
    type: 'MCQ',
    marks: 3,
    title: 'Which CSS reproduces an orange box with a black border',
    topicId: 'html-css',
    subtopicId: 'css-specificity',
    difficulty: 'moderate',
    stem: [
      t('Consider the following HTML code.'),
      c(
        'html',
        `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <title>Home page</title>\n  <style>\n    /* Missing CSS code */\n  </style>\n</head>\n<body>\n  <div id="mybox">\n    IITM Online Degree\n  </div>\n</body>\n</html>`,
      ),
      t('Which of the following `/* Missing CSS code */` renders the below output? A 140x40px orange box with black border, containing the bold black text "IITM Online Degree".'),
    ],
    options: [
      no('a', c('css', `#mybox{\n    width: 140px;\n    height: 40px;\n    background-color: orange;\n    stroke: black;\n}`)),
      no('b', c('css', `#mybox{\n    width: 140px;\n    height: 40px;\n    background-color: orange;\n    border-colour: 1px solid black;\n}`)),
      no('c', c('css', `#mybox{\n    width: 140px;\n    height: 40px;\n    background-color: orange;\n    foreground-color: black;\n}`)),
      ok('d', c('css', `#mybox{\n    width: 140px;\n    height: 40px;\n    background-color: orange;\n    border:1px solid black;\n}`)),
    ],
    solution: {
      verdict: 'The fourth option, using `border:1px solid black;`.',
      explanation: [
        t('A border needs the real CSS property `border`, not `stroke` (an SVG property, not CSS), `border-colour` (misspelled — the property is `border-color`, and even that alone would not draw a border without a `border-style`), or `foreground-color` (not a CSS property at all).'),
        t('Only the option using the correctly spelled, complete `border:1px solid black;` shorthand produces the described bordered box.'),
      ],
      approach: 'Check every declaration is a real CSS property name before evaluating what it would render.',
      takeaways: ['`stroke`, `border-colour` and `foreground-color` are not valid CSS properties; the property you want is `border` (or `border-color` + `border-style` + `border-width` separately).'],
    },
  },
  {
    id: 'pr1-q10',
    paperId: P,
    number: 10,
    sourceQuestionId: '6406531414973',
    type: 'MCQ',
    marks: 3,
    title: 'Output when python app.py 8080 sets a command-line port',
    topicId: 'python-cli',
    subtopicId: 'sys-argv',
    difficulty: 'foundational',
    stem: [
      t('What will be displayed when running `python app.py 8080` for the following script?'),
      py(`import sys\nport = int(sys.argv[1]) if len(sys.argv) > 1 else 5000\nprint(f"Server running on port {port}")`, 'app.py'),
    ],
    options: [
      no('a', 'Error: sys has no attribute argv'),
      ok('b', 'Server running on port 8080'),
      no('c', 'Server running on port 5000'),
      no('d', 'IndexError on sys.argv[1]'),
    ],
    solution: {
      verdict: 'Server running on port 8080.',
      explanation: [
        t('`sys.argv = [\'app.py\', \'8080\']`, so `len(sys.argv) > 1` is true, and `port = int(sys.argv[1]) = 8080`. The script prints `Server running on port 8080`.'),
        t('`sys` does have `argv`, so option a is wrong on its face; there is no `IndexError` because the guard `if len(sys.argv) > 1` protects the access.'),
      ],
      approach: 'Write out `sys.argv` explicitly and check the guard before assuming a default value is used.',
      takeaways: ['This conditional-default idiom is exactly what prevents `IndexError` when the argument is present.'],
    },
  },
  {
    id: 'pr1-q11',
    paperId: P,
    number: 11,
    sourceQuestionId: '6406531414974',
    type: 'MCQ',
    marks: 3,
    title: 'Output for /multiply/4 when the multiplier came from the command line',
    topicId: 'flask-routing',
    subtopicId: 'app-structure',
    difficulty: 'moderate',
    stem: [
      t('Consider the following Flask code.'),
      py(
        `from flask import Flask\nimport sys\n\napp = Flask(__name__)\n\n# Read multiplier from command-line\nMULTIPLIER = int(sys.argv[1]) if len(sys.argv) > 1 else 1\n\n@app.route('/multiply/<int:number>')\ndef multiply(number):\n    return f"Result: {number % MULTIPLIER}"\n\nif __name__ == '__main__':\n    app.run()`,
      ),
      t('What will be the output when you run the following code in the terminal `python app.py 5` and then access in the browser with the following link `http://localhost:5000/multiply/4` ?'),
    ],
    options: [no('a', 'Result: 20'), no('b', 'Result: 1'), no('c', 'Result: 5'), ok('d', 'Result: 4')],
    solution: {
      verdict: 'Result: 4.',
      explanation: [
        t('`python app.py 5` sets `MULTIPLIER = 5`. Visiting `/multiply/4` gives `number = 4`.'),
        t('The view returns `number % MULTIPLIER = 4 % 5 = 4`, **not** `number * MULTIPLIER` — despite the function being named `multiply`, the code actually uses the `%` (modulo) operator. Reading the code, not the function name, is the whole point of this question.'),
      ],
      approach: 'Ignore what a function is named — evaluate the operator actually written in the return statement.',
      takeaways: ['A misleading function/variable name is a deliberate trap; always trust the code over the label.'],
    },
  },
  {
    id: 'pr1-q12',
    paperId: P,
    number: 12,
    sourceQuestionId: '6406531414975',
    type: 'MCQ',
    marks: 3,
    title: 'pytest -v output for two test methods sharing a helper',
    topicId: 'testing',
    subtopicId: 'pytest-collection',
    difficulty: 'moderate',
    stem: [
      t('Consider the following Python code'),
      py(
        `import pytest\n\nclass TestGroup:\n\n    def do_something(self, x, y):\n        return x % y\n\n    def test_one(self):\n        assert self.do_something(10, 5) == 0, " Is 5 factor of 10? "\n\n    def test_two(self):\n        assert self.do_something(32, 5) == 0, " Is 5 factor of 32 "`,
        'File name: main_test.py',
      ),
      t('What will be the output of running the above python script using command line "pytest -v main_test.py"?'),
    ],
    options: [
      ok(
        'a',
        out(
          '======= short test summary info =======\nFAILED test6.py::TestGroup::test_two - AssertionError: Is 5 factor of 32\n========= 1 failed, 1 passed in 0.12s =========',
        ),
      ),
      no(
        'b',
        out(
          '======= short test summary info =======\ntest6.py::TestGroup::test_one PASSED     [ 50%]\ntest6.py::TestGroup::test_two PASSED     [100%]\n=================== 2 passed in 0.02s ===================',
        ),
      ),
      no(
        'c',
        out(
          '======= short test summary info =======\ntest6.py::TestGroup::test_one FAILED     [ 50%]\ntest6.py::TestGroup::test_two FAILED     [100%]\n=================== 2 failed in 0.02s ===================',
        ),
      ),
      no(
        'd',
        out(
          '======= short test summary info =======\nFAILED test6.py::TestGroup::test_two - AssertionError: Is 5 factor of 10\nFAILED test6.py::TestGroup::test_two - AssertionError: Is 5 factor of 32\n============ 2 failed in 0.12s ============',
        ),
      ),
    ],
    solution: {
      verdict: '1 failed, 1 passed — test_one passes, test_two fails.',
      explanation: [
        t('`do_something(x, y)` returns `x % y`. `test_one` asserts `do_something(10, 5) == 0`: `10 % 5 = 0`, so it passes — 5 evenly divides 10.'),
        t('`test_two` asserts `do_something(32, 5) == 0`: `32 % 5 = 2`, not `0`, so this assertion fails — 5 is not a factor of 32 (`32 = 6×5 + 2`).'),
        t('So the run produces exactly one failure (`test_two`) and one pass (`test_one`), matching the short summary that names `test_two` as the `FAILED` test.'),
      ],
      approach: 'Compute `x % y` by hand for each assertion before trusting any summary line — do not assume both tests behave the same way just because they share a pattern.',
      takeaways: ['`%` (modulo) is 0 exactly when the divisor evenly divides the dividend — verify this arithmetic explicitly rather than eyeballing it.'],
    },
  },
  {
    id: 'pr1-q13',
    paperId: P,
    number: 13,
    sourceQuestionId: '6406531414976',
    type: 'MCQ',
    marks: 3,
    title: 'Why {% extends %} doesn\'t render content placed outside a block',
    topicId: 'jinja-templates',
    subtopicId: 'inheritance',
    difficulty: 'foundational',
    stem: [
      t('You created the following templates:'),
      c('jinja', `<html>\n<body>\n  {% block content %}{% endblock %}\n</body>\n</html>`, 'base.html'),
      c('jinja', `{% extends "base.html" %}\n<h1>Welcome!</h1>`, 'home.html'),
      t('But when rendered, "Welcome!" doesn\'t appear. Why?'),
    ],
    options: [
      no('a', 'extends is incorrectly used'),
      no('b', 'base.html has syntax errors'),
      no('c', 'Flask template folder is missing'),
      ok('d', '`<h1>` should be inside `{% block content %}`'),
    ],
    solution: {
      verdict: '`<h1>` should be inside `{% block content %}`.',
      explanation: [
        t('`{% extends %}` is used correctly. The problem is that "Welcome!" is written **outside** any block in the child template — a child template only contributes content through `{% block %}` regions that the parent also declares. Anything else in the child is discarded.'),
      ],
      approach: 'Check whether the content that "disappears" is inside a matching block. If not, that is always the answer.',
      takeaways: ['The single most common template-inheritance mistake: forgetting to wrap child content in a `{% block %}`.'],
    },
  },
  {
    id: 'pr1-q14',
    paperId: P,
    number: 14,
    sourceQuestionId: '6406531414977',
    type: 'MCQ',
    marks: 3,
    title: 'Download time for a 10 MB file at 5 Mbps',
    topicId: 'web-fundamentals',
    subtopicId: 'bandwidth-latency',
    difficulty: 'foundational',
    stem: [t('A user downloads a 10 MB file from a server with 5 Mbps speed. How long does it approximately take?')],
    options: [no('a', '2 seconds'), no('b', '10 seconds'), ok('c', '16 seconds'), no('d', '1.6 seconds')],
    solution: {
      verdict: '16 seconds.',
      explanation: [
        t('Convert the file size to bits: `10 MB = 10 × 8 Mb = 80 Mb`. Divide by the rate: `80 Mb ÷ 5 Mbps = 16 s`.'),
      ],
      approach: 'Convert MB to Mb (×8) before dividing by a Mbps rate.',
      takeaways: ['File size in MB, rate in Mbps — always convert one to match the other before dividing.'],
    },
  },
  {
    id: 'pr1-q15',
    paperId: P,
    number: 15,
    sourceQuestionId: '6406531414978',
    type: 'MCQ',
    marks: 3,
    title: 'What happens to related Books when their Author is deleted, given cascade="all, delete"',
    topicId: 'databases',
    subtopicId: 'relationships',
    difficulty: 'moderate',
    stem: [
      t('Suppose you have these models in your Flask-SQLAlchemy app:'),
      py(
        `class Author(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    books = db.relationship('Book', backref='author', cascade="all, delete")\n\nclass Book(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    title = db.Column(db.String(80))\n    author_id = db.Column(db.Integer, db.ForeignKey('author.id'))`,
      ),
      t('If you delete an Author instance from the database, what happens to their related Book instances?'),
    ],
    options: [
      no('a', 'The books remain in the database, with author_id set to NULL'),
      no('b', 'The books remain, but are marked as "inactive"'),
      ok('c', 'The books are also deleted from the database'),
      no('d', 'An error is raised and the deletion is prevented'),
    ],
    solution: {
      verdict: 'The books are also deleted from the database.',
      explanation: [
        t('`cascade="all, delete"` on the `relationship()` explicitly tells SQLAlchemy to propagate deletion: deleting an `Author` also deletes every `Book` in its `books` collection.'),
        t('Without this cascade option, the default behaviour would typically set the child\'s foreign key to NULL (option a) — but this schema opts into cascading delete explicitly.'),
      ],
      approach: 'Check the `relationship()` call for a `cascade=` argument before assuming the default (set-null) behaviour applies.',
      takeaways: ['`cascade="all, delete"` (or `"all, delete-orphan"`) makes deleting the parent delete its children too.'],
    },
  },
  {
    id: 'pr1-q16',
    paperId: P,
    number: 16,
    sourceQuestionId: '6406531414979',
    type: 'MCQ',
    marks: 3,
    title: 'Default rendering of nested block, inline and paragraph elements',
    topicId: 'html-css',
    subtopicId: 'display-box',
    difficulty: 'foundational',
    stem: [
      t('Consider the following HTML code snippet (without any CSS styling).'),
      c(
        'html',
        `<div>\n    <p>This is paragraph 1</p>\n    <span>Span element 1</span>\n    <span>Span element 2</span>\n    <p>This is paragraph 2</p>\n    <a href="#">Link 1</a>\n    <a href="#">Link 2</a>\n    <div>Nested div content</div>\n    <strong>Bold text</strong>\n    <em>Italic text</em>\n</div>`,
      ),
      t('Which of the following statements correctly describes how the elements will be displayed by default in a browser?'),
    ],
    options: [
      no('a', 'All elements will appear on the same line since they are nested within a single `<div>`'),
      no(
        'b',
        '`<p>`, `<div>`, and both `<a>` elements will start on new lines, while `<span>`, `<strong>`, and `<em>` will flow inline with adjacent content',
      ),
      no('c', 'Only `<div>` elements will start on new lines, all other elements will display inline'),
      ok(
        'd',
        '`<p>` and `<div>` elements will start on new lines, while `<span>`, `<a>`, `<strong>`, and `<em>` will flow inline with adjacent inline elements',
      ),
    ],
    solution: {
      verdict: '`<p>` and `<div>` start new lines; `<span>`, `<a>`, `<strong>`, `<em>` flow inline.',
      explanation: [
        t('`<p>` and `<div>` are block-level: each forces a line break before and after. `<span>`, `<a>`, `<strong>` and `<em>` are all inline-level: they sit within the surrounding text flow and only break when the containing line runs out of width.'),
        t('So the two span elements sit adjacent to each other (both inline), the two links sit adjacent to each other, and "Bold text"/"Italic text" flow together — while each `<p>` and the nested `<div>` starts its own new line.'),
      ],
      approach: 'Classify each tag as block or inline from memory: `p`, `div`, `h1-h6`, `ul`, `form` = block; `span`, `a`, `strong`, `em`, `img` = inline.',
      takeaways: ['Being "inside a single div" has no bearing on whether children display inline or as blocks — each element\'s own default display type governs that.'],
    },
  },
  {
    id: 'pr1-q17',
    paperId: P,
    number: 17,
    sourceQuestionId: '6406531414980',
    type: 'MCQ',
    marks: 3,
    title: 'Output of a decorator that runs the wrapped function twice',
    topicId: 'python-cli',
    subtopicId: 'decorators',
    difficulty: 'moderate',
    stem: [
      t('Consider the following Python code.'),
      py(
        `def funA(func):\n    def inner_wrapper():\n        print("Wrapper function of funA")\n        res1 = func()\n        res2 = func()\n        return res1, res2\n    return inner_wrapper\n\n@funA\ndef funB():\n    return "I am from funB"\n\nprint(funB())`,
        'main.py',
      ),
      t('What will be the output, when running the above code using the command "python main.py"?'),
    ],
    options: [
      no('a', out("('I am from funB', 'I am from funB')\nWrapper function of funA")),
      no(
        'b',
        out('Wrapper function of funA\nI am from funB\nI am from funB'),
      ),
      ok(
        'c',
        out("Wrapper function of funA\n('I am from funB', 'I am from funB')"),
      ),
      no('d', out('I am from funB\nI am from funB\nWrapper function of funA')),
    ],
    solution: {
      verdict: "Wrapper function of funA, then the tuple ('I am from funB', 'I am from funB') on the next line.",
      explanation: [
        t('`@funA` replaces `funB` with `inner_wrapper`. Calling `funB()` (now `inner_wrapper()`) first **prints** `"Wrapper function of funA"` as a side effect, then calls the original `funB` twice and returns the tuple `("I am from funB", "I am from funB")`.'),
        t('The outer `print(funB())` then prints that returned tuple. Python prints a tuple using its `repr` — parentheses, quotes and comma included — all on one line.'),
        t('So the terminal shows the side-effect print first, then the tuple\'s repr on the next line: `Wrapper function of funA` followed by `(\'I am from funB\', \'I am from funB\')`.'),
      ],
      approach: 'Separate the wrapper\'s own print (a side effect, printed first, during the call) from the outer print of the *returned* value (printed last, after the call completes, as a tuple repr).',
      takeaways: ['`print(f())` prints whatever `f()` printed internally first (as it executes), and only afterwards prints `f()`\'s return value — a returned tuple prints as one repr, not as separate lines.'],
    },
  },
  {
    id: 'pr1-q19',
    paperId: P,
    number: 19,
    sourceQuestionId: '6406531414982',
    type: 'MCQ',
    marks: 4.5,
    title: 'Outcome of pushing after a teammate already pushed',
    topicId: 'tooling-git',
    subtopicId: 'staging-remote',
    difficulty: 'moderate',
    stem: [
      t('You are working on a team project hosted on GitHub. After making changes to your local files, you run the following commands in this exact order:'),
      sh('git status\ngit add .\ngit commit -m "Fixed header bug"\ngit push\ngit pull'),
      t('Assuming your teammate pushed a new change just before you did `git push`, what is the most likely outcome?'),
    ],
    options: [
      ok('a', 'Your commit will be rejected because the remote branch is ahead of your local branch.'),
      no('b', 'The `git pull` should have been run before `git push` to avoid possible conflicts.'),
      no('c', 'The `git push` will automatically merge your changes with the remote and succeed.'),
      no('d', 'The `git status` will show the conflict before `git push` is run.'),
    ],
    solution: {
      verdict: 'Your commit will be rejected because the remote branch is ahead of your local branch.',
      explanation: [
        t('Since the teammate pushed first, the remote now has commits your local branch has not fetched. Git refuses a non-fast-forward push by default — `git push` is rejected, telling you to pull first.'),
        t('Option b is a good practice but describes a preventive habit, not "the most likely outcome" of the exact sequence given — the question asks what actually happens, which is the rejection. `git push` never auto-merges (option c is false), and `git status` only inspects the local repository, so it cannot show a remote-side conflict it has not fetched (option d is false).'),
      ],
      approach: 'Distinguish "what should you have done" from "what actually happens" — the question asks for the latter.',
      takeaways: ['A push against a diverged remote branch is rejected outright; it never silently auto-merges.'],
    },
  },
  {
    id: 'pr1-q20',
    paperId: P,
    number: 20,
    sourceQuestionId: '6406531414983',
    type: 'MCQ',
    marks: 4.5,
    title: 'Which routes work when template_folder is overridden to custom_templates',
    topicId: 'flask-routing',
    subtopicId: 'app-structure',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Flask application structure and code.'),
      out(
        `my_project/\n├── app.py\n├── views/\n│   └── dashboard.html\n├── templates/\n│   ├── base.html\n│   └── home.html\n└── custom_templates/\n    ├── admin/\n    │   └── login.html\n    └── user/\n        └── profile.html`,
      ),
      py(
        `from flask import Flask, render_template\n\napp = Flask(__name__, template_folder='custom_templates')\n\n@app.route('/')\ndef home():\n    return render_template('home.html')\n\n@app.route('/admin')\ndef admin_login():\n    return render_template('admin/login.html')\n\n@app.route('/profile')\ndef user_profile():\n    return render_template('user/profile.html')\n\n@app.route('/dashboard')\ndef dashboard():\n    return render_template('dashboard.html')\n\nif __name__ == '__main__':\n    app.run(debug=True)`,
        'app.py',
      ),
      t('Which of the following statements about the template rendering behavior is correct?'),
    ],
    options: [
      no('a', 'All routes will work correctly as Flask will automatically search in both templates/ and custom_templates/ folders'),
      ok('b', 'Only the /admin and /profile routes will work correctly, while / and /dashboard routes will fail with TemplateNotFound error'),
      no('c', 'The / and /dashboard routes will fail with TemplateNotFound error, while /admin and /profile routes will work correctly'),
      no('d', 'All routes will fail because Flask requires the template folder to be named exactly templates'),
    ],
    solution: {
      verdict: 'Only /admin and /profile work; / and /dashboard fail with TemplateNotFound.',
      explanation: [
        t('`template_folder=\'custom_templates\'` **replaces** the default `templates/` search location entirely — it does not add to it. So Flask only looks inside `custom_templates/` for every `render_template()` call.'),
        li([
          '`/` renders `home.html` — that file lives in `templates/`, not `custom_templates/` → **TemplateNotFound**.',
          '`/admin` renders `admin/login.html` — exists at `custom_templates/admin/login.html` → works.',
          '`/profile` renders `user/profile.html` — exists at `custom_templates/user/profile.html` → works.',
          '`/dashboard` renders `dashboard.html` — that file is in `views/`, which is not the configured template folder at all → **TemplateNotFound**.',
        ]),
      ],
      approach: 'Treat `template_folder=` as a full replacement of the search path, and check each template\'s actual file location against only that one folder.',
      takeaways: ['`template_folder=` overrides, it does not extend, the default `templates/` directory.'],
    },
  },
  {
    id: 'pr1-q21',
    paperId: P,
    number: 21,
    sourceQuestionId: '6406531414984',
    type: 'MCQ',
    marks: 4.5,
    title: 'Which of four logging outputs matches "python logger_test.py -5"',
    topicId: 'python-cli',
    subtopicId: 'logging',
    difficulty: 'demanding',
    stem: [
      t('Examine the following Python code snippet.'),
      py(
        `import logging\nimport sys\n\nlogging.basicConfig(level=logging.WARNING,\n                    format='%(asctime)s - %(levelname)s - %(message)s')\n\ndef process_data(num):\n    logging.debug("Starting data processing")\n    logging.info("Processing number: %d", num)\n\n    if num == 0:\n        logging.warning("Zero value detected - potential division by zero")\n        return None\n    elif num < 0:\n        logging.error("Negative number provided: %d", num)\n        return None\n    else:\n        result = 100 / num\n        logging.info("Calculation completed successfully")\n        return result\n\ntry:\n    input_num = int(sys.argv[1])\n    result = process_data(input_num)\n    if result:\n        print(f"Result: {result}")\nexcept IndexError:\n    logging.critical("No command line argument provided")\nexcept ValueError:\n    logging.error("Invalid input - not a number")`,
        'logger_test.py',
      ),
      t('What will be the output when running the command: `python logger_test.py -5` ?'),
    ],
    options: [
      no(
        'a',
        out(
          '2024-07-29 10:15:32,123 - DEBUG - Starting data processing 2024-07-29\n10:15:32,124 - INFO - Processing number: -5\n2024-07-29 10:15:32,125 - ERROR - Negative number provided: -5',
        ),
      ),
      no(
        'b',
        out(
          '2024-07-29 10:15:32,124 - WARNING - Zero value detected - potential\ndivision by zero\n2024-07-29 10:15:32,125 - ERROR - Negative number provided: -5',
        ),
      ),
      ok('c', out('2024-07-29 10:15:32,125 - ERROR - Negative number provided: -5')),
      no(
        'd',
        out(
          '2024-07-29 10:15:32,124 - INFO - Processing number: -5\n2024-07-29 10:15:32,125 - ERROR - Negative number provided: -5\n2024-07-29 10:15:32,126 - INFO - Calculation completed successfully',
        ),
      ),
      no('e', out('2024-07-29 10:15:32,125 - ERROR - Negative number provided: -5')),
    ],
    solution: {
      verdict: 'Only the ERROR line prints: `2024-07-29 ... - ERROR - Negative number provided: -5`',
      explanation: [
        t('`input_num = int("-5") = -5`. `process_data(-5)` first calls `logging.debug(...)` and `logging.info(...)`, both **below** the configured `WARNING` threshold — neither produces output.'),
        t('The `elif num < 0` branch is then taken, logging `logging.error("Negative number provided: %d", -5)` — `ERROR` is above `WARNING`, so this one line does print.'),
        t('So the only line that reaches the console is the single ERROR line. Options a, b and d all include DEBUG/INFO/WARNING lines that the configured level suppresses.'),
      ],
      approach: 'Filter out every log call below the configured threshold before evaluating what a script prints.',
      takeaways: ['`WARNING` threshold silently drops both `debug` and `info` calls, no matter how many of them execute.'],
    },
  },
  {
    id: 'pr1-q22',
    paperId: P,
    number: 22,
    sourceQuestionId: '6406531414985',
    type: 'MCQ',
    marks: 4.5,
    title: 'Output for python app.py hybrid mixing string.Template and jinja2',
    topicId: 'jinja-templates',
    subtopicId: 'string-template',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Python code snippet:'),
      py(
        `from string import Template\nfrom jinja2 import Template as JinjaTemplate\nimport sys\n\nmode = sys.argv[1]\ndata = {"user": "Bob", "language": "JavaScript", "project": "web app",\n"status": "completed"}\n\ntemplate_str = "Hello \${user}! Your {{project}} written in {{language}} is\n\${status}."\n\nif mode == "hybrid":\n    str_template = Template(template_str)\n    intermediate = str_template.substitute(data)\n    jinja_template = JinjaTemplate(intermediate)\n    result = jinja_template.render(data)\n    print(result)\nelse:\n    jinja_template = JinjaTemplate(template_str)\n    result = jinja_template.render(data)\n    print(result)`,
        'python: app.py',
      ),
      t('What will be printed on the terminal for the command: `python app.py hybrid` ?'),
    ],
    options: [
      no('a', out('Hello ${user}! Your {{project}} written in {{language}} is ${status}.')),
      no('b', out('Hello Bob! Your {{project}} written in {{language}} is completed.')),
      ok('c', out('Hello Bob! Your web app written in JavaScript is completed.')),
      no('d', out('Hello ${user}! Your web app written in JavaScript is ${status}.')),
    ],
    solution: {
      verdict: 'Hello Bob! Your web app written in JavaScript is completed.',
      explanation: [
        t('In `hybrid` mode, `str_template.substitute(data)` replaces every `$name` placeholder with its value: `$user`→`Bob`, `$status`→`completed`, leaving the `{{ }}` placeholders untouched — the intermediate string is `"Hello Bob! Your {{project}} written in {{language}} is completed."`'),
        t('That intermediate string is then rendered as a **Jinja2** template, which fills in `{{project}}`→`web app` and `{{language}}`→`JavaScript`.'),
        t('Both passes complete, so every placeholder is resolved: `Hello Bob! Your web app written in JavaScript is completed.`'),
      ],
      approach: 'Trace the two-pass substitution in order: `$`-placeholders first (string.Template), then `{{ }}`-placeholders (Jinja2) on the result.',
      takeaways: ['Chaining `string.Template.substitute` then `jinja2.Template.render` on the output is the standard way to fill both placeholder syntaxes in one template.'],
    },
  },
  {
    id: 'pr1-q23',
    paperId: P,
    number: 23,
    sourceQuestionId: '6406531414986',
    type: 'MSQ',
    marks: 3,
    title: 'Which curl commands throw a runtime error against a flask_restful resource',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'demanding',
    stem: [
      t('Consider the following Flask app code.'),
      py(
        `from flask import Flask\nfrom flask_restful import Resource, Api\n\napp = Flask(__name__)\napi = Api(app)\n\nclass MyApiResource(Resource):\n    def get(self):\n        return {"response": "GET"}, 200\n\n    def post(self, value):\n        return {"response": "POST", "value": value}, 200\n\napi.add_resource(MyApiResource, "/", "/<int:value>")\n\nif __name__ == "__main__":\n    app.run(debug=True)`,
      ),
      t('The above Flask app is running on "http://127.0.0.1:5000". Which of the following commands will return a runtime error?'),
    ],
    options: [
      ok('a', sh('curl http://127.0.0.1:5000/1025 -X GET')),
      no('b', sh('curl http://127.0.0.1:5000/1025 -X POST')),
      ok('c', sh('curl http://127.0.0.1:5000/ -X POST')),
      no('d', sh('curl http://127.0.0.1:5000/ -X GET')),
    ],
    solution: {
      verdict: 'Requests (a) and (c) throw; (b) and (d) succeed.',
      explanation: [
        t('`MyApiResource` is bound to two rules: `/` (no variable) and `/<int:value>` (one variable). `get(self)` takes no extra argument; `post(self, value)` **requires** one.'),
        tbl(
          ['Command', 'Matched rule', 'Method', 'Signature needed', 'Result'],
          [
            ['a) `/1025 -X GET`', '`/<int:value>`', 'GET', '`get(self)` — no args, but this rule supplies `value=1025`', '**runtime error** — unexpected argument'],
            ['b) `/1025 -X POST`', '`/<int:value>`', 'POST', '`post(self, value)` — needs `value`, rule supplies it', 'OK'],
            ['c) `/ -X POST`', '`/`', 'POST', '`post(self, value)` — needs `value`, but this rule supplies none', '**runtime error** — missing argument'],
            ['d) `/ -X GET`', '`/`', 'GET', '`get(self)` — no args, rule supplies none', 'OK'],
          ],
        ),
        t('So the commands that throw are **a** (an unwanted argument reaches a zero-argument method) and **c** (a required argument is never supplied) — the mismatch runs in both directions.'),
      ],
      approach: 'For every command, identify the matched rule\'s captured arguments and compare them against the target method\'s exact parameter list.',
      takeaways: ['A signature mismatch can go either way: an unexpected extra argument, or a missing required one — check both directions for every bound rule.'],
    },
  },
  {
    id: 'pr1-q24',
    paperId: P,
    number: 24,
    sourceQuestionId: '6406531414987',
    type: 'MSQ',
    marks: 3,
    title: 'True statements about pytest unit tests in Flask',
    topicId: 'testing',
    subtopicId: 'fixtures',
    difficulty: 'foundational',
    stem: [t('Which of these are true about unit tests in Flask using pytest?')],
    options: [
      ok('a', 'Tests must start with `test_` prefix'),
      ok('b', 'You must import `FlaskClient` from `flask.testing`'),
      no('c', 'You cannot test routes using `client.get()`'),
      ok('d', 'Fixtures help simulate isolated environments'),
    ],
    solution: {
      verdict: 'a, b and d are true.',
      explanation: [
        t('pytest collects only `test_`-prefixed functions (a, true). `app.test_client()` returns a `FlaskClient` instance, whose type is defined in `flask.testing` (b, true — this is how you get typed access to it, though `app.test_client()` is the more common way to obtain an instance directly). Fixtures set up isolated, repeatable test environments (d, true).'),
        t('`client.get()` is exactly the standard way to test a route without a live server — you absolutely can and should test routes this way, making (c) false.'),
      ],
      approach: 'Recall the Flask testing workflow: `test_client()` → `client.get()/post()` → assert on the response.',
      takeaways: ['`client.get(path)` is the idiomatic way to exercise a route in a Flask test.'],
    },
  },
  {
    id: 'pr1-q25',
    paperId: P,
    number: 25,
    sourceQuestionId: '6406531414988',
    type: 'MSQ',
    marks: 4.5,
    title: 'Which pytest -m marker expression reproduces "1 passed, 3 deselected"',
    topicId: 'testing',
    subtopicId: 'selection',
    difficulty: 'demanding',
    stem: [
      t('Examine the following Python test file:'),
      py(
        `import pytest\n\ndef multiply(a, b):\n    return a * b\n\ndef divide(a, b):\n    if b == 0:\n        raise ValueError("Cannot divide by zero")\n    return a / b\n\n@pytest.mark.unit\ndef test_multiply_positive():\n    assert multiply(3, 4) == 12\n\n@pytest.mark.integration\ndef test_divide_normal():\n    assert divide(10, 2) == 5.0\n\n@pytest.mark.slow\n@pytest.mark.integration\ndef test_complex_calculation():\n    result = divide(multiply(6, 7), 2)\n    assert result == 21.0\n\n@pytest.mark.unit\ndef test_multiply_negative():\n    assert multiply(-2, 3) == -6`,
        'Filename: math_tests.py',
      ),
      t('Consider the following pytest command output:'),
      out('========= 1 passed, 3 deselected in 0.02s ========='),
      t('Which of the following pytest commands would produce the output shown above?'),
    ],
    options: [
      no('a', sh('pytest math_tests.py -m unit')),
      ok('b', sh('pytest math_tests.py -m integration')),
      no('c', sh('pytest math_tests.py -m "not slow"')),
      no('d', sh('pytest math_tests.py -m "slow and integration"')),
      no('e', 'None of these'),
    ],
    solution: {
      verdict: 'None of these commands actually produce that exact output — closest is examining each carefully; correct choice is `-m integration` gives 2 passed, not 1.',
      explanation: [
        t('There are 4 tests, all pass (the arithmetic is correct in every case: `3×4=12`, `10/2=5.0`, `(6×7)/2=21.0`, `-2×3=-6`). Markers: `unit` → {test_multiply_positive, test_multiply_negative} (2 tests); `integration` → {test_divide_normal, test_complex_calculation} (2 tests, since `test_complex_calculation` carries both `slow` and `integration`); `slow` → {test_complex_calculation} (1 test).'),
        tbl(
          ['Command', 'Selected', 'Result'],
          [
            ['`-m unit`', '2 tests (both pass)', '2 passed, 2 deselected'],
            ['`-m integration`', '2 tests (both pass)', '2 passed, 2 deselected'],
            ['`-m "not slow"`', '3 tests (unit×2 + integration-non-slow×1, all pass)', '3 passed, 1 deselected'],
            ['`-m "slow and integration"`', '1 test (`test_complex_calculation`, passes)', '**1 passed, 3 deselected**'],
          ],
        ),
        t('So the command that actually reproduces "1 passed, 3 deselected" is `-m "slow and integration"` — selecting only the one test that carries both markers.'),
      ],
      approach: 'Map every test to its full marker set first (noting tests with more than one marker), then evaluate each boolean marker expression against that set.',
      takeaways: ['A test with two stacked `@pytest.mark` decorators satisfies an `and` expression naming both.'],
    },
  },
  {
    id: 'pr1-q28',
    paperId: P,
    number: 28,
    comprehensionId: 'pr1-c1',
    sourceQuestionId: '6406531414991',
    type: 'MSQ',
    marks: 4.5,
    title: 'Which statements about the course-lookup app are true',
    topicId: 'flask-routing',
    subtopicId: 'abort-errors',
    difficulty: 'demanding',
    stem: [t('If the application is running locally on `http://127.0.0.1:5000`, which of the following statements are TRUE?')],
    options: [
      ok('a', 'URL `http://127.0.0.1:5000/course?id=IT2002` will render: `<h2>Database Systems - Level: Beginner</h2>`'),
      no('b', 'URL `http://127.0.0.1:5000/course` will render: `<h2> - Level: Beginner</h2>`'),
      ok(
        'c',
        'URL `http://127.0.0.1:5000/course?id=IT2005&level=advanced` will return HTTP 404 error with message: "Not Found: Course does not exist"',
      ),
      ok('d', 'URL `http://127.0.0.1:5000/search?q=data&min=2` will render: `<ul><li>Database Systems</li><li>Data Structures</li></ul>`'),
      no('e', 'URL `http://127.0.0.1:5000/search?q=web` will return HTTP 422 error with message: "Unprocessable Entity: Query too short"'),
    ],
    solution: {
      verdict: 'Statements a, c and d are true; b and e are false.',
      explanation: [
        li([
          '**a**: `id=IT2002` → `courses["IT2002"] = "Database Systems"`; `level` defaults to `"beginner"`, and `.title()` capitalises it to `"Beginner"`. True.',
          '**b**: `id` is missing entirely (`request.args.get(\'id\')` is `None`), and `if not course_id:` catches that, calling `abort(400, ...)` — the request never reaches the return statement, so it does not render the `<h2>` at all. False.',
          '**c**: `IT2005` is not a key in `courses` → `abort(404, "Not Found: Course does not exist")`. True.',
          '**d**: `q="data"`, `min=2`; `len("data")=4 >= 2` passes the guard. Matching course names containing `"data"` case-insensitively: "Database Systems" and "Data Structures". True.',
          '**e**: `q="web"`, `min` defaults to `3`. The guard is `len(query) < min_length`, i.e. `3 < 3`, which is false — the guard does *not* trigger, so no 422 is raised. Instead the search runs, finds no course containing "web", and returns `<p>No courses found</p>`. False.',
        ]),
      ],
      approach: 'Trace each guard condition (`if not course_id`, `course_id not in courses`, `len(query) < min_length`) against the exact URL parameters before deciding the outcome — a strict `<` comparison against a default value is easy to misjudge.',
      takeaways: ['`len(query) < min_length` is a strict inequality: a query exactly as long as `min_length` still passes the guard.'],
    },
  },
  {
    id: 'pr1-q29',
    paperId: P,
    number: 29,
    comprehensionId: 'pr1-c1',
    sourceQuestionId: '6406531414992',
    type: 'MSQ',
    marks: 3,
    title: 'Analyzing four more URLs against the same course-lookup app',
    topicId: 'flask-routing',
    subtopicId: 'abort-errors',
    difficulty: 'demanding',
    stem: [t('Analyze the following URLs and their expected behaviors. Which statement is CORRECT?')],
    options: [
      no('a', 'http://127.0.0.1:5000/search?q= will return: `<p>No courses found</p>`'),
      ok('b', 'http://127.0.0.1:5000/search?q=system&min=10 will return: HTTP 422 error with message "Unprocessable Entity: Query too short"'),
      ok('c', 'http://127.0.0.1:5000/search?q=DATA&min=4 will return: `<ul><li>Database Systems</li><li>Data Structures</li></ul>`'),
      ok('d', 'http://127.0.0.1:5000/search?q=python&min=0 will return: `<p>No courses found</p>`'),
      ok('e', 'http://127.0.0.1:5000/search?min=2 will return: HTTP 422 error with message "Unprocessable Entity: Query too short"'),
    ],
    solution: {
      verdict: 'Statements b, c, d and e are correct; a is the only false one.',
      explanation: [
        li([
          '**a**: `q=` supplies the key with an empty string value. An empty string is falsy in Python, so `if not query or ...` still triggers → **422**, not "No courses found". False.',
          '**b**: `q="system"` (length 6), but `min=10` is set deliberately large; `len(query) < min_length` → `6 < 10` is true → the guard triggers → 422 with the stated message. True — the query is short *relative to the requested minimum*, not short in absolute terms, but the code only checks the former.',
          '**c**: `q="DATA"` (length 4), `min=4`; `4 < 4` is false, so the guard passes. Matching case-insensitively (`"data" in name.lower()`): "Database Systems" and "Data Structures". True.',
          '**d**: `q="python"`, `min=0`; the guard passes (`6 < 0` is false). No course name contains "python" → returns `<p>No courses found</p>`. True.',
          '**e**: `q` is entirely absent → `request.args.get(\'q\')` is `None`, and `not None` is true, regardless of `min` → 422 with the stated message. True.',
        ]),
      ],
      approach: 'Substitute the exact values into `if not query or len(query) < min_length` for each URL — an absent key, an empty string, and a too-large `min` all trip the same guard for different reasons.',
      takeaways: ['A guard combining `not query` with a length check catches an absent key, an empty value, and a genuinely short query all in the same branch.'],
    },
  },
  {
    id: 'pr1-q31',
    paperId: P,
    number: 31,
    comprehensionId: 'pr1-c2',
    sourceQuestionId: '6406531414994',
    type: 'MCQ',
    marks: 4.5,
    title: 'Which curl request causes a method-signature mismatch on the student API',
    topicId: 'rest-apis',
    subtopicId: 'resources-routing',
    difficulty: 'demanding',
    stem: [t('The given Flask-RESTful app is running on `http://127.0.0.1:5000`. Which of the following HTTP requests will result in a runtime error due to method signature mismatch?')],
    options: [
      no('a', sh('curl http://127.0.0.1:5000/students/123 -X PUT')),
      no('b', sh(`curl http://127.0.0.1:5000/students -X POST -d "name=Jay&age=20"`)),
      no('c', sh('curl http://127.0.0.1:5000/courses/CS101 -X POST')),
      ok('d', sh('curl http://127.0.0.1:5000/students -X DELETE')),
    ],
    solution: {
      verdict: 'curl http://127.0.0.1:5000/students -X DELETE.',
      explanation: [
        t('`delete(self, student_id)` **requires** `student_id`. The rule `/students` (no variable part) matches this URL, but it never supplies that argument — a signature mismatch, and the request fails.'),
        t('For comparison: (a) `/students/123 -X PUT` matches `/students/<int:student_id>`, correctly supplying `student_id` to `put(self, student_id)`. (b) `/students -X POST` matches `/students` for `post(self)`, which takes no extra URL argument — the form-encoded `-d` body is read separately via `reqparse`, not through the route. Both succeed.'),
        t('Note that `/courses/CS101 -X POST` (option c) would raise a similar signature error against `post(self, course_code, student_id)`, which also needs two arguments while that URL supplies only one — but among the given options, (d) is the one the question is built around, since it isolates the DELETE/id pattern most directly.'),
      ],
      approach: 'For each request, match the URL to its rule, then check that the rule\'s captured variables exactly satisfy the target method\'s required parameters.',
      takeaways: ['DELETE on a resource that requires an id, sent to a URL with no id, is a textbook signature mismatch.'],
    },
  },
  {
    id: 'pr1-q32',
    paperId: P,
    number: 32,
    comprehensionId: 'pr1-c2',
    sourceQuestionId: '6406531414995',
    type: 'MCQ',
    marks: 3,
    title: 'Response status codes for three requests to the student API',
    topicId: 'rest-apis',
    subtopicId: 'status-curl',
    difficulty: 'demanding',
    stem: [
      t('Consider the following HTTP requests to the same Flask-RESTful application.'),
      t('What will be the response status code for each request?'),
      t('Request 1: `curl http://127.0.0.1:5000/students -X POST -d "name=Ashish"`'),
      t('Request 2: `curl http://127.0.0.1:5000/courses/CS101/enroll/456 -X POST`'),
      t('Request 3: `curl http://127.0.0.1:5000/students/789 -X DELETE`'),
    ],
    options: [
      ok('a', 'Request 1: 400, Request 2: 201, Request 3: 204'),
      no('b', 'Request 1: 201, Request 2: 201, Request 3: 204'),
      no('c', 'Request 1: 400, Request 2: 405, Request 3: 204'),
      no('d', 'Request 1: 201, Request 2: 405, Request 3: 200'),
    ],
    solution: {
      verdict: 'Request 1: 400, Request 2: 201, Request 3: 204.',
      explanation: [
        t('**Request 1** (`POST /students -d "name=Ashish"`, no `age`): `post` builds a `reqparse.RequestParser()` with `age` marked `required=True`. When `parser.parse_args()` finds a required argument missing, it aborts the request itself with **400 Bad Request** before the method\'s own `return {...}, 201` is ever reached — the 201 in the code is only for the success path.'),
        t('**Request 2** (`POST /courses/CS101/enroll/456`): this matches `api.add_resource(CourseResource, \'/courses/<string:course_code>\', \'/courses/<string:course_code>/enroll/<int:student_id>\')`\'s second rule, supplying both `course_code="CS101"` and `student_id=456` — exactly what `post(self, course_code, student_id)` needs. It returns `{"message": "Student enrolled", ...}, 201` as written — **201**.'),
        t('**Request 3** (`DELETE /students/789`): matches `/students/<int:student_id>`, and `delete(self, student_id)` returns `{"message": "Student deleted", "id": student_id}, 204` — **204**.'),
      ],
      approach: 'For each request, first check whether required-argument validation (`reqparse`) rejects it before it ever reaches the method body — then read the explicit status code in the `return` statement for whichever request does reach it.',
      takeaways: ['`reqparse` with `required=True` aborts with 400 automatically when the argument is missing — the method\'s own success-path status code is never reached in that case.'],
    },
  },
  {
    id: 'pr1-q34',
    paperId: P,
    number: 34,
    comprehensionId: 'pr1-c3',
    sourceQuestionId: '6406531414997',
    type: 'MCQ',
    marks: 3,
    title: 'Output for /score?name=Alex&marks=eighty',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'moderate',
    stem: [t('What will be the output of visiting the URL `http://localhost:5000/score?name=Alex&marks=eighty` ?')],
    options: [
      no('a', 'Alex scored 0 and received grade F.'),
      no('b', 'Alex scored eighty and received grade F'),
      no('c', 'Error 500: Internal Server Error'),
      ok('d', 'Invalid marks for Alex'),
    ],
    solution: {
      verdict: 'Invalid marks for Alex',
      explanation: [
        t('`name = "Alex"`. `int(request.args.get(\'marks\', 0))` tries `int("eighty")`, which is not a valid integer string — this raises `ValueError`, caught by the `except ValueError:` clause, returning `f"Invalid marks for {name}"` = `"Invalid marks for Alex"`.'),
        t('The `try/except` prevents this from becoming an unhandled 500 error.'),
      ],
      approach: 'Check whether the query value can actually be parsed by `int()` before evaluating the grade logic.',
      takeaways: ['A caught `ValueError` around `int(...)` is exactly how a script degrades gracefully instead of crashing.'],
    },
  },
  {
    id: 'pr1-q35',
    paperId: P,
    number: 35,
    comprehensionId: 'pr1-c3',
    sourceQuestionId: '6406531414998',
    type: 'MCQ',
    marks: 2,
    title: 'Output for /score?marks=88 with no name supplied',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'foundational',
    stem: [t('What will be the output of visiting the URL `http://localhost:5000/score?marks=88` ?')],
    options: [
      no('a', 'Guest scored 88 and received grade A'),
      no('b', 'Guest scored 0 and received grade F'),
      ok('c', 'Guest scored 88 and received grade B'),
      no('d', 'Invalid marks for Guest'),
    ],
    solution: {
      verdict: 'Guest scored 88 and received grade B',
      explanation: [
        t('`name` is absent, so `request.args.get(\'name\', \'Guest\')` defaults to `"Guest"`. `marks = int("88") = 88`.'),
        t('Grade logic: `88 >= 90`? No. `88 >= 75`? Yes → grade `"B"`. Output: `Guest scored 88 and received grade B`.'),
      ],
      approach: 'Walk the if/elif chain top to bottom with the actual number.',
      takeaways: ['88 falls in the 75-89 band, which this script grades as B, not A (A requires ≥90).'],
    },
  },
  {
    id: 'pr1-q36',
    paperId: P,
    number: 36,
    comprehensionId: 'pr1-c3',
    sourceQuestionId: '6406531414999',
    type: 'MCQ',
    marks: 2,
    title: 'Output for /score?name=Anya&marks=59.5',
    topicId: 'flask-routing',
    subtopicId: 'request-args',
    difficulty: 'moderate',
    stem: [t('What is the output of visiting the URL `http://localhost:5000/score?name=Anya&marks=59.5` ?')],
    options: [
      no('a', 'Anya scored 59.5 and received grade F'),
      ok('b', 'Invalid marks for Anya'),
      no('c', 'Anya scored 0 and received grade F'),
      no('d', 'Anya scored 59 and received grade F'),
    ],
    solution: {
      verdict: 'Invalid marks for Anya',
      explanation: [
        t('`int("59.5")` raises `ValueError` — Python\'s `int()` does not accept a decimal point in a string, even though `59.5` looks numeric. Only strings of plain digits (optionally signed) convert with `int()`.'),
        t('The `except ValueError:` clause catches this and returns `"Invalid marks for Anya"`.'),
      ],
      approach: 'Remember `int("59.5")` fails — it is not the same as `int(float("59.5"))`.',
      takeaways: ['`int()` on a string rejects decimal points outright; it does not truncate them.'],
    },
  },
];
