import type { Topic } from './types';

/**
 * The topic tree is derived from what the five source papers actually test.
 * Every subtopic below has at least one question mapped to it; `checkContent`
 * in `index.ts` fails the build-time audit if that stops being true.
 */
export const topics: Topic[] = [
  {
    id: 'flask-routing',
    name: 'Flask Routing & Views',
    blurb: 'Routes, URL converters, request arguments, redirects, aborts and error handlers.',
    subtopics: [
      { id: 'routes-converters', name: 'Routes & URL converters', summary: 'Mapping URLs to view functions, and how <int:>, <string:> and <path:> change what matches.' },
      { id: 'request-args', name: 'Request arguments & methods', summary: 'Reading query strings and form data, and which HTTP methods a route accepts.' },
      { id: 'redirect-urlfor', name: 'url_for & redirect', summary: 'Building URLs from endpoint names and moving the client to another route.' },
      { id: 'abort-errors', name: 'abort & error handlers', summary: 'Raising HTTP errors from a view and rendering a custom response for them.' },
      { id: 'sessions', name: 'Sessions', summary: 'Storing per-client state in a signed cookie across requests.' },
      { id: 'app-structure', name: 'App structure & startup', summary: 'template_folder, __name__ == "__main__", and reading command-line arguments at startup.' },
    ],
    learn: [
      { kind: 'text', value: 'A Flask application is a Python object that maps **URLs to functions**. The `@app.route(...)` decorator registers a rule; when a request arrives whose path matches that rule, Flask calls the decorated function (the *view function*) and turns whatever it returns into an HTTP response.' },
      { kind: 'code', lang: 'python', caption: 'The smallest useful Flask app', value: `from flask import Flask, request\n\napp = Flask(__name__)\n\n@app.route('/greet/<string:name>')\ndef greet(name):\n    return "Hello, " + name\n\napp.run(debug=True)` },
      { kind: 'text', value: 'The angle brackets in a rule declare a **variable part**. `<name>` captures one path segment and passes it to the view as a string. A converter narrows what will match:' },
      { kind: 'table', head: ['Converter', 'Matches', 'Passed to the view as'], rows: [
        ['`<name>`', 'One segment, no slashes (the default is `string`)', '`str`'],
        ['`<string:name>`', 'Same as the default', '`str`'],
        ['`<int:id>`', 'One segment of digits only', '`int`'],
        ['`<path:p>`', 'One or more segments — slashes are allowed', '`str`'],
      ]},
      { kind: 'text', value: 'This distinction is worth internalising because papers test it directly: `/details/1001/Michael` matches `<int:id>/<string:name>`, `<string:id>/<string:name>` **and** `<id>/<name>` — a number is also a valid string. But `/home/modules/chapters/one` will only match a rule ending in `<path:...>`, because `<string:...>` refuses to cross a slash.' },
      { kind: 'text', value: 'Query-string data does not come through the rule; it comes through the `request` object. `request.args` is a dictionary-like object of the `?key=value` pairs.' },
      { kind: 'code', lang: 'python', caption: 'Two ways to read a query parameter — with very different failure modes', value: `name = request.args.get('name')          # missing key -> None\nname = request.args.get('name', 'Guest') # missing key -> 'Guest'\nname = request.args['name']              # missing key -> 400 Bad Request` },
      { kind: 'text', value: 'A route with no `methods=` argument accepts **GET only** (and HEAD/OPTIONS, which Flask adds for you). Sending `curl -X POST` to such a route gets `405 Method Not Allowed` — the view never runs, so nothing inside it matters. Papers exploit this repeatedly: they show a view whose body clearly handles a `POST` case, then ask what a POST request returns. The answer is "Method Not Allowed" unless the decorator says `methods=[\'GET\', \'POST\']`.' },
      { kind: 'text', value: '`abort(code)` stops the view immediately and raises an HTTP error. `@app.errorhandler(code)` registers a function to render that error. Note that the handler only fires for the code that was actually raised — an unmatched URL produces 404 from Flask itself, not the 400 your `abort(400)` would produce.' },
      { kind: 'text', value: '`url_for(\'endpoint\', **values)` builds a URL from a view function\'s name. Values that correspond to a variable part of the rule get substituted into the path; **everything left over becomes a query string**. That is the whole trick behind a common exam question: `url_for(\'home\', user="x")` on a rule `/library` gives `/library?user=x`, not `/library/x`.' },
      { kind: 'text', value: 'A session stores per-client data in a cryptographically signed cookie. It needs `app.config[\'SECRET_KEY\']` to be set. `session[\'user\'] = ...` writes, `\'user\' in session` tests, and `session.pop(\'user\', None)` clears.' },
    ],
    keyTerms: [
      { term: 'View function', meaning: 'The Python function a route is bound to. Its return value becomes the response body.' },
      { term: 'URL converter', meaning: 'The `int:`, `string:` or `path:` prefix inside a rule that constrains and types the captured value.' },
      { term: 'request.args', meaning: 'Dict-like access to the query string. `.get()` returns None or a default; `[]` aborts with 400 when the key is missing.' },
      { term: 'abort(code)', meaning: 'Raises an HTTP exception from inside a view, skipping the rest of the function.' },
      { term: 'Endpoint', meaning: 'The name `url_for` uses to identify a route — by default the view function\'s name.' },
      { term: 'SECRET_KEY', meaning: 'The key Flask uses to sign session cookies. Without it, using `session` raises an error.' },
    ],
    commonMistakes: [
      'Assuming a route accepts POST because the view body handles POST. Without `methods=`, only GET is allowed and the response is 405.',
      'Reading `request.args[\'k\']` and expecting `None` for a missing key — that form raises 400 Bad Request.',
      'Expecting `<string:x>` to match a path containing slashes. Only `<path:x>` does.',
      'Expecting `url_for` to place every keyword argument into the path. Arguments that are not part of the rule become query parameters.',
      'Forgetting that Flask redirects `/about` to `/about/` when the rule has a trailing slash, but 404s on `/about/` when the rule does not.',
    ],
    examFocus: [
      'Trace the URL against every rule in the snippet before reading the view bodies — most wrong answers come from picking the right body for the wrong route.',
      'For "which URL returns 200 / throws 404", check the converter first, then the number of segments.',
      'For status-code sequence questions, walk the URLs in order and carry the session state forward between them.',
    ],
  },
  {
    id: 'jinja-templates',
    name: 'Templating',
    blurb: 'Jinja2 and string.Template — rendering, inheritance, macros, filters and control flow.',
    subtopics: [
      { id: 'jinja-basics', name: 'Jinja2 rendering', summary: 'Template objects, render(), render_template() and how variables are substituted.' },
      { id: 'string-template', name: 'string.Template', summary: 'The standard-library templating with $name placeholders, substitute and safe_substitute.' },
      { id: 'inheritance', name: 'Template inheritance', summary: 'extends, block and endblock, and what happens to content placed outside a block.' },
      { id: 'macros-filters', name: 'Macros, filters & control flow', summary: 'macro, for, if, and filters such as length, groupby and title.' },
    ],
    learn: [
      { kind: 'text', value: 'Two different templating systems show up in these papers and they are easy to confuse. **Jinja2** uses `{{ }}` for expressions and `{% %}` for statements. **`string.Template`** from the Python standard library uses `$name` or `${name}`. A template only substitutes the syntax it understands and leaves everything else alone — which is exactly what the trickier questions turn on.' },
      { kind: 'code', lang: 'python', caption: 'The same string run through both engines', value: `from string import Template\nfrom jinja2 import Template as JinjaTemplate\n\ns = "Hello \${user}! Your {{project}} is {{status}}."\ndata = {"user": "Bob", "project": "web app", "status": "done"}\n\nTemplate(s).substitute(data)\n# 'Hello Bob! Your {{project}} is {{status}}.'   <- only $user replaced\n\nJinjaTemplate(s).render(data)\n# 'Hello \${user}! Your web app is done.'         <- only {{ }} replaced` },
      { kind: 'text', value: 'Chaining them — `string.Template` first, then Jinja on the result — replaces both. That "hybrid" pattern is a recurring exam question.' },
      { kind: 'text', value: '`substitute()` raises `KeyError` if any placeholder in the template has no value in the mapping. `safe_substitute()` never raises: an unmatched placeholder is left in the output verbatim. Extra keys in the mapping are harmless for both.' },
      { kind: 'code', lang: 'python', value: `t = Template("The \$animal jumped over the \$obstacle.")\n\nt.substitute({"animal": "cat"})        # KeyError: 'obstacle'\nt.safe_substitute({"animal": "cat"})  # 'The cat jumped over the \$obstacle.'\nt.safe_substitute({"obstacle": "wall", "place": "park"})  # fine, extra key ignored` },
      { kind: 'text', value: '**Template inheritance.** A child template starts with `{% extends "base.html" %}`. Only content inside a `{% block %}` that the parent also declares is rendered — anything the child puts outside a block is silently dropped. That is the single most common "why is my text missing?" question in this course.' },
      { kind: 'code', lang: 'jinja', caption: 'base.html declares the block; home.html must fill it', value: `{# base.html #}\n<html><body>\n  <h2>Diploma Courses</h2>\n  {% block content %}{% endblock %}\n</body></html>\n\n{# home.html - correct #}\n{% extends "base.html" %}\n{% block content %}\n  <p>MAD I</p>\n{% endblock %}\n\n{# home.html - the <h1> never appears #}\n{% extends "base.html" %}\n<h1>Welcome!</h1>` },
      { kind: 'text', value: 'The parent\'s own markup still renders. So the output is the base page **plus** the block content, in the order the base lays them out — not the child content alone.' },
      { kind: 'text', value: '**Macros** are reusable template functions: `{% macro name(args) %}...{% endmacro %}`, invoked with `{{ name(value) }}`. **Filters** transform a value with `|`: `item|length`, `Products|groupby(\'producer\')`, `level.title()`.' },
      { kind: 'text', value: '`groupby` returns group objects with two attributes: `.grouper` (the shared value) and `.list` (the members). Iterating a groupby result and printing `product.product_id` will not work — you need a second, inner loop over `.list`. Note also that Jinja\'s `groupby` **sorts by the grouping key**, so the output order is alphabetical by group, not source order.' },
    ],
    keyTerms: [
      { term: '{{ ... }}', meaning: 'Jinja expression — evaluated and inserted into the output.' },
      { term: '{% ... %}', meaning: 'Jinja statement — for, if, block, macro, extends. Produces no output itself.' },
      { term: 'substitute vs safe_substitute', meaning: 'The first raises KeyError on a missing placeholder; the second leaves the placeholder text in place.' },
      { term: 'block', meaning: 'A named, overridable region declared in a parent template and filled by a child.' },
      { term: 'groupby', meaning: 'A Jinja filter that returns groups with `.grouper` and `.list`, sorted by the grouping key.' },
    ],
    commonMistakes: [
      'Putting content in a child template outside `{% block %}` and expecting it to render. It is dropped.',
      'Expecting `render_template` to find a template in `templates/` after passing `template_folder=` to `Flask()` — that argument replaces the folder, it does not add one.',
      'Using `substitute()` where the data is incomplete. Use `safe_substitute()` if a missing key must not raise.',
      'Iterating a `groupby` result as if each item were a record. Each item is a group; the records live in `.list`.',
      'Forgetting that the base template\'s own headings appear in the rendered output, above or around the block.',
    ],
    examFocus: [
      'Read the base template first and note exactly which blocks exist; then check whether the child\'s content is inside one.',
      'For `$`/`{{ }}` mixing questions, mark each placeholder with which engine owns it before choosing.',
      'For a `{% if %}` inside a `{% for %}`, evaluate the condition against every item — the answer is usually the filtered subset.',
    ],
  },
  {
    id: 'html-css',
    name: 'HTML & CSS',
    blurb: 'Document structure, selector specificity, the display model, forms and validation.',
    subtopics: [
      { id: 'html-structure', name: 'HTML structure & semantics', summary: 'Documents, block vs inline elements, links and navigation.' },
      { id: 'css-specificity', name: 'Selectors & specificity', summary: 'Which rule wins when several target the same element, including !important and inline styles.' },
      { id: 'display-box', name: 'Display & box model', summary: 'display: block vs inline vs inline-block, borders, widths and margins.' },
      { id: 'forms-validation', name: 'Forms & client-side validation', summary: 'Form submission methods and the :valid / :invalid pseudo-classes.' },
    ],
    learn: [
      { kind: 'text', value: 'Two ideas carry almost every HTML/CSS question in these papers: **the cascade** (which rule wins) and **the display model** (whether an element starts a new line).' },
      { kind: 'text', value: 'When several declarations target the same element and property, the winner is decided in this order:' },
      { kind: 'list', ordered: true, items: [
        'A declaration marked `!important` beats one that is not, whatever its selector.',
        'Otherwise, higher specificity wins: inline `style=""` > `#id` > `.class` > `element`.',
        'Only if specificity ties does source order decide — and then the **last** rule wins.',
      ]},
      { kind: 'text', value: 'This produces two statements that look symmetric but are not. If an element is styled by *both* an id selector and a class selector, the id wins no matter which came last — specificity is decided before order. If an element belongs to *two classes* and both style the same property, specificity ties, so the one written later in the stylesheet wins. A question in Paper 6 turns exactly on that asymmetry.' },
      { kind: 'code', lang: 'css', caption: 'Order only breaks ties', value: `#box { color: blue; }     /* wins: id beats class ... */\n.box { color: red; }      /* ... even though this is later */\n\n.a { color: green; }\n.b { color: purple; }     /* wins over .a: same specificity, written later */` },
      { kind: 'text', value: 'An `!important` in an external stylesheet beats an inline `style=""` that is *not* important, because `!important` is evaluated before specificity. That single rule explains most "which rendering is correct?" screenshots.' },
      { kind: 'text', value: '**Display.** `<div>`, `<p>`, `<h1>`-`<h6>`, `<ul>`, `<form>` are block-level: each starts on a new line and fills the available width. `<span>`, `<a>`, `<strong>`, `<em>`, `<img>`, `<input>`, `<label>` are inline: they sit in the text flow and ignore `width`/`height`. `display: inline-block` gives an element a box you can size while keeping it in the flow, so adjacent inline-blocks sit side by side.' },
      { kind: 'text', value: 'Setting `display: block` on a `<span>` makes it behave like a `<div>` — each one on its own line, honouring `width`. Setting `display: inline-block` lets it take a width but stay beside its neighbours.' },
      { kind: 'text', value: '**Forms.** A `<form>` with no `method` attribute submits with **GET**, appending the fields to the URL as a query string. That is why sensitive data must never go through a default form: the values land in the address bar, in browser history, and in server logs. `POST` puts them in the request body instead — not encrypted, but not in the URL.' },
      { kind: 'text', value: '**Client-side validation** is a convenience, never a security control. `minlength`, `maxlength`, `required` and `type="email"` drive the `:valid` and `:invalid` pseudo-classes, so CSS can colour an input live as the user types. All of it can be bypassed by anyone sending the request directly, so the server must validate too.' },
      { kind: 'code', lang: 'html', caption: 'Live validation styling', value: `<style>\n  input:valid   { background: green; }\n  input:invalid { background: red; }\n</style>\n<input type="text" minlength="5" maxlength="8" value="a">` },
      { kind: 'text', value: 'Typing into that box: the value is invalid (too short) until it reaches 5 characters, then valid. `maxlength` **prevents** further typing rather than making the value invalid, so it never turns red again — a distinction Paper 8 tests directly.' },
    ],
    keyTerms: [
      { term: 'Specificity', meaning: 'The weight of a selector: inline > id > class > element. Decided before source order.' },
      { term: '!important', meaning: 'Overrides specificity entirely. Evaluated first in the cascade.' },
      { term: 'Block element', meaning: 'Starts on a new line and takes the full available width.' },
      { term: 'Inline element', meaning: 'Flows with surrounding text and ignores width/height.' },
      { term: 'inline-block', meaning: 'Sizeable like a block, but stays on the same line as its neighbours.' },
      { term: ':valid / :invalid', meaning: 'Pseudo-classes that match an input according to its HTML5 validation constraints.' },
    ],
    commonMistakes: [
      'Assuming the last rule always wins. Source order only breaks ties between equal specificity.',
      'Assuming an inline `style=""` always wins. An `!important` declaration elsewhere beats it.',
      'Treating `<span>` as block-level. It is inline until CSS says otherwise.',
      'Believing client-side validation makes server-side validation unnecessary.',
      'Writing `border-colour` or `stroke` in CSS. The property is `border`, and the spelling is `color`.',
    ],
    examFocus: [
      'For a "which screenshot is correct?" question, resolve colours first (cascade), then layout (display) — the options usually differ on both.',
      'List the selectors targeting each element and rank them before looking at the pictures.',
      'For form questions, check for a `method` attribute. Absent means GET.',
    ],
  },
  {
    id: 'javascript-web',
    name: 'JavaScript & the Browser',
    blurb: 'DOM manipulation, what the browser does versus the server, web components and WebAssembly.',
    subtopics: [
      { id: 'browser-vs-server', name: 'Browser vs server responsibilities', summary: 'Which parts of a page-load are the client\'s job and which are the server\'s.' },
      { id: 'web-platform', name: 'Web components & WebAssembly', summary: 'Custom Elements, Shadow DOM, HTML Templates, and what WebAssembly and Emscripten are.' },
    ],
    learn: [
      { kind: 'text', value: 'JavaScript reaches the page through the **DOM**: `document.getElementById("x")` returns an element object whose `.style` property exposes CSS as JavaScript properties.' },
      { kind: 'text', value: 'The naming rule matters more than it looks: CSS `font-weight` becomes JavaScript `style.fontWeight` — hyphens become camelCase. And `.style` itself is an object, not a string, so `element.style = "bold"` does nothing useful; you must assign to a specific property.' },
      { kind: 'code', lang: 'javascript', caption: 'The only form that works', value: `function doSomething() {\n  var txt1 = document.getElementById("txt1");\n  txt1.style.fontWeight = "bold";\n}\n\n// equivalently, in one line:\ndocument.getElementById("txt1").style.fontWeight = "bold";\n\n// these do NOT work:\n// txt1.style = "bold";              <- assigning to the style object\n// txt1.style.font-weight = "bold";  <- invalid JS identifier` },
      { kind: 'text', value: '**Browser versus server.** Parsing HTML, executing JavaScript, applying CSS, and auto-filling saved form data are all done by the browser. The Flask server only produces the bytes; it never sees a click, never runs your JavaScript, and has no idea what the page looks like. URL routing, on the other hand, is the server\'s job — it decides which view answers a path.' },
      { kind: 'text', value: '**Web components** are a browser standard made of three pieces: *Custom Elements* (define your own tag), *Shadow DOM* (an encapsulated subtree with its own styles), and *HTML Templates* (`<template>` markup that is parsed but not rendered until cloned). WebAssembly is not one of them — it is a separate bytecode format that lets languages like C and C++ run in the browser at near-native speed. **Emscripten** is the toolchain that compiles C/C++ to WebAssembly.' },
    ],
    keyTerms: [
      { term: 'DOM', meaning: 'The browser\'s live object model of the document, which script can read and modify.' },
      { term: 'style.fontWeight', meaning: 'The JavaScript name for the CSS `font-weight` property — hyphenated CSS names become camelCase.' },
      { term: 'Custom Elements', meaning: 'The web-components API for defining new HTML tags with their own behaviour.' },
      { term: 'Shadow DOM', meaning: 'An encapsulated DOM subtree whose styles do not leak in or out.' },
      { term: 'WebAssembly', meaning: 'A portable bytecode the browser can run at near-native speed. Not a web component.' },
      { term: 'Emscripten', meaning: 'A toolchain that compiles C/C++ source into WebAssembly.' },
    ],
    commonMistakes: [
      'Assigning to `element.style` directly instead of to a property on it.',
      'Writing the CSS property name with a hyphen in JavaScript.',
      'Counting URL routing as browser work — it is the server\'s.',
      'Listing WebAssembly among the web components.',
    ],
    examFocus: [
      'For DOM options, eliminate on syntax first: any option assigning to `.style` as a whole, or using a hyphen, is out.',
      'For "browser or server?" questions, ask whether the work needs the page — if it does, it is the browser.',
    ],
  },
  {
    id: 'databases',
    name: 'Databases & SQLAlchemy',
    blurb: 'Models, relationships, the session, queries, raw SQL and reading ER diagrams.',
    subtopics: [
      { id: 'models-columns', name: 'Models & columns', summary: 'Declaring tables as Python classes, and how column arguments map to SQL constraints.' },
      { id: 'relationships', name: 'Relationships & cardinality', summary: 'Foreign keys, relationship(), backref, and telling one-to-one from one-to-many.' },
      { id: 'session', name: 'The session', summary: 'add, add_all, commit, and what is actually persisted when.' },
      { id: 'queries', name: 'Queries & updates', summary: 'query.filter_by, .all(), .first(), first_or_404(), and updating rows in place.' },
      { id: 'sql-er', name: 'SQL & ER diagrams', summary: 'Which statements change server state, and reading cardinality off a crow\'s-foot diagram.' },
    ],
    learn: [
      { kind: 'text', value: 'Flask-SQLAlchemy is an **ORM**: it maps Python classes to database tables and instances to rows, so you write Python instead of SQL. A model subclasses `db.Model`; each `db.Column` is a column.' },
      { kind: 'code', lang: 'python', caption: 'A one-to-many relationship', value: `class Library(db.Model):\n    id   = db.Column(db.Integer(), primary_key=True)\n    name = db.Column(db.String(), unique=True)\n\nclass Book(db.Model):\n    id      = db.Column(db.Integer(), primary_key=True)\n    name    = db.Column(db.String(), unique=True)\n    library = db.Column(db.Integer(), db.ForeignKey("library.id"))` },
      { kind: 'text', value: '**Reading cardinality from a schema** is a recurring 3-mark question, and the rule is short: the table holding the foreign key is the "many" side. A plain `ForeignKey` gives one-to-many. Add `unique=True` to that foreign-key column and it becomes one-to-one, because no two rows may point at the same parent.' },
      { kind: 'text', value: 'And if the foreign key names a table that does not exist in the snippet — say `Project.course` references `"course.id"` when the models are `Student` and `Project` — then the two classes shown are simply not related to each other. Read the target of the `ForeignKey`, not just its presence.' },
      { kind: 'text', value: '`db.relationship("Book", backref="library")` adds a Python-side attribute. `relationship` goes on the "one" side; the `ForeignKey` column goes on the "many" side. `backref` creates the reverse attribute on the other class automatically. `lazy=\'dynamic\'` makes the relationship return a query object you can filter further instead of a loaded list.' },
      { kind: 'text', value: '**The session** is a staging area. `db.session.add(obj)` marks an object to be written; `db.session.commit()` writes everything staged so far and clears the staging area. Anything added *after* the last commit is not in the database — but it is still in Python, so an in-process `query.all()` may return it via the session\'s identity map even though the row was never persisted. Papers test exactly this gap between "printed in the terminal" and "in the database file".' },
      { kind: 'code', lang: 'python', caption: 'Two rows persisted, three objects visible', value: `db.session.add(material1)   # Steel\ndb.session.add(material2)   # Iron\ndb.session.commit()         # <- Steel and Iron are now in the DB\ndb.session.add(material3)   # Aluminium: staged, never committed\n\nprint([(x.m_id, x.name) for x in Material.query.all()])\n# prints all three; the database file contains two` },
      { kind: 'text', value: 'Mutating an object that came from a query and then calling `commit()` writes the change — you do not need `add()` again. But `staff.Salary = 6000` sets the salary; `staff.Salary += 6000` adds to it. When a question says "increase their salaries to 6000", only the assignment form is correct.' },
      { kind: 'text', value: '`query.filter_by(...)` takes keyword arguments and returns a query. `.all()` gives a list, `.first()` gives one object or `None`, and `.first_or_404()` gives one object or raises a 404 — which is the idiomatic way to make a missing record produce a 404 page.' },
      { kind: 'text', value: '**Raw SQL.** Statements that change server state are the DDL/DML ones: `CREATE`, `INSERT`, `UPDATE`, `DELETE`, `DROP`. `SELECT` only reads, however complicated its `WHERE` clause.' },
      { kind: 'text', value: '**ER diagrams** use crow\'s-foot notation at each end of a line. A crow\'s foot (the three-pronged fork) means "many"; a single bar means "one". A circle next to it means "zero is allowed" (optional); a second bar means "at least one" (mandatory). Read each end separately — the two ends are independent.' },
    ],
    keyTerms: [
      { term: 'ORM', meaning: 'Object-Relational Mapping: Python classes stand in for tables, instances for rows.' },
      { term: 'ForeignKey', meaning: 'A column referencing another table\'s primary key. The table holding it is the "many" side.' },
      { term: 'relationship / backref', meaning: 'The Python-side navigation attribute, and the automatically created reverse attribute.' },
      { term: 'lazy=\'dynamic\'', meaning: 'Makes a relationship return a query object that can be filtered, rather than a loaded list.' },
      { term: 'db.session.commit()', meaning: 'Writes everything staged since the last commit. Objects added after it are not persisted.' },
      { term: 'first_or_404()', meaning: 'Returns the first match, or raises a 404 if there is none.' },
      { term: 'cascade="all, delete"', meaning: 'Deleting the parent also deletes the related child rows.' },
    ],
    commonMistakes: [
      'Reading `unique=True` on a foreign key as decoration. It is what turns one-to-many into one-to-one.',
      'Assuming `query.all()` reflects the database file. Uncommitted objects can still appear in the same process.',
      'Using `+=` where the question asks to set a value to a number.',
      'Assuming a `ForeignKey` relates the two classes shown without checking which table it points at.',
      'Counting `SELECT` as a statement that changes server state.',
    ],
    examFocus: [
      'For cardinality questions: find the ForeignKey, check its target table, then check for `unique=True`. That is the whole answer.',
      'For session questions, mark the position of every `commit()` and split the operations around it.',
      'For ER diagrams, read the symbol at each end separately and translate it into a sentence before looking at the options.',
    ],
  },
  {
    id: 'rest-apis',
    name: 'REST APIs',
    blurb: 'flask_restful resources, request parsing, marshalling, curl and status codes.',
    subtopics: [
      { id: 'resources-routing', name: 'Resources & add_resource', summary: 'Mapping a Resource class to one or more URLs and matching method signatures.' },
      { id: 'reqparse-json', name: 'Request parsing', summary: 'reqparse.RequestParser versus request.args and request.json.' },
      { id: 'marshalling', name: 'Marshalling output', summary: 'fields, marshal and @marshal_with for shaping a response.' },
      { id: 'status-curl', name: 'Status codes & curl', summary: 'What a request returns, and the curl flags used to send it.' },
      { id: 'rest-principles', name: 'REST principles & OpenAPI', summary: 'Statelessness, the client-server split, and where endpoints live in an OpenAPI document.' },
    ],
    learn: [
      { kind: 'text', value: '`flask_restful` layers a class-based API over Flask. A `Resource` subclass gets one method per HTTP verb: `get`, `post`, `put`, `delete`. `api.add_resource(MyResource, "/path")` binds it; you may pass several URLs to bind them all to the same class.' },
      { kind: 'text', value: 'The rule that generates most exam questions is the **method signature must match the URL**. If a URL contains `<int:todo_id>`, then every method that URL can reach must accept a `todo_id` parameter. Bind `TodoSimple` (whose `get(self, todo_id)` requires it, but whose `put(self)` does not) to both `/api/<int:todo_id>` and `/api`, and a GET on `/api` or a PUT on `/api/5` fails with a signature error.' },
      { kind: 'code', lang: 'python', caption: 'Signature mismatch is a runtime error, not a 404', value: `class StudentResource(Resource):\n    def get(self, student_id=None): ...   # optional -> works with or without\n    def post(self): ...                    # no id -> URL must have no id\n    def delete(self, student_id): ...      # required -> URL must supply it\n\napi.add_resource(StudentResource, '/students', '/students/<int:student_id>')\n\n# curl -X DELETE /students     -> error: delete() missing student_id\n# curl -X POST   /students/123 -> error: post() got unexpected student_id` },
      { kind: 'text', value: '**Three ways to read input, and they disagree.** `request.args` reads the query string. `request.json` reads a JSON body. `reqparse.RequestParser().parse_args()` looks in several places — and by default the JSON body wins over the query string for the same key. When one request carries both `?val=soccer` and a body `{"val": "tennis"}`, the parser returns `tennis` while `request.args["val"]` returns `soccer`; the path variable is a third, independent value.' },
      { kind: 'text', value: '**Marshalling** shapes the response. Define a `fields` dict, then either decorate the method with `@marshal_with(output)` or call `marshal(obj, output)` on the return value. The decorator goes on the *method*, not the class — putting it above `class Userapi(Resource):` does not work.' },
      { kind: 'text', value: '**Status codes worth knowing cold:** 200 OK; 201 Created (a successful POST that made something); 204 No Content (a successful DELETE with nothing to return); 400 Bad Request; 401 Unauthorized; 404 Not Found; 405 Method Not Allowed (the route exists but not for that verb); 422 Unprocessable Entity.' },
      { kind: 'text', value: '**curl flags:** `-X` sets the method, `-H` adds a header, `-d` sends a body, `--head` fetches headers only. A `-d` payload with no `-X` implies POST.' },
      { kind: 'text', value: '**Statelessness** means the server keeps no memory of previous requests from a client: every request must carry everything needed to answer it. The benefit is that any server can answer any request; the cost is repetition, since context travels with each request. A *stateful* server, by contrast, answers based on the state it retained — which is why session affinity and larger repeated payloads become a concern.' },
      { kind: 'text', value: 'In an **OpenAPI** document, the `paths` object holds every endpoint of the API. `info` carries the title and version, `schema`/`components` carry data shapes, and `responses` sits inside an individual operation.' },
    ],
    keyTerms: [
      { term: 'Resource', meaning: 'A flask_restful class whose methods are named after HTTP verbs.' },
      { term: 'add_resource', meaning: 'Binds a Resource to one or more URL rules.' },
      { term: 'reqparse', meaning: 'flask_restful\'s request parser. Looks in JSON body and query string; the body wins on conflict.' },
      { term: 'marshal / @marshal_with', meaning: 'Shapes a Python object into the declared output fields. The decorator belongs on a method.' },
      { term: '201 Created', meaning: 'A POST succeeded and created a resource.' },
      { term: '204 No Content', meaning: 'The request succeeded and there is deliberately no body — typical for DELETE.' },
      { term: '405 Method Not Allowed', meaning: 'The URL exists but does not accept that HTTP verb.' },
      { term: 'Stateless', meaning: 'The server retains nothing between requests; each request carries its own context.' },
    ],
    commonMistakes: [
      'Binding a Resource to a URL whose variables its methods do not accept.',
      'Assuming `reqparse` and `request.args` return the same value when the request carries both a body and a query string.',
      'Putting `@marshal_with` above the class instead of above the method.',
      'Returning 200 from a creating POST where the code explicitly returns 201.',
      'Reading "stateless" as "the server has no data". It means no retained *client* state between requests.',
    ],
    examFocus: [
      'For "which curl throws an error?", line up each URL against the bound rules and each verb against the method signatures.',
      'For output-value questions, track each of the three input channels separately before reading the options.',
      'For status-code lists, answer each request independently — they rarely follow a pattern.',
    ],
  },
  {
    id: 'testing',
    name: 'Testing',
    blurb: 'pytest collection, selection by name and marker, coverage criteria and testing levels.',
    subtopics: [
      { id: 'pytest-collection', name: 'pytest collection', summary: 'Which functions and classes pytest actually treats as tests.' },
      { id: 'selection', name: 'Selecting tests: -k and -m', summary: 'Filtering by substring of the name versus by registered marker.' },
      { id: 'fixtures', name: 'Fixtures & the Flask test client', summary: 'Providing setup to tests, and testing routes without a live server.' },
      { id: 'coverage', name: 'Coverage criteria', summary: 'Statement, branch, condition and function coverage, and what each implies.' },
      { id: 'testing-levels', name: 'Levels of testing', summary: 'Unit, integration, system, automation, acceptance and regression testing.' },
    ],
    learn: [
      { kind: 'text', value: 'pytest **collects** a function as a test only if its name starts with `test_`, and a class only if its name starts with `Test`. Inside a collected class, again only `test_`-prefixed methods count. So in a class containing `test_case1`, `case_test2` and `case_test3`, exactly one test is collected — the other two are ordinary methods, invisible to pytest and never run.' },
      { kind: 'text', value: 'That single rule answers a family of questions. Two classes `Test_class0` and `Test_class1`, each with one `test_`-prefixed method among several, yield **2 tests**, not 6.' },
      { kind: 'text', value: '`-k EXPR` selects by **substring of the test\'s name/path**; the rest are reported as *deselected*. `-m MARKER` selects by a marker registered with `@pytest.mark.name`; unregistered markers additionally produce warnings, which is why `1 passed, 3 deselected, 4 warnings` is a giveaway that `-m` was used with ad-hoc markers.' },
      { kind: 'code', lang: 'shell', caption: 'Reading a pytest summary backwards', value: `pytest test_file.py -k Test_class\n# == 2 passed in 0.07s ===        <- no "deselected": everything collected matched\n\npytest test_file.py -m marker2\n# 1 passed, 3 deselected, 4 warnings   <- marker selection, 4 unregistered markers\n\npytest math_tests.py -m "not slow"\n# selects everything not marked slow` },
      { kind: 'text', value: 'Marker expressions support `not`, `and`, `or`: `-m "slow and integration"` needs both. Watch for a test that carries two markers — it is selected by either one.' },
      { kind: 'text', value: 'A **fixture** is a function decorated with `@pytest.fixture` whose return value is injected into any test that names it as a parameter. Flask\'s test client (`app.test_client()`) lets you call routes without running a server; `client.get("/path")` returns a response you can assert on. Testing against a *live* server with `requests` also works, but then the server has to actually be running.' },
      { kind: 'text', value: '**Coverage criteria**, weakest to strongest for the code `if ((x > 0) && (y > 0)) { z = x; }`:' },
      { kind: 'table', head: ['Criterion', 'What it demands', 'Satisfied by'], rows: [
        ['Function coverage', 'Every function is called at least once', 'Any single call'],
        ['Statement coverage', 'Every line executes at least once', '`foo(1,1)` — takes the true branch'],
        ['Branch coverage', 'Every branch is taken both ways', '`foo(1,1)` and `foo(1,0)`'],
        ['Condition coverage', 'Every sub-condition is both true and false', '`foo(0,1)` and `foo(1,0)`'],
      ]},
      { kind: 'text', value: 'The implication direction is the trap: 100% statement coverage does **not** imply 100% branch coverage (an `if` with no `else` reaches every statement without ever taking the false branch), and it does not imply condition coverage either. Neither implication holds.' },
      { kind: 'text', value: '**Levels of testing.** Unit testing exercises the smallest logical units — individual functions or methods. Integration testing checks that several components work together. System testing takes the whole application in a full environment, one step beyond integration. System test automation scripts the browser to simulate real user interaction. User acceptance testing is real users verifying the product before release — beta testing. Regression testing runs after every change to confirm nothing previously working has broken.' },
    ],
    keyTerms: [
      { term: 'Collection', meaning: 'pytest\'s discovery of tests: `test_*` functions, `Test*` classes.' },
      { term: '-k', meaning: 'Select tests whose name matches a substring expression. Non-matching tests are deselected.' },
      { term: '-m', meaning: 'Select tests carrying a given `@pytest.mark` marker. Supports not/and/or.' },
      { term: 'deselected', meaning: 'Collected but filtered out by -k or -m. Distinct from "skipped".' },
      { term: 'Fixture', meaning: 'A `@pytest.fixture` function whose result is injected into tests that name it.' },
      { term: 'Branch coverage', meaning: 'Every branch of every decision has been taken in both directions.' },
      { term: 'Condition coverage', meaning: 'Every atomic sub-condition has evaluated both true and false.' },
      { term: 'Regression testing', meaning: 'Re-running tests after a change to confirm nothing already working broke.' },
    ],
    commonMistakes: [
      'Counting `case_test2` as a test. The prefix must be `test_`.',
      'Confusing "deselected" with "failed" or "skipped" when reading a summary.',
      'Believing 100% statement coverage implies branch or condition coverage. It implies neither.',
      'Using `-k` where the question\'s output shows marker warnings, or `-m` where it shows none.',
      'Forgetting that a test module without a running server cannot make real HTTP requests succeed.',
    ],
    examFocus: [
      'Count the collected tests first, on the naming rules alone. That usually eliminates two options.',
      'Read the summary line for the words "deselected" and "warnings" — they tell you whether -k or -m was used.',
      'For coverage matching, work out the minimum input set for each criterion rather than reasoning about the options.',
    ],
  },
  {
    id: 'python-cli',
    name: 'Python, CLI & Logging',
    blurb: 'Command-line arguments, decorators, mutable defaults and the logging module.',
    subtopics: [
      { id: 'sys-argv', name: 'Command-line arguments', summary: 'How sys.argv is indexed and what quoting does to it.' },
      { id: 'decorators', name: 'Decorators & closures', summary: 'Wrapping a function, and what the wrapper actually returns.' },
      { id: 'logging', name: 'The logging module', summary: 'Levels, basicConfig, and which messages are emitted.' },
    ],
    learn: [
      { kind: 'text', value: '`sys.argv` is a list of strings. **`sys.argv[0]` is the script name**, so the first user argument is `sys.argv[1]`. Everything in it is a string, always — `int(sys.argv[1])` is how you get a number.' },
      { kind: 'code', lang: 'shell', value: `python app.py 8080\n# sys.argv == ['app.py', '8080']\n\npython app.py "Application Development" DBMS\n# sys.argv == ['app.py', 'Application Development', 'DBMS']\n\npython app.py Application Development DBMS\n# sys.argv == ['app.py', 'Application', 'Development', 'DBMS']   <- three arguments` },
      { kind: 'text', value: 'Quoting is the difference between one argument containing a space and two arguments. Papers pair a command with a URL and ask which combination produces a given page, and the quoting is usually what separates the right option from the wrong one.' },
      { kind: 'text', value: 'A common defensive idiom reads an optional argument with a fallback: `port = int(sys.argv[1]) if len(sys.argv) > 1 else 5000`. Reading `sys.argv[1]` without that guard raises `IndexError` when the argument is absent.' },
      { kind: 'text', value: '**Decorators.** `@dec` above `def f` means `f = dec(f)`. Whatever `dec` returns *becomes* `f`, so the wrapper\'s return value is the function\'s return value and the wrapper\'s parameters are the function\'s parameters.' },
      { kind: 'code', lang: 'python', caption: 'Trace the wrapper, not the original', value: `def decor(func):\n    def wrapper(x):\n        y = func(x)\n        return x * y\n    return wrapper\n\n@decor\ndef output(x, optional="hello world!"):\n    return x, optional\n\nprint(output(5))\n# output(5) is wrapper(5): y = (5, 'hello world!'), returns 5 * that tuple\n# -> (5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!', 5, 'hello world!')` },
      { kind: 'text', value: 'Multiplying a tuple by an integer repeats it — that is ordinary Python, not a decorator quirk, but the decorator is what puts a tuple where you expected a number. Note too that the decorator replaces the signature: `output` now takes exactly the parameters `wrapper` declares, so the default argument is unreachable from the call site.' },
      { kind: 'text', value: 'The **mutable default argument** is the other decorator-adjacent trap. `def f(x, list=[])` evaluates `[]` **once**, when the function is defined — so the same list is reused on every call and accumulates. Wrapping the function so the wrapper passes a fresh `[]` each time hides the bug; commenting out the decorator exposes it.' },
      { kind: 'text', value: '**Logging.** `logging.basicConfig(level=...)` sets the threshold: messages below it are discarded. The order is `DEBUG < INFO < WARNING < ERROR < CRITICAL`. With `level=logging.WARNING`, calls to `logging.debug()` and `logging.info()` produce nothing at all.' },
      { kind: 'text', value: 'So for a script configured at `WARNING` that logs `info` on success and hits no error path, the terminal output is *nothing* — an answer option often phrased as "None of these". `basicConfig` also accepts `filename=` to write to a file instead of the console, and `format=` to control the layout. Note that `logging.basicConfig(...)` is the function; `logging(...)` is not callable.' },
    ],
    keyTerms: [
      { term: 'sys.argv[0]', meaning: 'The script name. User arguments start at index 1.' },
      { term: 'IndexError', meaning: 'Raised by reading past the end of sys.argv when an expected argument is missing.' },
      { term: 'Decorator', meaning: '`@dec` rebinds the name to `dec(f)`. The wrapper replaces the function, signature and all.' },
      { term: 'Mutable default', meaning: 'A default like `[]` is created once at definition time and shared across calls.' },
      { term: 'basicConfig(level=...)', meaning: 'Sets the minimum severity that will be emitted.' },
      { term: 'Log level order', meaning: 'DEBUG < INFO < WARNING < ERROR < CRITICAL.' },
    ],
    commonMistakes: [
      'Treating `sys.argv[0]` as the first user argument.',
      'Forgetting that everything in `sys.argv` is a string.',
      'Reading the decorated function\'s body and ignoring the wrapper that replaced it.',
      'Expecting `logging.info` output when the level is set to WARNING.',
      'Assuming an unquoted multi-word argument arrives as one string.',
    ],
    examFocus: [
      'Write out `sys.argv` as an explicit list before evaluating any indexing.',
      'For decorator questions, rewrite the call as `wrapper(args)` and trace from there.',
      'For logging output questions, check the configured level before reading any log call.',
    ],
  },
  {
    id: 'web-fundamentals',
    name: 'Web & System Fundamentals',
    blurb: 'HTTP, client-server, URLs, bandwidth and latency arithmetic, storage and cloud models.',
    subtopics: [
      { id: 'http-messages', name: 'HTTP requests & responses', summary: 'Methods, headers, and reading a response head.' },
      { id: 'url-anatomy', name: 'URL anatomy', summary: 'Protocol, domain, sub-domain, path and parameters.' },
      { id: 'bandwidth-latency', name: 'Bandwidth & latency', summary: 'Turning a rate and a time into a volume, and a distance into a round-trip.' },
      { id: 'storage-hardware', name: 'Storage & hardware', summary: 'Disk rotation, DRAM bandwidth and cold storage trade-offs.' },
      { id: 'addressing', name: 'Addressing & encoding', summary: 'Converting an IPv4 address to hexadecimal.' },
      { id: 'cloud-models', name: 'Cloud service models', summary: 'IaaS, PaaS and SaaS, and which products are which.' },
      { id: 'markup-standards', name: 'Markup standards', summary: 'How HTML5, XHTML, XML and SGML relate.' },
    ],
    learn: [
      { kind: 'text', value: '**A URL, part by part.** In `https://seek.study.iitm.ac.in/courses/ns_23t3_cs2003?type=lesson&tab=courses`: the protocol is `https`; the sub-domain is `seek`; the domain is `study.iitm.ac.in`; the path is `/courses/ns_23t3_cs2003`; the parameters are `?type=lesson&tab=courses`. The sub-domain is the label in front of the registered domain — the leftmost part, not the rightmost.' },
      { kind: 'text', value: '**Reading an HTTP response head.** `curl --head URL` fetches only the headers. The first line (`HTTP/2 200`) carries the status — that is what tells you the request succeeded. `content-type: text/html; charset=utf-8` gives the MIME type of the body (`text/html`), with the character encoding as a parameter of it rather than the type itself.' },
      { kind: 'text', value: '**Bandwidth arithmetic.** Network rates are quoted in **bits** per second; file sizes in **bytes**. Divide by 8 to move from bits to bytes.' },
      { kind: 'code', lang: 'text', caption: 'A 10 MB download at 5 Mbps', value: `10 MB = 80 Mb (megabits)\n80 Mb / 5 Mbps = 16 seconds` },
      { kind: 'text', value: 'When a bandwidth graph shows a rate held over an interval, the data for that interval is rate x time, and the total is the sum over the intervals — the area under the curve. Convert once at the end: `Mb/s x 3600 s = Mb`, then `/8` for MB, then `/1000` for GB.' },
      { kind: 'text', value: '**Latency.** One-way time is distance / speed. A **round trip** doubles it. When a route has two segments through different media, compute each segment separately and add — the media have different propagation speeds.' },
      { kind: 'code', lang: 'text', caption: 'Round trip over two media', value: `9000 km cable at 1.5e8 m/s  ->  9e6 / 1.5e8 = 0.06 s   one way\n9000 km air   at 3e8   m/s  ->  9e6 / 3e8   = 0.03 s   one way\none way total = 0.09 s   ->  round trip = 0.18 s = 180 ms` },
      { kind: 'text', value: 'If each request must wait for the previous response, the number of requests per second is `1 / RTT`. Halving the speed of light doubles the RTT and so halves that count; doubling the distance does the same.' },
      { kind: 'text', value: '**Disk latency.** A disk at *R* rpm completes a revolution in `60 / R` seconds. Having missed the data by *d* degrees, you wait for the remaining `360 - d` degrees: `(360 - d)/360 x 60/R`. For a rotating disk read at *B* bits per second with *n* bits per revolution, the maximum spin rate that does not outrun the reader is `B/n` revolutions per second, or `60B/n` rpm.' },
      { kind: 'text', value: '**DRAM bandwidth** is `bus width (bytes) x clock rate x transfers per cycle`. A 64-bit bus is 8 bytes; DDR moves two values per cycle; so at 2 GHz that is `8 x 2 x 2 = 32 GB/s`.' },
      { kind: 'text', value: '**IPv4 to hexadecimal**: convert each octet to two hex digits independently and concatenate. `172.16.254.10` gives `AC`, `10`, `FE`, `0A` — that is `AC10 FE0A`.' },
      { kind: 'text', value: '**Cold storage** such as Amazon Glacier trades retrieval speed for price: low cost and high durability, but retrieval latency measured in hours.' },
      { kind: 'text', value: '**Cloud service models.** IaaS gives you raw infrastructure (AWS). PaaS gives you a managed environment to deploy code into, with the languages and frameworks maintained for you (Replit). SaaS gives you the finished application (Office 365). Large providers such as Microsoft Azure offer several of these at once.' },
      { kind: 'text', value: '**Markup standards.** SGML is the ancestor. XML is a simplified SGML, and is both human- and machine-readable. XHTML is HTML reformulated as XML, so it inherits from SGML through XML. HTML5, by contrast, is *not* defined in terms of SGML — it has its own parsing specification — and it was deliberately designed to stay backwards compatible with older HTML.' },
    ],
    keyTerms: [
      { term: 'Sub-domain', meaning: 'The label in front of the registered domain — `seek` in `seek.study.iitm.ac.in`.' },
      { term: 'MIME type', meaning: 'The `content-type` value describing the body\'s format, e.g. `text/html`.' },
      { term: 'Mbps vs MBps', meaning: 'Megabits vs megabytes per second. A factor of 8 separates them.' },
      { term: 'RTT', meaning: 'Round-trip time: two one-way propagation delays.' },
      { term: 'Statelessness', meaning: 'The server retains nothing about a client between requests.' },
      { term: 'IaaS / PaaS / SaaS', meaning: 'Infrastructure, platform, or finished software delivered as a service.' },
      { term: 'Cold storage', meaning: 'Cheap, durable, slow-to-retrieve archival storage.' },
    ],
    commonMistakes: [
      'Mixing bits and bytes. Rates are bits per second; file sizes are bytes.',
      'Giving a one-way delay where the question asks for a round trip.',
      'Averaging bandwidth over 24 hours instead of summing rate x interval.',
      'Reading the last label of a hostname as the sub-domain.',
      'Claiming HTML5 is based on SGML, or that it broke backwards compatibility.',
    ],
    examFocus: [
      'Write the units on every intermediate value. Most wrong options in these papers are the right number in the wrong unit.',
      'For graph questions, tabulate interval, rate and duration before multiplying.',
      'For "which option is the sub-domain", split the hostname left to right.',
    ],
  },
  {
    id: 'tooling-git',
    name: 'Version Control',
    blurb: 'Branching, merging, staging and the everyday git commands.',
    subtopics: [
      { id: 'branch-merge', name: 'Branches & merging', summary: 'Checking out a target branch before merging others into it.' },
      { id: 'staging-remote', name: 'Staging & remotes', summary: 'Removing files from the index, and the pull-before-push workflow.' },
    ],
    learn: [
      { kind: 'text', value: '`git merge X` brings branch `X` **into the branch you are currently on**. So merging two feature branches into `main` means checking out `main` first, then merging each one:' },
      { kind: 'code', lang: 'shell', value: `git checkout main\ngit merge feature1\ngit merge feature2` },
      { kind: 'text', value: 'A sequence that merges without checking out `main` first merges into whatever branch happens to be current — and `git merge main` while on a feature branch does the opposite of what was asked.' },
      { kind: 'text', value: '`git rm --cached <file>` removes a file from the staging area (the index) but leaves it on disk — this is how you un-track a file you committed by mistake. `git rm <file>` removes it from **both** the index and the working tree. There is no `git del`.' },
      { kind: 'text', value: '**Push and pull order.** If a teammate pushed after you last fetched, your push is rejected: the remote branch has commits your local branch does not. Git does not silently merge on push. The fix, and the habit, is `git pull` *before* `git push`, so you integrate their work locally and resolve any conflict on your own machine.' },
      { kind: 'text', value: 'Note also that `git status` only knows about your local repository. It cannot warn you about a conflict with commits it has never seen — that only surfaces on fetch or push.' },
      { kind: 'text', value: 'A new repository starts on a single branch, historically named `master` and more recently `main` — both answers are correct depending on the git version and configuration.' },
    ],
    keyTerms: [
      { term: 'git merge X', meaning: 'Merges X into the current branch. Check out the destination first.' },
      { term: 'Staging area / index', meaning: 'The set of changes marked for the next commit.' },
      { term: 'git rm --cached', meaning: 'Removes from the index, keeps the file on disk.' },
      { term: 'Rejected push', meaning: 'The remote has commits you do not. Pull, integrate, then push.' },
    ],
    commonMistakes: [
      'Merging without checking out the destination branch.',
      'Expecting `git push` to merge remote changes automatically.',
      'Expecting `git status` to reveal a remote conflict.',
      'Reaching for `git del`, which does not exist.',
    ],
    examFocus: [
      'For a command sequence, track which branch is checked out after every line.',
      'For staging questions, decide separately what happens to the index and to the working tree.',
    ],
  },
  {
    id: 'app-design',
    name: 'Application Design',
    blurb: 'The MVC split and Nielsen\'s usability heuristics.',
    subtopics: [
      { id: 'mvc', name: 'Model, View, Controller', summary: 'What counts as the view of an application, including non-visual interfaces.' },
      { id: 'usability', name: 'Usability heuristics', summary: 'Nielsen\'s heuristics and diagnosing which one a design violates.' },
    ],
    learn: [
      { kind: 'text', value: 'In **MVC**, the model holds data and rules, the controller handles input and decides what happens, and the view is whatever the user perceives. "View" is not a synonym for "screen": for a voice assistant, the view is the AI voice and the status light — the parts that present state to the user. The physical casing is not part of the view, because it presents nothing.' },
      { kind: 'text', value: '**Nielsen\'s usability heuristics** are ten rules of thumb for interface design. Four of them account for almost every exam question:' },
      { kind: 'table', head: ['Heuristic', 'What it demands', 'Typical violation'], rows: [
        ['Visibility of system status', 'Always tell the user what is going on', 'A login form that does nothing visible when credentials are wrong'],
        ['Error prevention', 'Design so the mistake cannot be made', 'Allowing an invalid date to be typed at all'],
        ['Recognition rather than recall', 'Show options rather than making users remember them', 'Requiring a code the user saw on a previous screen'],
        ['Aesthetic and minimalist design', 'Do not compete with the relevant information', 'A page dense with irrelevant content'],
      ]},
      { kind: 'text', value: 'The distinction that catches people out is *status* versus *prevention*. Silence after a failed action is a visibility failure — the system knows something and is not saying it. Prevention is about stopping the failure from being possible in the first place.' },
    ],
    keyTerms: [
      { term: 'View (MVC)', meaning: 'Everything that presents application state to the user — visual or not.' },
      { term: 'Controller', meaning: 'The layer that receives input and decides what the application does about it.' },
      { term: 'Visibility of system status', meaning: 'Keep users informed about what is happening, through timely feedback.' },
      { term: 'Error prevention', meaning: 'Design out the possibility of the error rather than reporting it afterwards.' },
    ],
    commonMistakes: [
      'Restricting "view" to a graphical screen.',
      'Diagnosing missing feedback as "error prevention" instead of "visibility of system status".',
      'Counting a device\'s physical body as part of the view.',
    ],
    examFocus: [
      'Ask what the user perceives; that is the view.',
      'For heuristic questions, name what the system failed to do — that phrasing usually maps straight onto one heuristic.',
    ],
  },
];

export const topicById = new Map(topics.map((t) => [t.id, t]));
